In [1]:
# import libraries

import pandas as pd
pd.set_option('display.max_rows', 1000)

import sqlite3

In [2]:
# read in file and create dataframe
df = pd.read_csv('Assignment Log.csv')

### Part 1: Analysis 
#### Analyze and extract any interesting insights you can derive from the data set attached (each row represents the assignment of a job in our research queue, including some data about the analyst who received the assignment and the current state of the research queue). What can you infer? What do you think this means for us from a business perspective? 

### Part 2: Data modeling 
#### Assuming we are starting with the data set from Part 1 as our raw data table, how would you model this data in a data warehouse for analytical purposes? What tables would you create? What kinds of questions do you imagine business users would want to ask of this data, and how would they express them in your data model? Please use whatever tools you are comfortable with to answer this question and whatever flavor of SQL you are most familiar with. A github repo or gist is preferred.

### Exploratory Data Analysis

In [3]:
df.head(10)

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
0,06/22/2017 19:59:06,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Accepted Job,594bec5c95e2ce005840c23a,06/22/2017 12:12:12,review,1,review,0,13,14,4,6,2,0,1,1
1,06/22/2017 19:59:02,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Assigned Job,594bec5c95e2ce005840c23a,06/22/2017 12:12:12,review,1,review,1,13,15,5,6,2,0,1,1
2,06/22/2017 19:51:30,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Declined Job,594bec83fd2cf400280aa965,06/22/2017 12:12:51,writing,9,"sourcing, writing",1,12,12,5,5,1,0,0,1
3,06/22/2017 19:51:01,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,Accepted Job,594c1f5cd7e68f0028c9062c,06/22/2017 15:49:48,sourcing,1,"sourcing, writing",1,11,12,5,5,1,0,0,1
4,06/22/2017 19:50:58,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594bec83fd2cf400280aa965,06/22/2017 12:12:51,writing,8,"sourcing, writing",2,11,14,5,5,2,0,1,1
5,06/22/2017 19:50:58,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,Assigned Job,594c1f5cd7e68f0028c9062c,06/22/2017 15:49:48,sourcing,1,"sourcing, writing",2,11,14,5,5,2,0,1,1
6,06/22/2017 19:50:58,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Declined Job,594bec83fd2cf400280aa965,06/22/2017 12:12:51,writing,8,"sourcing, writing",2,11,14,5,5,2,0,1,1
7,06/22/2017 19:50:23,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594bec83fd2cf400280aa965,06/22/2017 12:12:51,writing,8,"sourcing, writing",1,11,14,5,5,2,0,1,1
8,06/22/2017 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,06/22/2017 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0
9,06/22/2017 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,06/22/2017 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0

In [4]:
df.shape

(791, 19)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 791 entries, 0 to 790
Data columns (total 19 columns):
Event occurred at           791 non-null object
Analyst                     791 non-null object
Quality score (sourcing)    791 non-null float64
Quality score (writing)     791 non-null float64
Action                      791 non-null object
Request                     791 non-null object
Request created at          791 non-null object
Job                         791 non-null object
Wait time (min)             791 non-null int64
Waiting for                 785 non-null object
Analysts available          791 non-null int64
Analysts occupied           791 non-null int64
Total jobs available        791 non-null int64
Review jobs available       791 non-null int64
Vetting jobs available      791 non-null int64
Planning jobs available     791 non-null int64
Editing jobs available      791 non-null int64
Sourcing jobs available     791 non-null int64
Writing jobs available      791 non-null int64
dtypes: float64(2), int64(10), object(7)
memory usage: 117.5+ KB

In [6]:
# convert Event occurred at and Request created at to datetime
df['Event occurred at'] = pd.to_datetime(df['Event occurred at'])
df['Request created at'] = pd.to_datetime(df['Request created at'])

In [7]:
# Min and Max times for creating requests

print('Min Date: ' + str(min(df['Request created at'])))
print('Max Date: ' + str(max(df['Request created at'])))

Min Date: 2017-06-19 13:43:51
Max Date: 2017-06-22 18:16:11

In [8]:
# Min and Max times for events

print('Min Date: ' + str(min(df['Event occurred at'])))
print('Max Date: ' + str(max(df['Event occurred at'])))

Min Date: 2017-06-21 20:15:42
Max Date: 2017-06-22 19:59:06

#### Handling Nulls

In [9]:
# check for any null values
df.isnull().sum()

Event occurred at           0
Analyst                     0
Quality score (sourcing)    0
Quality score (writing)     0
Action                      0
Request                     0
Request created at          0
Job                         0
Wait time (min)             0
Waiting for                 6
Analysts available          0
Analysts occupied           0
Total jobs available        0
Review jobs available       0
Vetting jobs available      0
Planning jobs available     0
Editing jobs available      0
Sourcing jobs available     0
Writing jobs available      0
dtype: int64

In [10]:
# find nulls
def find_nulls(df):
    null_columns=df.columns[df.isnull().any()]
    return df[df['Waiting for'].isnull()][null_columns]

In [11]:
find_nulls(df)

    Waiting for
195         NaN
340         NaN
392         NaN
454         NaN
595         NaN
723         NaN

In [12]:
df.loc[194:196]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
194,2017-06-22 14:31:08,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Assigned Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,planning,1,planning,5,16,8,0,3,5,0,0,0
195,2017-06-22 14:30:59,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,26,NaN,5,15,8,0,3,5,0,0,0
196,2017-06-22 14:30:54,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,26,sourcing,5,15,8,0,3,5,0,0,0

In [13]:
df.loc[[195], 'Waiting for'] = 'sourcing'

In [14]:
df.loc[339:341]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
339,2017-06-22 08:03:23,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,4,10,4,0,0,1,0,1,2
340,2017-06-22 08:01:25,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,NaN,3,10,3,0,0,1,0,0,2
341,2017-06-22 08:01:22,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,3,10,3,0,0,1,0,0,2

In [15]:
df.loc[[340], 'Waiting for'] = 'sourcing'

In [16]:
df.loc[391:393]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
391,2017-06-22 06:17:54,7e22ad15724c44543d1d4bcafd10c812,5.0,5.0,Assigned Job,594ae6fb4f06e20035d92345,2017-06-21 17:36:59,review,1,review,1,10,6,3,1,0,0,0,2
392,2017-06-22 06:13:40,766d3435eda76c4de9f034b8f97a0602,3.5,3.5,Accepted Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,NaN,0,9,6,3,1,0,0,0,2
393,2017-06-22 06:13:34,766d3435eda76c4de9f034b8f97a0602,3.5,3.5,Assigned Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,"sourcing, writing",1,9,7,3,1,0,0,0,3

In [17]:
df.loc[[392], 'Waiting for'] = 'sourcing, writing'

In [18]:
df.loc[453:455]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
453,2017-06-22 04:45:27,7e22ad15724c44543d1d4bcafd10c812,5.0,5.0,Assigned Job,594b00e23f82d10028f03be2,2017-06-21 19:27:30,review,1,review,1,14,7,3,1,0,0,0,3
454,2017-06-22 04:40:07,7e22ad15724c44543d1d4bcafd10c812,5.0,5.0,Accepted Job,594af3c6f3b9f600287eabe0,2017-06-21 18:31:34,review,1,NaN,0,15,7,3,1,0,0,0,3
455,2017-06-22 04:40:03,7e22ad15724c44543d1d4bcafd10c812,5.0,5.0,Assigned Job,594af3c6f3b9f600287eabe0,2017-06-21 18:31:34,review,1,review,1,15,8,4,1,0,0,0,3

In [19]:
df.loc[[454], 'Waiting for'] = 'review'

In [20]:
df.loc[594:596]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
594,2017-06-21 23:26:17,9fcbc63ff4c8bea5cea4efad782c87cf,5.0,5.0,Assigned Job,594b20ed3f82d10028f03c6c,2017-06-21 21:44:13,sourcing,1,sourcing,1,24,7,1,3,1,0,1,1
595,2017-06-21 23:23:02,f7f7591403c6c431053920223069550a,5.0,5.0,Accepted Job,594b20ee3f82d10028f03c74,2017-06-21 21:44:14,planning,1,NaN,0,23,7,1,3,1,0,1,1
596,2017-06-21 23:22:37,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Accepted Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,1,22,8,1,3,2,0,1,1

In [21]:
df.loc[[595], 'Waiting for'] = 'planning'

In [22]:
df.loc[722:724]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
722,2017-06-21 21:25:06,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Assigned Job,5949462dd9ae5200633f9640,2017-06-20 11:58:37,review,1,review,2,21,8,6,1,0,0,0,1
723,2017-06-21 21:24:44,206de922289a1f9f5ee250fc71308628,3.17,3.17,Accepted Job,594ae6fb4f06e20035d92345,2017-06-21 17:36:59,writing,1,NaN,1,20,8,6,1,0,0,0,1
724,2017-06-21 21:24:38,206de922289a1f9f5ee250fc71308628,3.17,3.17,Accepted Job,594ae6fb4f06e20035d92345,2017-06-21 17:36:59,writing,1,writing,1,20,8,6,1,0,0,0,1

In [23]:
df.loc[[723], 'Waiting for'] = 'writing'

In [24]:
# check for any null values
df.isnull().sum()

Event occurred at           0
Analyst                     0
Quality score (sourcing)    0
Quality score (writing)     0
Action                      0
Request                     0
Request created at          0
Job                         0
Wait time (min)             0
Waiting for                 0
Analysts available          0
Analysts occupied           0
Total jobs available        0
Review jobs available       0
Vetting jobs available      0
Planning jobs available     0
Editing jobs available      0
Sourcing jobs available     0
Writing jobs available      0
dtype: int64

#### Handling Duplicates

In [25]:
# find duplicates
# select duplicate rows except first occurrence based on all columns
def duplicates(df):
    duplicate_rows_df = df[df.duplicated()]
    return duplicate_rows_df

In [26]:
duplicates(df)

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
9,2017-06-22 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0
55,2017-06-22 18:26:42,e2333b2dc03032f12c8526e45243f0c1,0.00,0.00,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,22,sourcing,2,14,9,2,7,0,0,0,0

In [27]:
df.drop_duplicates(inplace = True)

In [28]:
# confirm duplicates removed
duplicates(df)

Empty DataFrame
Columns: [Event occurred at, Analyst, Quality score (sourcing), Quality score (writing), Action, Request, Request created at, Job, Wait time (min), Waiting for, Analysts available, Analysts occupied, Total jobs available, Review jobs available, Vetting jobs available, Planning jobs available, Editing jobs available, Sourcing jobs available, Writing jobs available]
Index: []

In [29]:
# inspecting the unique values found in columns
df.nunique()

Event occurred at           669
Analyst                      71
Quality score (sourcing)     37
Quality score (writing)      37
Action                        3
Request                      74
Request created at           72
Job                           7
Wait time (min)              39
Waiting for                  27
Analysts available            9
Analysts occupied            19
Total jobs available         17
Review jobs available        12
Vetting jobs available        8
Planning jobs available      13
Editing jobs available        3
Sourcing jobs available       5
Writing jobs available        7
dtype: int64

In [30]:
def values(column):
    print(df[column].value_counts())

In [31]:
print(values('Action'))
print(values('Job'))

Assigned Job    393
Accepted Job    301
Declined Job     95
Name: Action, dtype: int64
None
sourcing         209
writing          160
review           143
vetting           94
planning          94
source review     58
editing           31
Name: Job, dtype: int64
None

In [32]:
df[df['Request'] == '594c1e983b593b00281250ba']

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
8,2017-06-22 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0
10,2017-06-22 19:46:56,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",2,12,13,5,5,2,0,1,0
104,2017-06-22 16:02:15,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",0,19,3,2,1,0,0,0,0
105,2017-06-22 16:02:11,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",1,19,4,2,2,0,0,0,0

In [33]:
df[df['Request'] == '594bec7ffd2cf400280aa953']

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
188,2017-06-22 14:33:36,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,1,"editing, sourcing, writing",5,14,7,0,3,4,0,0,0
189,2017-06-22 14:33:35,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,1,"editing, sourcing, writing",5,14,7,0,3,4,0,0,0
190,2017-06-22 14:33:29,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,Assigned Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,1,"editing, sourcing, writing",6,14,8,0,3,4,0,1,0
195,2017-06-22 14:30:59,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,26,sourcing,5,15,8,0,3,5,0,0,0
196,2017-06-22 14:30:54,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,26,sourcing,5,15,8,0,3,5,0,0,0
197,2017-06-22 14:30:33,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,Assigned Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,26,sourcing,5,15,9,0,3,5,0,1,0
214,2017-06-22 13:32:46,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,planning,1,planning,4,12,9,0,1,8,0,0,0
215,2017-06-22 13:32:40,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Assigned Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,planning,1,planning,5,12,10,0,1,9,0,0,0

In [34]:
df.describe()

,Quality score (sourcing),Quality score (writing),Wait time (min),Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
count,789.000000,789.000000,789.000000,789.000000,789.000000,789.000000,789.000000,789.000000,789.000000,789.000000,789.000000,789.000000
mean,3.939759,3.939759,5.079848,2.676806,15.221800,8.049430,2.835234,1.617237,1.740177,0.087452,0.386565,1.382763
std,1.867008,1.867008,12.154044,1.871705,4.871728,3.647033,2.805130,1.613870,2.844475,0.295838,0.620195,1.548048
min,0.000000,0.000000,1.000000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.430000,4.430000,1.000000,1.000000,11.000000,5.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,4.830000,4.830000,1.000000,2.000000,14.000000,8.000000,2.000000,1.000000,0.000000,0.000000,0.000000,1.000000
75%,5.000000,5.000000,2.000000,4.000000,20.000000,11.000000,5.000000,2.000000,2.000000,0.000000,1.000000,2.000000
max,5.000000,5.000000,107.000000,8.000000,25.000000,16.000000,11.000000,7.000000,12.000000,2.000000,4.000000,6.000000

In [35]:
# Min and Max times for creating requests

print('Min quality score (sourcing) : ' + str(min(df['Quality score (sourcing)'])))
print('Max quality score (sourcing) : ' + str(max(df['Quality score (sourcing)'])))

Min quality score (sourcing) : 0.0
Max quality score (sourcing) : 5.0

In [36]:
df[df['Quality score (sourcing)'] == 0]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
24,2017-06-22 19:15:06,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,1,sourcing,1,15,9,3,5,1,0,0,0
27,2017-06-22 19:14:53,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,1,sourcing,3,14,12,3,6,2,0,1,0
28,2017-06-22 19:09:03,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,107,sourcing,2,14,11,2,6,2,0,1,0
29,2017-06-22 19:08:28,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,106,sourcing,2,14,11,2,6,2,0,1,0
30,2017-06-22 19:08:28,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,106,sourcing,2,14,11,2,6,2,0,1,0
33,2017-06-22 19:07:53,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,106,sourcing,3,13,12,3,6,2,0,1,0
34,2017-06-22 19:06:14,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,2,13,10,3,6,1,0,0,0
35,2017-06-22 19:06:08,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,3,13,12,3,6,2,0,1,0
40,2017-06-22 18:59:12,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,5,sourcing,2,12,10,3,7,0,0,0,0
41,2017-06-22 18:59:07,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,4,sourcing,4,12,12,3,7,1,0,1,0
54,2017-06-22 18:26:42,e2333b2dc03032f12c8526e45243f0c1,0.0,0.0,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,22,sourcing,2,14,9,2,7,0,0,0,0
56,2017-06-22 18:26:26,e2333b2dc03032f12c8526e45243f0c1,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,21,sourcing,4,14,11,2,7,1,0,1,0
57,2017-06-22 18:26:26,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,18,sourcing,4,14,11,2,7,1,0,1,0
58,2017-06-22 18:25:51,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,17,sourcing,4,15,11,2,7,1,0,1,0
59,2017-06-22 18:25:51,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,17,sourcing,4,15,11,2,7,1,0,1,0
60,2017-06-22 18:25:16,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,17,sourcing,4,15,11,2,7,1,0,1,0
81,2017-06-22 17:03:03,b89eb67419465a9e2c9da08dae6023e2,0.0,0.0,Accepted Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,35,sourcing,2,14,8,5,3,0,0,0,0
82,2017-06-22 17:02:54,b89eb67419465a9e2c9da08dae6023e2,0.0,0.0,Assigned Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,35,sourcing,4,14,9,5,3,0,0,1,0
98,2017-06-22 16:17:23,9286ce84f2401fbd6635f7d768c3cad1,0.0,0.0,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,2,sourcing,2,15,5,5,0,0,0,0,0
99,2017-06-22 16:17:17,9286ce84f2401fbd6635f7d768c3cad1,0.0,0.0,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,2,sourcing,3,15,6,5,0,0,0,1,0
106,2017-06-22 16:01:43,b89eb67419465a9e2c9da08dae6023e2,0.0,0.0,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,sourcing,0,18,4,2,2,0,0,0,0
107,2017-06-22 16:01:36,b89eb67419465a9e2c9da08dae6023e2,0.0,0.0,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,sourcing,1,18,5,2,2,0,0,1,0
108,2017-06-22 15:57:43,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Declined Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,6,sourcing,2,19,5,2,2,0,0,1,0
109,2017-06-22 15:57:08,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,6,sourcing,2,20,5,2,2,0,0,1,0
110,2017-06-22 15:57:08,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Declined Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,6,sourcing,2,20,5,2,2,0,0,1,0
113,2017-06-22 15:56:33,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,5,sourcing,3,19,6,2,3,0,0,1,0
114,2017-06-22 15:50:34,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Accepted Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,sourcing,2,sourcing,1,19,4,2,2,0,0,0,0
115,2017-06-22 15:50:07,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,sourcing,1,sourcing,2,19,5,2,2,0,0,1,0
116,2017-06-22 15:50:07,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Declined Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,sourcing,1,sourcing,2,19,5,2,2,0,0,1,0
117,2017-06-22 15:49:32,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,sourcing,1,sourcing,2,19,4,2,1,0,0,1,0
132,2017-06-22 15:30:50,95130c93e28b36bcb5ecd7e747b4d5c2,0.0,0.0,Declined Job,594c1abc73dd9c002873cdb8,2017-06-22 15:30:04,sourcing,16,sourcing,5,19,5,2,1,2,0,0,0
133,2017-06-22 15:30:15,95130c93e28b36bcb5ecd7e747b4d5c2,0.0,0.0,Assigned Job,594c1abc73dd9c002873cdb8,2017-06-22 15:30:04,sourcing,16,sourcing,5,18,6,2,1,2,0,1,0
161,2017-06-22 15:12:42,608b40f66ef114c6d9f5c95021290f69,0.0,0.0,Declined Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,sourcing,28,"sourcing, writing",8,13,9,2,4,2,0,1,0
162,2017-06-22 15:12:07,608b40f66ef114c6d9f5c95021290f69,0.0,0.0,Assigned Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,sourcing,28,"sourcing, writing",7,13,9,2,4,2,0,1,0
164,2017-06-22 15:12:07,608b40f66ef114c6d9f5c95021290f69,0.0,0.0,Declined Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,sourcing,28,"sourcing, writing",7,13,9,2,4,2,0,1,0
165,2017-06-22 15:11:32,608b40f66ef114c6d9f5c95021290f69,0.0,0.0,Assigned Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,sourcing,27,"sourcing, writing",6,13,9,2,4,2,0,1,0
198,2017-06-22 14:24:23,9286ce84f2401fbd6635f7d768c3cad1,0.0,0.0,Accepted Job,594bec5e95e2ce005840c252,2017-06-22 12:12:14,sourcing,11,sourcing,4,15,7,0,2,5,0,0,0
199,2017-06-22 14:24:07,9286ce84f2401fbd6635f7d768c3cad1,0.0,0.0,Assigned Job,594bec5e95e2ce005840c252,2017-06-22 12:12:14,sourcing,11,sourcing,6,15,8,0,2,5,0,1,0
202,2017-06-22 14:04:23,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Accepted Job,594bcdd680f13f00405cd4e8,2017-06-22 10:01:58,sourcing,4,sourcing,2,12,8,0,2,6,0,0,0
203,2017-06-22 14:04:14,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Assigned Job,594bcdd680f13f00405cd4e8,2017-06-22 10:01:58,sourcing,4,sourcing,3,12,10,0,2,7,0,1,0
230,2017-06-22 13:22:16,30ea4ac9222bfa53b3849df49d6f26f0,0.0,0.0,Accepted Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,sourcing,2,sourcing,5,9,10,0,0,10,0,0,0
232,2017-06-22 13:22:08,30ea4ac9222bfa53b3849df49d6f26f0,0.0,0.0,Assigned Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,sourcing,2,sourcing,7,9,11,0,0,10,0,1,0
255,2017-06-22 12:54:05,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Declined Job,594aead5ef88150028311172,2017-06-21 17:53:25,writing,1,sourcing,7,7,13,0,0,12,0,0,1
256,2017-06-22 12:53:30,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Assigned Job,594aead5ef88150028311172,2017-06-21 17:53:25,writing,1,"sourcing, writing",4,7,13,0,0,12,0,0,1
301,2017-06-22 09:58:49,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Accepted Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,28,sourcing,1,9,0,0,0,0,0,0,0
302,2017-06-22 09:58:24,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Assigned Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,27,sourcing,3,9,2,0,0,1,0,1,0
303,2017-06-22 09:58:24,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Declined Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,7,sourcing,3,9,2,0,0,1,0,1,0
304,2017-06-22 09:57:49,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Assigned Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,6,sourcing,3,9,2,0,0,1,0,1,0
305,2017-06-22 09:57:49,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Declined Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,6,sourcing,3,9,2,0,0,1,0,1,0
306,2017-06-22 09:57:14,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Assigned Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,5,sourcing,3,10,2,0,0,1,0,1,0
338,2017-06-22 08:03:26,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,4,10,3,0,0,1,0,0,2
339,2017-06-22 08:03:23,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,4,10,4,0,0,1,0,1,2
340,2017-06-22 08:01:25,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,3,10,3,0,0,1,0,0,2
341,2017-06-22 08:01:22,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,3,10,3,0,0,1,0,0,2
342,2017-06-22 08:01:20,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,3,10,3,0,0,1,0,0,2
343,2017-06-22 08:01:03,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,5,10,4,0,0,1,0,1,2
344,2017-06-22 08:01:03,1f8d8b08a994331e419d24293ce9e7b0,0.0,0.0,Declined Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,7,sourcing,5,10,4,0,0,1,0,1,2
345,2017-06-22 08:00:28,1f8d8b08a994331e419d24293ce9e7b0,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,7,sourcing,4,10,3,0,0,0,0,1,2
346,2017-06-22 08:00:28,1f8d8b08a994331e419d24293ce9e7b0,0.0,0.0,Declined Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,7,sourcing,4,10,3,0,0,0,0,1,2
347,2017-06-22 07:59:53,1f8d8b08a994331e419d24293ce9e7b0,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,6,sourcing,2,11,2,0,0,0,0,1,1
386,2017-06-22 06:20:10,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,0,10,5,1,1,0,0,0,3
387,2017-06-22 06:20:08,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,1,10,6,1,1,0,0,1,3
415,2017-06-22 05:39:53,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Assigned Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,writing,3,12,5,2,0,0,0,0,3
416,2017-06-22 05:39:53,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Declined Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,writing,3,12,5,2,0,0,0,0,3
417,2017-06-22 05:39:18,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Assigned Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,writing,1,12,5,2,0,0,0,0,3
460,2017-06-22 04:27:11,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Accepted Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,5,sourcing,0,15,10,6,1,0,0,0,3
461,2017-06-22 04:27:06,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Assigned Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,5,sourcing,1,15,11,6,1,0,0,1,3
492,2017-06-22 02:57:03,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Accepted Job,594b31f09d87570035cccafd,2017-06-21 22:56:48,sourcing,26,sourcing,1,12,12,5,1,0,1,0,5
493,2017-06-22 02:56:55,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594b31f09d87570035cccafd,2017-06-21 22:56:48,sourcing,26,sourcing,2,12,14,5,1,1,1,1,5
510,2017-06-22 02:05:27,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Accepted Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,1,writing,0,15,12,5,1,1,1,0,4
511,2017-06-22 02:05:22,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Assigned Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,1,writing,1,15,13,5,1,1,1,0,5
512,2017-06-22 02:04:20,77b8ab28b9e95edb3a69ca7a6d352ec8,0.0,0.0,Accepted Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,1,sourcing,1,14,13,5,1,1,1,0,5
513,2017-06-22 02:04:15,77b8ab28b9e95edb3a69ca7a6d352ec8,0.0,0.0,Assigned Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,1,sourcing,1,14,14,5,1,1,1,1,5
514,2017-06-22 02:03:43,5233d783ae5bf0483cf49549cbc594f8,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,0,13,14,5,1,1,1,1,5
515,2017-06-22 02:03:40,5233d783ae5bf0483cf49549cbc594f8,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,1,13,15,5,1,1,1,2,5
516,2017-06-22 01:59:14,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,editing,4,editing,1,14,13,5,1,1,0,1,5
517,2017-06-22 01:59:06,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,editing,3,editing,2,14,14,5,1,1,1,1,5
518,2017-06-22 01:59:05,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Declined Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,editing,3,editing,2,14,14,5,1,1,1,1,5
521,2017-06-22 01:58:30,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,editing,3,editing,2,13,15,6,1,1,1,1,5
528,2017-06-22 01:40:09,77b8ab28b9e95edb3a69ca7a6d352ec8,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,0,18,10,5,1,0,0,0,4
529,2017-06-22 01:40:05,77b8ab28b9e95edb3a69ca7a6d352ec8,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,1,18,11,5,1,0,0,1,4
530,2017-06-22 01:39:46,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b31f09d87570035cccafd,2017-06-21 22:56:48,vetting,1,"vetting, editing, sourcing",1,17,11,5,1,0,0,1,4
533,2017-06-22 01:39:30,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b31f09d87570035cccafd,2017-06-21 22:56:48,vetting,1,"vetting, editing, sourcing",2,16,13,6,2,0,0,1,4
552,2017-06-22 01:17:55,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b1abfa6992500289d6040,2017-06-21 21:17:51,vetting,1,"vetting, editing, sourcing",1,17,12,9,2,0,0,0,1
553,2017-06-22 01:17:52,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b1abfa6992500289d6040,2017-06-21 21:17:51,vetting,1,"vetting, editing, sourcing",1,17,12,9,2,0,0,0,1
554,2017-06-22 01:17:39,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b1abfa6992500289d6040,2017-06-21 21:17:51,vetting,1,"vetting, editing, sourcing",2,17,12,9,2,0,0,0,1
566,2017-06-22 00:20:28,b599bfb42906772db81ac90137fc1916,0.0,0.0,Accepted Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,1,sourcing,1,20,9,5,2,0,0,0,2
567,2017-06-22 00:20:26,b599bfb42906772db81ac90137fc1916,0.0,0.0,Assigned Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,1,sourcing,2,20,10,5,2,0,0,1,2
582,2017-06-22 00:00:27,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b20ea3f82d10028f03c54,2017-06-21 21:44:10,sourcing,1,"editing, sourcing",0,19,12,4,2,1,0,3,2
583,2017-06-22 00:00:13,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b20ea3f82d10028f03c54,2017-06-21 21:44:10,sourcing,1,"editing, sourcing",1,19,13,4,2,1,0,4,2
584,2017-06-21 23:38:17,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b33d6fee3760035a1a540,2017-06-21 23:04:54,vetting,1,"vetting, editing, sourcing",0,22,10,3,2,1,0,3,1
585,2017-06-21 23:38:16,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b33d6fee3760035a1a540,2017-06-21 23:04:54,vetting,1,"vetting, editing, sourcing",1,22,11,3,3,1,0,3,1
586,2017-06-21 23:37:09,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594ae6fb4f06e20035d92345,2017-06-21 17:36:59,writing,1,"editing, sourcing, writing",1,22,11,3,3,1,0,3,1
596,2017-06-21 23:22:37,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Accepted Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,1,22,8,1,3,2,0,1,1
597,2017-06-21 23:22:36,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Accepted Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,1,22,8,1,3,2,0,1,1
598,2017-06-21 23:22:35,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Accepted Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,1,22,8,1,3,2,0,1,1
600,2017-06-21 23:22:30,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Assigned Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,2,22,9,1,3,2,0,2,1
606,2017-06-21 23:12:02,ea5354c723ba83f2c412c238b133e84a,0.0,0.0,Accepted Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",2,23,8,1,3,2,0,1,1
608,2017-06-21 23:11:54,ea5354c723ba83f2c412c238b133e84a,0.0,0.0,Assigned Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",3,23,9,1,3,2,0,1,2
620,2017-06-21 23:06:55,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Accepted Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",4,24,7,1,3,2,0,0,1
621,2017-06-21 23:06:39,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Assigned Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",3,24,8,1,3,2,0,0,2
622,2017-06-21 23:05:29,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Declined Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2,"sourcing, writing",2,25,7,0,3,2,0,0,2
623,2017-06-21 23:04:54,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Assigned Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",2,25,6,0,2,2,0,0,2
624,2017-06-21 23:04:54,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Declined Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",2,25,6,0,2,2,0,0,2
626,2017-06-21 23:04:19,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Assigned Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",3,24,7,0,2,2,0,0,3
628,2017-06-21 23:02:02,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Accepted Job,594b20ea3f82d10028f03c54,2017-06-21 21:44:10,sourcing,1,sourcing,1,22,7,0,2,2,0,0,3
629,2017-06-21 23:02:01,b692db6843c42f5ce686fcdfda4e0b62,0.0,0.0,Accepted Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,1,sourcing,2,22,8,0,2,2,0,1,3
630,2017-06-21 23:01:59,b692db6843c42f5ce686fcdfda4e0b62,0.0,0.0,Assigned Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,1,sourcing,3,22,10,0,2,3,0,2,3
631,2017-06-21 23:01:59,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594b20ea3f82d10028f03c54,2017-06-21 21:44:10,sourcing,1,sourcing,3,22,10,0,2,3,0,2,3
642,2017-06-21 22:38:56,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Accepted Job,594aead5ef88150028311172,2017-06-21 17:53:25,sourcing,2,sourcing,0,23,6,1,1,3,0,0,1
643,2017-06-21 22:38:50,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594aead5ef88150028311172,2017-06-21 17:53:25,sourcing,2,sourcing,1,22,9,1,1,4,0,1,2
705,2017-06-21 21:34:05,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Accepted Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,1,sourcing,0,20,8,6,1,0,0,0,1
706,2017-06-21 21:33:52,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,1,sourcing,2,20,10,6,1,1,0,1,1
716,2017-06-21 21:26:19,b599bfb42906772db81ac90137fc1916,0.0,0.0,Accepted Job,59485c262e71030033104e3c,2017-06-19 19:20:06,sourcing,1,sourcing,2,21,6,5,1,0,0,0,0
720,2017-06-21 21:26:17,b599bfb42906772db81ac90137fc1916,0.0,0.0,Assigned Job,59485c262e71030033104e3c,2017-06-19 19:20:06,sourcing,1,sourcing,4,21,8,5,1,0,0,1,1
732,2017-06-21 21:20:09,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Accepted Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,sourcing,3,sourcing,2,21,9,6,1,0,0,0,2
733,2017-06-21 21:19:51,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,sourcing,2,sourcing,3,21,10,6,1,0,0,1,2
734,2017-06-21 21:19:16,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,sourcing,3,sourcing,5,21,10,6,1,0,0,1,2
735,2017-06-21 21:19:16,5238b0785b5576f5ffe665136df9244f,0.0,0.0,Declined Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,sourcing,6,sourcing,5,21,10,6,1,0,0,1,2

In [37]:
df[df['Action'] == 'Declined Job'].describe()

,Quality score (sourcing),Quality score (writing),Wait time (min),Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
count,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000
mean,3.294211,3.294211,12.294737,3.494737,16.431579,7.842105,2.800000,2.031579,1.463158,0.031579,0.536842,0.978947
std,2.205641,2.205641,20.636610,1.934423,5.037419,3.412480,2.611757,1.932106,2.220842,0.175804,0.649231,1.263051
min,0.000000,0.000000,1.000000,1.000000,7.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,2.000000,2.000000,13.000000,5.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,4.500000,4.500000,3.000000,3.000000,17.000000,8.000000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,4.930000,4.930000,14.500000,5.000000,20.000000,10.000000,5.000000,3.000000,2.000000,0.000000,1.000000,2.000000
max,5.000000,5.000000,107.000000,8.000000,25.000000,14.000000,9.000000,7.000000,12.000000,1.000000,3.000000,5.000000

In [38]:
df.groupby('Analyst')['Request'].count()

Analyst
00360b3f177375b01b795a4be7b4686c     8
008fa95f5c94985e2d44047aeac31655     7
052066814364850e1a17a90d576dd904     3
0c2680433387fb4cf51a3546296f8422    18
0e9802516f8a79dd0d45211dd4ee74af    24
1f8d8b08a994331e419d24293ce9e7b0     4
206de922289a1f9f5ee250fc71308628     7
2d0f64a208f69a70ec415cfccb59cc24     4
2df8ce7d317c7d89dfa95be7695d2de0     8
30ea4ac9222bfa53b3849df49d6f26f0     2
32553d485988e2ddcf0f701c60754f2d     4
36ee9fc3bade4a4f71c2a6e5c2bd8862     4
39012c98c8fb80752d2bbcc3dc285230     8
39b71201151caf98fd10afce50cfc83e    12
3a29165b73c047e745934c2cbbfaac1b     4
3a8a0b0323b02a707535fe7d65821de3     2
482e9b14d8d59b748320f89074362746     8
4bb6e496f0c92286dee7eed7038ddd9d     8
5078cc506436a8668c0b6de594842fcf     1
5233d783ae5bf0483cf49549cbc594f8     2
5238b0785b5576f5ffe665136df9244f     4
57ef46a92ecee8e187f4d450e92651ea     2
608b40f66ef114c6d9f5c95021290f69     4
62060850630c7afe54fd59151413d237    46
632a6492e9ff20cc4a442245836424e5     6
642782c690c8d963c487300a4751e220    42
6b19235b9269df81b6da879771bf40bc     8
6c6bd5e891c4015e534773dfb19f29b0    19
710dbda77cade1eced9c735c08e6e38d    14
732e4a29b2e318bce3c1e923276ddf51    42
766d3435eda76c4de9f034b8f97a0602     3
77b8ab28b9e95edb3a69ca7a6d352ec8     4
795930bc4ed320777ad76b46da2ed66d    14
7e22ad15724c44543d1d4bcafd10c812    28
8258591d197a3936de0f7ee021ab9e0e    17
83f00c2268afaf459715f4c52e16dd23     2
85c7b78e76b5232cd38014ea4cdc8f56    34
9286ce84f2401fbd6635f7d768c3cad1     4
94959cf2d0b592d0fa1e5e9cf760a1c7    26
95130c93e28b36bcb5ecd7e747b4d5c2     2
98de7e62209a07eee6ec8dc984911042    10
9fa24ddce8fd9d1526d9d7451304fc74    17
9fcbc63ff4c8bea5cea4efad782c87cf    40
a09c8906073b4c0b75e3100b857b982a    72
a29fe6d26c1a49ff4a3c876eaee0a1af     4
b599bfb42906772db81ac90137fc1916     4
b692db6843c42f5ce686fcdfda4e0b62     2
b89eb67419465a9e2c9da08dae6023e2     4
bcd8d747b5af397febc04228293f747f     2
c033808b89b50e6f550caf266470f090     8
c2d7982e24aadeea8921108d0eb756d8     8
c2dcc0b178176d7e6b185df9bd1cb4f2    16
c9401f82fdedf3cd080a03bafe3447c7    17
caf77e4ba6154e998b352cc92c685f80    15
d5aa695af013ee5baaeeccfb7ca50c80    10
d6eaa4eeb52b4d62ec78299454763870    15
d74c4a7423dd3ee0a78de5481c364823     4
d8e25a290ea51352bf9100a99c475f6d    19
d9837e646a15a4fdd823531178b2d62e     8
dddcdea13df8232803957a5d9c847aae    13
de71db592b02c988670ca3d301a02568     4
dee1febfdeb9c90a41759cb330c72fd4     6
e2333b2dc03032f12c8526e45243f0c1     2
e817dd4305458b293cbeb3015da99565     2
e8a2b0b2e2234a89dc52dd8a3e0f79e6     4
e9468b4c33f88d6937c4ad2bea8bbc2f     2
ea452a7456e38887ca8b98f4e131d224     2
ea5354c723ba83f2c412c238b133e84a     2
ef7e6e9fd91d89f2e31b26b9feaec787     2
f3b93c5ae97215ae15fa63b5f0fc30e1     2
f7f7591403c6c431053920223069550a    14
Name: Request, dtype: int64

In [39]:
df.groupby(['Request', 'Analyst'])['Wait time (min)'].sum()

Request                   Analyst
59480d57e759070028da6467  a09c8906073b4c0b75e3100b857b982a      2
                          d8e25a290ea51352bf9100a99c475f6d      7
59485c262e71030033104e3c  642782c690c8d963c487300a4751e220      2
                          7e22ad15724c44543d1d4bcafd10c812      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          b599bfb42906772db81ac90137fc1916      2
                          e817dd4305458b293cbeb3015da99565      2
59486e7af5874900429ce273  9fcbc63ff4c8bea5cea4efad782c87cf      2
5949462dd9ae5200633f9640  39012c98c8fb80752d2bbcc3dc285230      2
                          9fa24ddce8fd9d1526d9d7451304fc74     10
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
59494c13d9ae5200633f9695  a09c8906073b4c0b75e3100b857b982a      2
5949a81c4d1319005556396c  39012c98c8fb80752d2bbcc3dc285230      4
                          632a6492e9ff20cc4a442245836424e5      2
                          642782c690c8d963c487300a4751e220      4
                          710dbda77cade1eced9c735c08e6e38d      2
                          732e4a29b2e318bce3c1e923276ddf51      2
                          795930bc4ed320777ad76b46da2ed66d      2
                          7e22ad15724c44543d1d4bcafd10c812      2
                          8258591d197a3936de0f7ee021ab9e0e      2
                          9fa24ddce8fd9d1526d9d7451304fc74    107
                          a09c8906073b4c0b75e3100b857b982a      2
                          b692db6843c42f5ce686fcdfda4e0b62      2
                          c9401f82fdedf3cd080a03bafe3447c7      2
                          d74c4a7423dd3ee0a78de5481c364823      2
                          de71db592b02c988670ca3d301a02568      2
5949bdb4fe2f5d005b4f4910  39012c98c8fb80752d2bbcc3dc285230      2
5949bdbcfe2f5d005b4f4928  c033808b89b50e6f550caf266470f090      2
5949e376f03c130028baa724  482e9b14d8d59b748320f89074362746      2
                          dddcdea13df8232803957a5d9c847aae      6
594a4325499a400071d4cca4  9fcbc63ff4c8bea5cea4efad782c87cf      2
594a536d220b450040dc0182  9fcbc63ff4c8bea5cea4efad782c87cf      2
594a5e5566cb69006fdcf09d  008fa95f5c94985e2d44047aeac31655      9
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          c2dcc0b178176d7e6b185df9bd1cb4f2      2
594a8f5664251c002831f4c5  2d0f64a208f69a70ec415cfccb59cc24      8
                          a09c8906073b4c0b75e3100b857b982a      4
                          d5aa695af013ee5baaeeccfb7ca50c80      4
594a8fd422b3c50028e71976  0c2680433387fb4cf51a3546296f8422      2
                          2d0f64a208f69a70ec415cfccb59cc24      2
                          482e9b14d8d59b748320f89074362746      2
                          642782c690c8d963c487300a4751e220      4
                          732e4a29b2e318bce3c1e923276ddf51      2
                          766d3435eda76c4de9f034b8f97a0602      2
                          795930bc4ed320777ad76b46da2ed66d      3
                          7e22ad15724c44543d1d4bcafd10c812      2
                          c9401f82fdedf3cd080a03bafe3447c7      3
                          caf77e4ba6154e998b352cc92c685f80      1
594a9ce6c864e200288e766b  1f8d8b08a994331e419d24293ce9e7b0     27
                          2df8ce7d317c7d89dfa95be7695d2de0      2
                          5233d783ae5bf0483cf49549cbc594f8      2
                          57ef46a92ecee8e187f4d450e92651ea      2
                          642782c690c8d963c487300a4751e220      2
                          77b8ab28b9e95edb3a69ca7a6d352ec8      2
                          795930bc4ed320777ad76b46da2ed66d     47
                          7e22ad15724c44543d1d4bcafd10c812      2
                          98de7e62209a07eee6ec8dc984911042      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          a29fe6d26c1a49ff4a3c876eaee0a1af      4
                          caf77e4ba6154e998b352cc92c685f80      2
594aa36664251c002831f51e  9fcbc63ff4c8bea5cea4efad782c87cf      2
594ab554c864e200288e76ef  0c2680433387fb4cf51a3546296f8422      2
                          0e9802516f8a79dd0d45211dd4ee74af      2
                          482e9b14d8d59b748320f89074362746      2
                          795930bc4ed320777ad76b46da2ed66d     54
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          c033808b89b50e6f550caf266470f090      2
                          c9401f82fdedf3cd080a03bafe3447c7    197
                          caf77e4ba6154e998b352cc92c685f80      2
                          d6eaa4eeb52b4d62ec78299454763870      2
                          d9837e646a15a4fdd823531178b2d62e      7
                          dddcdea13df8232803957a5d9c847aae      4
                          e8a2b0b2e2234a89dc52dd8a3e0f79e6      2
                          ea5354c723ba83f2c412c238b133e84a      2
594ada897a05b40035f08be4  32553d485988e2ddcf0f701c60754f2d      2
                          a09c8906073b4c0b75e3100b857b982a      2
594ae6944f06e20035d92325  0e9802516f8a79dd0d45211dd4ee74af      4
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
594ae6994f06e20035d92335  732e4a29b2e318bce3c1e923276ddf51      7
                          9fcbc63ff4c8bea5cea4efad782c87cf      7
                          a09c8906073b4c0b75e3100b857b982a      2
594ae6fa4f06e20035d9233d  a09c8906073b4c0b75e3100b857b982a      2
594ae6fb4f06e20035d92345  206de922289a1f9f5ee250fc71308628      3
                          5078cc506436a8668c0b6de594842fcf      1
                          632a6492e9ff20cc4a442245836424e5      5
                          7e22ad15724c44543d1d4bcafd10c812      2
                          9fcbc63ff4c8bea5cea4efad782c87cf      4
                          c2dcc0b178176d7e6b185df9bd1cb4f2      1
                          caf77e4ba6154e998b352cc92c685f80      2
                          d6eaa4eeb52b4d62ec78299454763870      5
594aead5ef88150028311172  0c2680433387fb4cf51a3546296f8422     32
                          0e9802516f8a79dd0d45211dd4ee74af      2
                          206de922289a1f9f5ee250fc71308628      2
                          39b71201151caf98fd10afce50cfc83e     50
                          4bb6e496f0c92286dee7eed7038ddd9d      2
                          98de7e62209a07eee6ec8dc984911042      4
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          bcd8d747b5af397febc04228293f747f      3
                          d9837e646a15a4fdd823531178b2d62e      2
594aec513f82d10028f03b9a  a09c8906073b4c0b75e3100b857b982a      2
594af29d3f82d10028f03bb2  0e9802516f8a79dd0d45211dd4ee74af      4
                          32553d485988e2ddcf0f701c60754f2d      2
                          39b71201151caf98fd10afce50cfc83e      2
                          642782c690c8d963c487300a4751e220      6
                          766d3435eda76c4de9f034b8f97a0602      1
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          ef7e6e9fd91d89f2e31b26b9feaec787     10
                          f3b93c5ae97215ae15fa63b5f0fc30e1      2
594af3c6f3b9f600287eabe0  482e9b14d8d59b748320f89074362746      2
                          7e22ad15724c44543d1d4bcafd10c812      2
                          a09c8906073b4c0b75e3100b857b982a      2
594b00e23f82d10028f03be2  6c6bd5e891c4015e534773dfb19f29b0      2
                          7e22ad15724c44543d1d4bcafd10c812      2
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          d8e25a290ea51352bf9100a99c475f6d      2
594b0303f3b9f600287eac2b  0e9802516f8a79dd0d45211dd4ee74af      2
                          4bb6e496f0c92286dee7eed7038ddd9d      2
                          642782c690c8d963c487300a4751e220      2
                          7e22ad15724c44543d1d4bcafd10c812      4
                          85c7b78e76b5232cd38014ea4cdc8f56      4
                          9fa24ddce8fd9d1526d9d7451304fc74      2
                          caf77e4ba6154e998b352cc92c685f80      2
                          d6eaa4eeb52b4d62ec78299454763870      2
                          d8e25a290ea51352bf9100a99c475f6d      2
594b06bf6cdeef002881af7b  0e9802516f8a79dd0d45211dd4ee74af      2
                          8258591d197a3936de0f7ee021ab9e0e      8
594b06c06cdeef002881af83  206de922289a1f9f5ee250fc71308628      2
                          5238b0785b5576f5ffe665136df9244f     23
                          8258591d197a3936de0f7ee021ab9e0e      3
                          98de7e62209a07eee6ec8dc984911042      5
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          c2dcc0b178176d7e6b185df9bd1cb4f2     13
                          d5aa695af013ee5baaeeccfb7ca50c80      3
594b1abfa6992500289d6040  0c2680433387fb4cf51a3546296f8422      2
                          39b71201151caf98fd10afce50cfc83e      2
                          3a29165b73c047e745934c2cbbfaac1b      2
                          642782c690c8d963c487300a4751e220     14
                          6c6bd5e891c4015e534773dfb19f29b0      3
                          85c7b78e76b5232cd38014ea4cdc8f56    289
                          c2dcc0b178176d7e6b185df9bd1cb4f2      3
594b20ea3f82d10028f03c54  642782c690c8d963c487300a4751e220      2
                          732e4a29b2e318bce3c1e923276ddf51      3
                          8258591d197a3936de0f7ee021ab9e0e      2
                          85c7b78e76b5232cd38014ea4cdc8f56      7
                          a09c8906073b4c0b75e3100b857b982a      2
                          c2dcc0b178176d7e6b185df9bd1cb4f2      2
                          d8e25a290ea51352bf9100a99c475f6d      2
                          f7f7591403c6c431053920223069550a     27
594b20eb3f82d10028f03c5c  0e9802516f8a79dd0d45211dd4ee74af      4
                          36ee9fc3bade4a4f71c2a6e5c2bd8862      4
                          39b71201151caf98fd10afce50cfc83e      2
                          642782c690c8d963c487300a4751e220      2
                          732e4a29b2e318bce3c1e923276ddf51      3
                          85c7b78e76b5232cd38014ea4cdc8f56     85
                          a09c8906073b4c0b75e3100b857b982a      7
                          caf77e4ba6154e998b352cc92c685f80      5
                          f7f7591403c6c431053920223069550a      2
594b20ec3f82d10028f03c64  0c2680433387fb4cf51a3546296f8422      2
                          732e4a29b2e318bce3c1e923276ddf51      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          e8a2b0b2e2234a89dc52dd8a3e0f79e6      2
594b20ed3f82d10028f03c6c  7e22ad15724c44543d1d4bcafd10c812      2
                          9fcbc63ff4c8bea5cea4efad782c87cf      4
                          a09c8906073b4c0b75e3100b857b982a      7
                          f7f7591403c6c431053920223069550a      2
594b20ee3f82d10028f03c74  7e22ad15724c44543d1d4bcafd10c812      2
                          85c7b78e76b5232cd38014ea4cdc8f56      2
                          a09c8906073b4c0b75e3100b857b982a      5
                          d6eaa4eeb52b4d62ec78299454763870      2
                          f7f7591403c6c431053920223069550a      2
594b20ef3f82d10028f03c7c  2df8ce7d317c7d89dfa95be7695d2de0     10
                          642782c690c8d963c487300a4751e220    131
                          710dbda77cade1eced9c735c08e6e38d      2
                          77b8ab28b9e95edb3a69ca7a6d352ec8      2
                          85c7b78e76b5232cd38014ea4cdc8f56      8
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          b599bfb42906772db81ac90137fc1916      2
                          d6eaa4eeb52b4d62ec78299454763870      2
                          e9468b4c33f88d6937c4ad2bea8bbc2f      2
                          f7f7591403c6c431053920223069550a      2
594b31f09d87570035cccafd  052066814364850e1a17a90d576dd904      3
                          39b71201151caf98fd10afce50cfc83e      2
                          4bb6e496f0c92286dee7eed7038ddd9d      2
                          795930bc4ed320777ad76b46da2ed66d     51
                          7e22ad15724c44543d1d4bcafd10c812    219
                          8258591d197a3936de0f7ee021ab9e0e     52
                          c2dcc0b178176d7e6b185df9bd1cb4f2      2
                          caf77e4ba6154e998b352cc92c685f80      2
                          dee1febfdeb9c90a41759cb330c72fd4      2
                          ea452a7456e38887ca8b98f4e131d224      2
594b33d6fee3760035a1a540  7e22ad15724c44543d1d4bcafd10c812      2
                          c2dcc0b178176d7e6b185df9bd1cb4f2      2
594b52f717d10a00289676dd  6c6bd5e891c4015e534773dfb19f29b0      8
594b6c6a96165a002896b124  6c6bd5e891c4015e534773dfb19f29b0      6
594b945bf8b866004036d9c3  0e9802516f8a79dd0d45211dd4ee74af      8
                          2df8ce7d317c7d89dfa95be7695d2de0     55
                          39b71201151caf98fd10afce50cfc83e     60
                          642782c690c8d963c487300a4751e220     47
                          6b19235b9269df81b6da879771bf40bc     24
                          732e4a29b2e318bce3c1e923276ddf51      2
                          de71db592b02c988670ca3d301a02568      2
594b9dd57c3b31004d97a6dc  4bb6e496f0c92286dee7eed7038ddd9d      2
                          732e4a29b2e318bce3c1e923276ddf51      2
                          d6eaa4eeb52b4d62ec78299454763870      2
594babd780f13f00405cd449  642782c690c8d963c487300a4751e220      2
594baca737b4b7004b683616  642782c690c8d963c487300a4751e220      2
                          732e4a29b2e318bce3c1e923276ddf51      2
594bcdd580f13f00405cd4e0  dee1febfdeb9c90a41759cb330c72fd4      2
594bcdd680f13f00405cd4e8  2df8ce7d317c7d89dfa95be7695d2de0      8
                          3a8a0b0323b02a707535fe7d65821de3      2
                          710dbda77cade1eced9c735c08e6e38d      2
                          83f00c2268afaf459715f4c52e16dd23     14
                          9fa24ddce8fd9d1526d9d7451304fc74     40
                          d8e25a290ea51352bf9100a99c475f6d      2
                          dee1febfdeb9c90a41759cb330c72fd4      2
594bcdd780f13f00405cd4f0  710dbda77cade1eced9c735c08e6e38d      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          d74c4a7423dd3ee0a78de5481c364823     52
594bde9ffd2cf400280aa920  732e4a29b2e318bce3c1e923276ddf51      2
594bebaa632eb100405ab4c3  0c2680433387fb4cf51a3546296f8422     93
                          642782c690c8d963c487300a4751e220      4
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          b89eb67419465a9e2c9da08dae6023e2     70
                          dddcdea13df8232803957a5d9c847aae      9
594bec5a95e2ce005840c22a  0e9802516f8a79dd0d45211dd4ee74af      2
                          732e4a29b2e318bce3c1e923276ddf51      5
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          9fa24ddce8fd9d1526d9d7451304fc74    107
594bec5b95e2ce005840c232  30ea4ac9222bfa53b3849df49d6f26f0      4
                          3a29165b73c047e745934c2cbbfaac1b     16
                          732e4a29b2e318bce3c1e923276ddf51      3
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          a09c8906073b4c0b75e3100b857b982a      4
594bec5c95e2ce005840c23a  732e4a29b2e318bce3c1e923276ddf51      1
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
594bec5c95e2ce005840c242  732e4a29b2e318bce3c1e923276ddf51      2
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          9fa24ddce8fd9d1526d9d7451304fc74     30
                          a09c8906073b4c0b75e3100b857b982a      2
                          d6eaa4eeb52b4d62ec78299454763870     32
594bec5d95e2ce005840c24a  732e4a29b2e318bce3c1e923276ddf51      2
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
594bec5e95e2ce005840c252  732e4a29b2e318bce3c1e923276ddf51      2
                          9286ce84f2401fbd6635f7d768c3cad1     22
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          c033808b89b50e6f550caf266470f090      8
594bec5e95e2ce005840c25a  710dbda77cade1eced9c735c08e6e38d      2
                          732e4a29b2e318bce3c1e923276ddf51      3
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
594bec7ffd2cf400280aa953  94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          9fa24ddce8fd9d1526d9d7451304fc74     78
                          d5aa695af013ee5baaeeccfb7ca50c80      3
594bec81fd2cf400280aa95c  608b40f66ef114c6d9f5c95021290f69    111
                          85c7b78e76b5232cd38014ea4cdc8f56     15
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          c2d7982e24aadeea8921108d0eb756d8     13
594bec83fd2cf400280aa965  0c2680433387fb4cf51a3546296f8422     56
                          0e9802516f8a79dd0d45211dd4ee74af      2
                          85c7b78e76b5232cd38014ea4cdc8f56     33
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          98de7e62209a07eee6ec8dc984911042      5
                          a09c8906073b4c0b75e3100b857b982a      2
                          c2d7982e24aadeea8921108d0eb756d8    129
                          dddcdea13df8232803957a5d9c847aae     28
594bfcde70709600281a12b8  62060850630c7afe54fd59151413d237      7
                          642782c690c8d963c487300a4751e220      2
594c0645b99a200028ff12fe  62060850630c7afe54fd59151413d237     11
594c0b883b593b002812506e  00360b3f177375b01b795a4be7b4686c    425
                          62060850630c7afe54fd59151413d237      4
                          6b19235b9269df81b6da879771bf40bc      9
                          8258591d197a3936de0f7ee021ab9e0e     71
                          94959cf2d0b592d0fa1e5e9cf760a1c7     24
                          a09c8906073b4c0b75e3100b857b982a     71
                          e2333b2dc03032f12c8526e45243f0c1     43
594c151273dd9c002873cd98  62060850630c7afe54fd59151413d237     19
                          6b19235b9269df81b6da879771bf40bc     12
                          c033808b89b50e6f550caf266470f090      2
594c15a573dd9c002873cda1  00360b3f177375b01b795a4be7b4686c     23
                          62060850630c7afe54fd59151413d237      9
                          9286ce84f2401fbd6635f7d768c3cad1      4
                          a09c8906073b4c0b75e3100b857b982a      2
                          b89eb67419465a9e2c9da08dae6023e2      2
594c1abc73dd9c002873cdb8  95130c93e28b36bcb5ecd7e747b4d5c2     32
594c1e983b593b00281250ba  62060850630c7afe54fd59151413d237      2
                          85c7b78e76b5232cd38014ea4cdc8f56      8
594c1f5cd7e68f0028c9062c  0e9802516f8a79dd0d45211dd4ee74af      2
                          62060850630c7afe54fd59151413d237      2
594c20b773dd9c002873cdda  62060850630c7afe54fd59151413d237      2
594c28953b593b00281250e1  62060850630c7afe54fd59151413d237      7
594c2e992c137900353e0faa  d8e25a290ea51352bf9100a99c475f6d      2
594c3f0c73dd9c002873ce44  d8e25a290ea51352bf9100a99c475f6d      2
594c41482c137900353e0fea  d8e25a290ea51352bf9100a99c475f6d      3
594c41ab1e24bf00350a1f11  710dbda77cade1eced9c735c08e6e38d      4
Name: Wait time (min), dtype: int64

In [40]:
df[df['Request'] == '594c151273dd9c002873cd98']

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
17,2017-06-22 19:31:18,c033808b89b50e6f550caf266470f090,4.90,4.90,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,1,"editing, sourcing, writing",2,10,11,5,5,1,0,0,0
18,2017-06-22 19:31:15,c033808b89b50e6f550caf266470f090,4.90,4.90,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,1,"editing, sourcing, writing",2,10,13,5,5,2,0,1,0
34,2017-06-22 19:06:14,6b19235b9269df81b6da879771bf40bc,0.00,0.00,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,2,13,10,3,6,1,0,0,0
35,2017-06-22 19:06:08,6b19235b9269df81b6da879771bf40bc,0.00,0.00,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,3,13,12,3,6,2,0,1,0
126,2017-06-22 15:34:23,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,19,4,2,0,2,0,0,0
127,2017-06-22 15:34:21,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",6,19,5,2,1,2,0,0,0
128,2017-06-22 15:33:11,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",6,19,5,2,1,2,0,0,0
129,2017-06-22 15:32:36,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0
130,2017-06-22 15:32:36,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0
131,2017-06-22 15:32:01,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0
134,2017-06-22 15:27:20,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0
135,2017-06-22 15:26:45,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0
136,2017-06-22 15:26:45,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0
137,2017-06-22 15:26:10,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",6,17,4,2,1,1,0,0,0
138,2017-06-22 15:23:50,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",8,17,4,2,1,1,0,0,0
139,2017-06-22 15:23:15,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0
140,2017-06-22 15:23:15,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0
141,2017-06-22 15:22:39,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,4,2,1,1,0,0,0

In [41]:
df[df['Analyst'] == '62060850630c7afe54fd59151413d237']

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
96,2017-06-22 16:29:48,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c28953b593b00281250e1,2017-06-22 16:29:09,vetting,4,"vetting, planning, editing, sourcing, writing",4,15,6,6,0,0,0,0,0
97,2017-06-22 16:29:33,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c28953b593b00281250e1,2017-06-22 16:29:09,vetting,3,"vetting, planning, editing, sourcing, writing",5,15,7,6,1,0,0,0,0
100,2017-06-22 16:09:53,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,"vetting, planning, editing, sourcing, writing",0,17,4,4,0,0,0,0,0
101,2017-06-22 16:09:47,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,"vetting, planning, editing, sourcing, writing",1,17,5,4,0,0,0,1,0
102,2017-06-22 16:05:31,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c20b773dd9c002873cdda,2017-06-22 15:55:35,vetting,1,"vetting, planning, editing, sourcing, writing",0,18,3,2,0,0,0,1,0
103,2017-06-22 16:05:27,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c20b773dd9c002873cdda,2017-06-22 15:55:35,vetting,1,"vetting, planning, editing, sourcing, writing",1,18,4,2,1,0,0,1,0
104,2017-06-22 16:02:15,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",0,19,3,2,1,0,0,0,0
105,2017-06-22 16:02:11,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",1,19,4,2,2,0,0,0,0
111,2017-06-22 15:57:02,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c1f5cd7e68f0028c9062c,2017-06-22 15:49:48,vetting,1,"vetting, planning, editing, sourcing, writing",2,19,5,2,2,0,0,1,0
112,2017-06-22 15:56:33,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c1f5cd7e68f0028c9062c,2017-06-22 15:49:48,vetting,1,"vetting, planning, editing, sourcing, writing",3,19,6,2,3,0,0,1,0
124,2017-06-22 15:37:20,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,planning,1,"vetting, planning, editing, sourcing, writing",4,18,3,2,0,1,0,0,0
125,2017-06-22 15:37:16,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,planning,1,"vetting, planning, editing, sourcing, writing",5,18,4,2,0,2,0,0,0
126,2017-06-22 15:34:23,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,19,4,2,0,2,0,0,0
127,2017-06-22 15:34:21,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",6,19,5,2,1,2,0,0,0
128,2017-06-22 15:33:11,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",6,19,5,2,1,2,0,0,0
129,2017-06-22 15:32:36,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0
130,2017-06-22 15:32:36,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0
131,2017-06-22 15:32:01,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0
134,2017-06-22 15:27:20,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0
135,2017-06-22 15:26:45,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0
136,2017-06-22 15:26:45,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0
137,2017-06-22 15:26:10,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",6,17,4,2,1,1,0,0,0
138,2017-06-22 15:23:50,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",8,17,4,2,1,1,0,0,0
139,2017-06-22 15:23:15,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0
140,2017-06-22 15:23:15,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0
141,2017-06-22 15:22:39,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,4,2,1,1,0,0,0
142,2017-06-22 15:19:23,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0
143,2017-06-22 15:19:09,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,5,2,2,1,0,0,0
144,2017-06-22 15:19:09,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,5,2,2,1,0,0,0
145,2017-06-22 15:18:34,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,5,2,2,1,0,0,0
146,2017-06-22 15:16:09,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,vetting,2,"vetting, planning, editing, sourcing, writing",5,17,5,2,2,1,0,0,0
147,2017-06-22 15:15:38,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,vetting,1,"vetting, planning, editing, sourcing, writing",6,17,6,2,3,1,0,0,0
148,2017-06-22 15:15:38,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,vetting,1,"vetting, planning, editing, sourcing, writing",6,17,6,2,3,1,0,0,0
149,2017-06-22 15:15:03,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,vetting,1,"vetting, planning, editing, sourcing, writing",6,16,6,2,3,1,0,0,0
157,2017-06-22 15:12:45,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594bfcde70709600281a12b8,2017-06-22 13:22:38,vetting,2,"vetting, planning, editing, sourcing, writing",6,13,8,2,3,2,0,1,0
158,2017-06-22 15:12:42,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594bfcde70709600281a12b8,2017-06-22 13:22:38,vetting,2,"vetting, planning, editing, sourcing, writing",8,13,9,2,4,2,0,1,0
160,2017-06-22 15:12:42,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594bfcde70709600281a12b8,2017-06-22 13:22:38,vetting,2,"vetting, planning, editing, sourcing, writing",8,13,9,2,4,2,0,1,0
163,2017-06-22 15:12:07,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594bfcde70709600281a12b8,2017-06-22 13:22:38,vetting,1,"vetting, planning, editing, sourcing, writing",7,13,9,2,4,2,0,1,0
166,2017-06-22 15:06:54,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",6,15,7,1,3,3,0,0,0
167,2017-06-22 15:06:50,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",7,16,7,0,4,3,0,0,0
168,2017-06-22 15:06:50,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",7,16,7,0,4,3,0,0,0
169,2017-06-22 15:06:15,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",6,16,7,0,4,3,0,0,0
170,2017-06-22 15:05:05,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,2,"vetting, planning, editing, sourcing, writing",6,16,6,0,3,3,0,0,0
171,2017-06-22 15:04:30,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,2,"vetting, planning, editing, sourcing, writing",6,16,6,0,3,3,0,0,0
172,2017-06-22 15:04:30,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,2,"vetting, planning, editing, sourcing, writing",6,16,6,0,3,3,0,0,0
173,2017-06-22 15:03:55,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",5,16,6,0,3,3,0,0,0

In [42]:
export_csv = df.to_csv (r'clean_assignment_log.csv', index = None, header=True) #Don't forget to add '.csv' at the end of the path

In [43]:
clean_df = pd.read_csv('clean_assignment_log.csv')

In [44]:
clean_df.head()

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
0,2017-06-22 19:59:06,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Accepted Job,594bec5c95e2ce005840c23a,2017-06-22 12:12:12,review,1,review,0,13,14,4,6,2,0,1,1
1,2017-06-22 19:59:02,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Assigned Job,594bec5c95e2ce005840c23a,2017-06-22 12:12:12,review,1,review,1,13,15,5,6,2,0,1,1
2,2017-06-22 19:51:30,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Declined Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,9,"sourcing, writing",1,12,12,5,5,1,0,0,1
3,2017-06-22 19:51:01,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,Accepted Job,594c1f5cd7e68f0028c9062c,2017-06-22 15:49:48,sourcing,1,"sourcing, writing",1,11,12,5,5,1,0,0,1
4,2017-06-22 19:50:58,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,8,"sourcing, writing",2,11,14,5,5,2,0,1,1

In [45]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 789 entries, 0 to 788
Data columns (total 19 columns):
Event occurred at           789 non-null object
Analyst                     789 non-null object
Quality score (sourcing)    789 non-null float64
Quality score (writing)     789 non-null float64
Action                      789 non-null object
Request                     789 non-null object
Request created at          789 non-null object
Job                         789 non-null object
Wait time (min)             789 non-null int64
Waiting for                 789 non-null object
Analysts available          789 non-null int64
Analysts occupied           789 non-null int64
Total jobs available        789 non-null int64
Review jobs available       789 non-null int64
Vetting jobs available      789 non-null int64
Planning jobs available     789 non-null int64
Editing jobs available      789 non-null int64
Sourcing jobs available     789 non-null int64
Writing jobs available      789 non-null int64
dtypes: float64(2), int64(10), object(7)
memory usage: 117.2+ KB

In [46]:
# connect to database
conn = sqlite3.connect(':memory:')

# create cursor object
cur = conn.cursor()

In [49]:
df = pd.read_csv('clean_assignment_log.csv')
df.to_sql('assignment_log', con = conn, if_exists='append', index=False)

In [48]:
cur.execute('''SELECT * FROM assignment_log;''')       # sql query
assign_df = pd.DataFrame(cur.fetchall())               # create dataframe from sql query
assign_df.columns = [x[0] for x in cur.description]    # labels dataframe columns
assign_df                                              # view dataframe

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
0,2017-06-22 19:59:06,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Accepted Job,594bec5c95e2ce005840c23a,2017-06-22 12:12:12,review,1,review,0,13,14,4,6,2,0,1,1
1,2017-06-22 19:59:02,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Assigned Job,594bec5c95e2ce005840c23a,2017-06-22 12:12:12,review,1,review,1,13,15,5,6,2,0,1,1
2,2017-06-22 19:51:30,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Declined Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,9,"sourcing, writing",1,12,12,5,5,1,0,0,1
3,2017-06-22 19:51:01,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,Accepted Job,594c1f5cd7e68f0028c9062c,2017-06-22 15:49:48,sourcing,1,"sourcing, writing",1,11,12,5,5,1,0,0,1
4,2017-06-22 19:50:58,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,8,"sourcing, writing",2,11,14,5,5,2,0,1,1
5,2017-06-22 19:50:58,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,Assigned Job,594c1f5cd7e68f0028c9062c,2017-06-22 15:49:48,sourcing,1,"sourcing, writing",2,11,14,5,5,2,0,1,1
6,2017-06-22 19:50:58,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Declined Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,8,"sourcing, writing",2,11,14,5,5,2,0,1,1
7,2017-06-22 19:50:23,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,8,"sourcing, writing",1,11,14,5,5,2,0,1,1
8,2017-06-22 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0
9,2017-06-22 19:46:56,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",2,12,13,5,5,2,0,1,0
10,2017-06-22 19:44:03,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Accepted Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,review,1,"review, planning, editing, sourcing, writing",1,10,11,5,5,1,0,0,0
11,2017-06-22 19:44:01,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,review,1,"review, planning, editing, sourcing, writing",2,10,12,6,5,1,0,0,0
12,2017-06-22 19:40:41,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,Accepted Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,1,"sourcing, writing",2,9,12,6,5,1,0,0,0
13,2017-06-22 19:40:37,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,1,"sourcing, writing",3,9,13,6,5,1,0,0,1
14,2017-06-22 19:35:59,710dbda77cade1eced9c735c08e6e38d,5.00,5.00,Accepted Job,594c41ab1e24bf00350a1f11,2017-06-22 18:16:11,vetting,1,vetting,2,11,10,5,4,1,0,0,0
15,2017-06-22 19:35:56,710dbda77cade1eced9c735c08e6e38d,5.00,5.00,Assigned Job,594c41ab1e24bf00350a1f11,2017-06-22 18:16:11,vetting,1,vetting,3,11,11,5,5,1,0,0,0
16,2017-06-22 19:31:18,c033808b89b50e6f550caf266470f090,4.90,4.90,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,1,"editing, sourcing, writing",2,10,11,5,5,1,0,0,0
17,2017-06-22 19:31:15,c033808b89b50e6f550caf266470f090,4.90,4.90,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,1,"editing, sourcing, writing",2,10,13,5,5,2,0,1,0
18,2017-06-22 19:25:28,710dbda77cade1eced9c735c08e6e38d,5.00,5.00,Accepted Job,594c41ab1e24bf00350a1f11,2017-06-22 18:16:11,vetting,1,"vetting, sourcing",1,12,10,5,4,1,0,0,0
19,2017-06-22 19:25:25,710dbda77cade1eced9c735c08e6e38d,5.00,5.00,Assigned Job,594c41ab1e24bf00350a1f11,2017-06-22 18:16:11,vetting,1,"vetting, sourcing",2,12,11,5,5,1,0,0,0
20,2017-06-22 19:20:23,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,Accepted Job,594c41482c137900353e0fea,2017-06-22 18:14:32,vetting,1,vetting,1,14,8,3,4,1,0,0,0
21,2017-06-22 19:20:09,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,Assigned Job,594c41482c137900353e0fea,2017-06-22 18:14:32,vetting,1,vetting,2,14,9,3,5,1,0,0,0
22,2017-06-22 19:18:59,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,Assigned Job,594c41482c137900353e0fea,2017-06-22 18:14:32,vetting,1,vetting,2,14,9,3,5,1,0,0,0
23,2017-06-22 19:15:06,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,1,sourcing,1,15,9,3,5,1,0,0,0
24,2017-06-22 19:14:59,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,Accepted Job,594c3f0c73dd9c002873ce44,2017-06-22 18:05:00,vetting,1,vetting,2,14,11,3,5,2,0,1,0
25,2017-06-22 19:14:53,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,Assigned Job,594c3f0c73dd9c002873ce44,2017-06-22 18:05:00,vetting,1,vetting,3,14,12,3,6,2,0,1,0
26,2017-06-22 19:14:53,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,1,sourcing,3,14,12,3,6,2,0,1,0
27,2017-06-22 19:09:03,00360b3f177375b01b795a4be7b4686c,0.00,0.00,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,107,sourcing,2,14,11,2,6,2,0,1,0
28,2017-06-22 19:08:28,00360b3f177375b01b795a4be7b4686c,0.00,0.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,106,sourcing,2,14,11,2,6,2,0,1,0
29,2017-06-22 19:08:28,00360b3f177375b01b795a4be7b4686c,0.00,0.00,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,106,sourcing,2,14,11,2,6,2,0,1,0
30,2017-06-22 19:07:55,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Accepted Job,594bcdd780f13f00405cd4f0,2017-06-22 10:01:59,review,1,"review, planning, editing, sourcing, writing",2,13,11,2,6,2,0,1,0
31,2017-06-22 19:07:53,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594bcdd780f13f00405cd4f0,2017-06-22 10:01:59,review,1,"review, planning, editing, sourcing, writing",3,13,12,3,6,2,0,1,0
32,2017-06-22 19:07:53,00360b3f177375b01b795a4be7b4686c,0.00,0.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,106,sourcing,3,13,12,3,6,2,0,1,0
33,2017-06-22 19:06:14,6b19235b9269df81b6da879771bf40bc,0.00,0.00,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,2,13,10,3,6,1,0,0,0
34,2017-06-22 19:06:08,6b19235b9269df81b6da879771bf40bc,0.00,0.00,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,3,13,12,3,6,2,0,1,0
35,2017-06-22 19:00:59,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,Accepted Job,594c2e992c137900353e0faa,2017-06-22 16:54:49,vetting,1,vetting,3,13,9,3,6,0,0,0,0
36,2017-06-22 19:00:52,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,Assigned Job,594c2e992c137900353e0faa,2017-06-22 16:54:49,vetting,1,vetting,4,13,10,3,7,0,0,0,0
37,2017-06-22 19:00:19,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,1,planning,2,12,10,3,7,0,0,0,0
38,2017-06-22 19:00:17,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,1,planning,3,12,12,3,7,1,0,1,0
39,2017-06-22 18:59:12,6b19235b9269df81b6da879771bf40bc,0.00,0.00,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,5,sourcing,2,12,10,3,7,0,0,0,0
40,2017-06-22 18:59:07,6b19235b9269df81b6da879771bf40bc,0.00,0.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,4,sourcing,4,12,12,3,7,1,0,1,0
41,2017-06-22 18:59:07,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,18,"planning, editing, sourcing, writing",4,12,12,3,7,1,0,1,0
42,2017-06-22 18:58:32,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,17,"planning, editing, sourcing, writing",4,12,12,3,7,1,0,1,0
43,2017-06-22 18:58:32,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,17,"planning, editing, sourcing, writing",4,12,12,3,7,1,0,1,0
44,2017-06-22 18:57:57,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,17,"planning, editing, sourcing, writing",5,12,12,3,7,1,0,1,0
45,2017-06-22 18:57:57,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,7,planning,5,12,12,3,7,1,0,1,0
46,2017-06-22 18:57:21,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,6,planning,5,12,12,3,7,1,0,1,0
47,2017-06-22 18:57:21,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,6,planning,5,12,12,3,7,1,0,1,0
48,2017-06-22 18:56:46,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,planning,5,planning,4,12,12,3,7,1,0,1,0
49,2017-06-22 18:37:07,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,source review,1,"review, planning, editing, sourcing, writing",2,14,8,1,7,0,0,0,0
50,2017-06-22 18:36:56,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,source review,1,"review, planning, editing, sourcing, writing",3,14,9,2,7,0,0,0,0
51,2017-06-22 18:29:23,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Accepted Job,594bec5c95e2ce005840c242,2017-06-22 12:12:12,review,1,"review, planning, editing, sourcing, writing",3,14,9,2,7,0,0,0,0
52,2017-06-22 18:29:21,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594bec5c95e2ce005840c242,2017-06-22 12:12:12,review,1,"review, planning, editing, sourcing, writing",4,14,10,3,7,0,0,0,0
53,2017-06-22 18:26:42,e2333b2dc03032f12c8526e45243f0c1,0.00,0.00,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,22,sourcing,2,14,9,2,7,0,0,0,0
54,2017-06-22 18:26:26,e2333b2dc03032f12c8526e45243f0c1,0.00,0.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,21,sourcing,4,14,11,2,7,1,0,1,0
55,2017-06-22 18:26:26,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,18,sourcing,4,14,11,2,7,1,0,1,0
56,2017-06-22 18:25:51,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,17,sourcing,4,15,11,2,7,1,0,1,0
57,2017-06-22 18:25:51,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,17,sourcing,4,15,11,2,7,1,0,1,0
58,2017-06-22 18:25:16,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,17,sourcing,4,15,11,2,7,1,0,1,0
59,2017-06-22 17:47:20,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,Accepted Job,594bde9ffd2cf400280aa920,2017-06-22 11:13:35,review,1,review,6,17,4,1,3,0,0,0,0
60,2017-06-22 17:47:18,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,Assigned Job,594bde9ffd2cf400280aa920,2017-06-22 11:13:35,review,1,review,6,17,5,2,3,0,0,0,0
61,2017-06-22 17:26:53,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,Accepted Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,review,1,review,2,18,4,1,3,0,0,0,0
62,2017-06-22 17:26:52,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,Assigned Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,review,1,review,3,18,5,2,3,0,0,0,0
63,2017-06-22 17:19:35,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Accepted Job,594aead5ef88150028311172,2017-06-21 17:53:25,review,1,"review, planning, editing, sourcing, writing",2,17,5,2,3,0,0,0,0
64,2017-06-22 17:19:26,dddcdea13df8232803957a5d9c847aae,4.31,4.31,Accepted Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,14,"sourcing, writing",3,16,6,3,3,0,0,0,0
65,2017-06-22 17:19:16,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594aead5ef88150028311172,2017-06-21 17:53:25,review,1,"review, planning, editing, sourcing, writing",4,16,7,3,3,0,0,0,1
66,2017-06-22 17:19:16,dddcdea13df8232803957a5d9c847aae,4.31,4.31,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,14,"sourcing, writing",4,16,7,3,3,0,0,0,1
67,2017-06-22 17:19:16,0c2680433387fb4cf51a3546296f8422,4.52,4.52,Declined Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,15,"sourcing, writing",4,16,7,3,3,0,0,0,1
68,2017-06-22 17:18:41,0c2680433387fb4cf51a3546296f8422,4.52,4.52,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,14,"sourcing, writing",4,16,7,3,3,0,0,0,1
69,2017-06-22 17:18:41,0c2680433387fb4cf51a3546296f8422,4.52,4.52,Declined Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,14,"sourcing, writing",4,16,7,3,3,0,0,0,1
70,2017-06-22 17:18:06,0c2680433387fb4cf51a3546296f8422,4.52,4.52,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,writing,13,"sourcing, writing",3,16,7,3,3,0,0,0,1
71,2017-06-22 17:12:54,c033808b89b50e6f550caf266470f090,4.90,4.90,Accepted Job,594bec5e95e2ce005840c252,2017-06-22 12:12:14,writing,4,"editing, sourcing, writing",3,16,6,3,3,0,0,0,0
72,2017-06-22 17:12:52,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Accepted Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,source review,1,"review, planning, editing, sourcing, writing",4,16,7,3,3,0,0,0,1
73,2017-06-22 17:12:50,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,source review,1,"review, planning, editing, sourcing, writing",5,16,8,4,3,0,0,0,1
74,2017-06-22 17:12:50,c033808b89b50e6f550caf266470f090,4.90,4.90,Assigned Job,594bec5e95e2ce005840c252,2017-06-22 12:12:14,writing,4,"editing, sourcing, writing",5,16,8,4,3,0,0,0,1
75,2017-06-22 17:04:42,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Accepted Job,594bec5e95e2ce005840c252,2017-06-22 12:12:14,source review,1,"review, planning, editing, sourcing, writing",2,15,7,4,3,0,0,0,0
76,2017-06-22 17:04:40,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594bec5e95e2ce005840c252,2017-06-22 12:12:14,source review,1,"review, planning, editing, sourcing, writing",3,15,8,5,3,0,0,0,0
77,2017-06-22 17:04:12,3a29165b73c047e745934c2cbbfaac1b,4.67,4.67,Accepted Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,writing,8,writing,2,14,8,5,3,0,0,0,0
78,2017-06-22 17:04:05,3a29165b73c047e745934c2cbbfaac1b,4.67,4.67,Assigned Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,writing,8,writing,3,14,9,5,3,0,0,0,1
79,2017-06-22 17:03:03,b89eb67419465a9e2c9da08dae6023e2,0.00,0.00,Accepted Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,35,sourcing,2,14,8,5,3,0,0,0,0
80,2017-06-22 17:02:54,b89eb67419465a9e2c9da08dae6023e2,0.00,0.00,Assigned Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,35,sourcing,4,14,9,5,3,0,0,1,0
81,2017-06-22 17:02:54,dddcdea13df8232803957a5d9c847aae,4.31,4.31,Declined Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,3,"sourcing, writing",4,14,9,5,3,0,0,1,0
82,2017-06-22 17:02:19,dddcdea13df8232803957a5d9c847aae,4.31,4.31,Assigned Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,2,"sourcing, writing",4,14,9,5,3,0,0,1,0
83,2017-06-22 17:02:19,dddcdea13df8232803957a5d9c847aae,4.31,4.31,Declined Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,2,"sourcing, writing",4,14,9,5,3,0,0,1,0
84,2017-06-22 17:01:44,dddcdea13df8232803957a5d9c847aae,4.31,4.31,Assigned Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,2,"sourcing, writing",5,14,9,5,3,0,0,1,0
85,2017-06-22 17:01:44,0c2680433387fb4cf51a3546296f8422,4.52,4.52,Declined Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,24,sourcing,5,14,9,5,3,0,0,1,0
86,2017-06-22 17:01:09,0c2680433387fb4cf51a3546296f8422,4.52,4.52,Assigned Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,23,sourcing,5,14,9,5,3,0,0,1,0
87,2017-06-22 17:01:09,0c2680433387fb4cf51a3546296f8422,4.52,4.52,Declined Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,23,sourcing,5,14,9,5,3,0,0,1,0
88,2017-06-22 17:00:34,0c2680433387fb4cf51a3546296f8422,4.52,4.52,Assigned Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,23,sourcing,4,14,9,5,3,0,0,1,0
89,2017-06-22 16:53:00,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Accepted Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,source review,1,"review, planning, editing, sourcing, writing",3,14,5,5,0,0,0,0,0
90,2017-06-22 16:52:58,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,Assigned Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,source review,1,"review, planning, editing, sourcing, writing",4,14,6,6,0,0,0,0,0
91,2017-06-22 16:46:32,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,Assigned Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,source review,1,review,4,14,6,6,0,0,0,0,0
92,2017-06-22 16:37:46,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,Accepted Job,594baca737b4b7004b683616,2017-06-22 07:40:23,review,1,review,4,14,6,6,0,0,0,0,0
93,2017-06-22 16:37:43,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,Assigned Job,594baca737b4b7004b683616,2017-06-22 07:40:23,review,1,review,5,14,7,7,0,0,0,0,0
94,2017-06-22 16:29:48,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c28953b593b00281250e1,2017-06-22 16:29:09,vetting,4,"vetting, planning, editing, sourcing, writing",4,15,6,6,0,0,0,0,0
95,2017-06-22 16:29:33,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c28953b593b00281250e1,2017-06-22 16:29:09,vetting,3,"vetting, planning, editing, sourcing, writing",5,15,7,6,1,0,0,0,0
96,2017-06-22 16:17:23,9286ce84f2401fbd6635f7d768c3cad1,0.00,0.00,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,2,sourcing,2,15,5,5,0,0,0,0,0
97,2017-06-22 16:17:17,9286ce84f2401fbd6635f7d768c3cad1,0.00,0.00,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,2,sourcing,3,15,6,5,0,0,0,1,0
98,2017-06-22 16:09:53,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,"vetting, planning, editing, sourcing, writing",0,17,4,4,0,0,0,0,0
99,2017-06-22 16:09:47,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,"vetting, planning, editing, sourcing, writing",1,17,5,4,0,0,0,1,0
100,2017-06-22 16:05:31,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c20b773dd9c002873cdda,2017-06-22 15:55:35,vetting,1,"vetting, planning, editing, sourcing, writing",0,18,3,2,0,0,0,1,0
101,2017-06-22 16:05:27,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c20b773dd9c002873cdda,2017-06-22 15:55:35,vetting,1,"vetting, planning, editing, sourcing, writing",1,18,4,2,1,0,0,1,0
102,2017-06-22 16:02:15,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",0,19,3,2,1,0,0,0,0
103,2017-06-22 16:02:11,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",1,19,4,2,2,0,0,0,0
104,2017-06-22 16:01:43,b89eb67419465a9e2c9da08dae6023e2,0.00,0.00,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,sourcing,0,18,4,2,2,0,0,0,0
105,2017-06-22 16:01:36,b89eb67419465a9e2c9da08dae6023e2,0.00,0.00,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,sourcing,1,18,5,2,2,0,0,1,0
106,2017-06-22 15:57:43,00360b3f177375b01b795a4be7b4686c,0.00,0.00,Declined Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,6,sourcing,2,19,5,2,2,0,0,1,0
107,2017-06-22 15:57:08,00360b3f177375b01b795a4be7b4686c,0.00,0.00,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,6,sourcing,2,20,5,2,2,0,0,1,0
108,2017-06-22 15:57:08,00360b3f177375b01b795a4be7b4686c,0.00,0.00,Declined Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,6,sourcing,2,20,5,2,2,0,0,1,0
109,2017-06-22 15:57:02,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c1f5cd7e68f0028c9062c,2017-06-22 15:49:48,vetting,1,"vetting, planning, editing, sourcing, writing",2,19,5,2,2,0,0,1,0
110,2017-06-22 15:56:33,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c1f5cd7e68f0028c9062c,2017-06-22 15:49:48,vetting,1,"vetting, planning, editing, sourcing, writing",3,19,6,2,3,0,0,1,0

In [55]:
cur.execute('''SELECT "Event occurred at" FROM assignment_log;''')       # sql query
time_df = pd.DataFrame(cur.fetchall())               # create dataframe from sql query
time_df.columns = [x[0] for x in cur.description]    # labels dataframe columns
time_df                                              # view dataframe

        Event occurred at
0     2017-06-22 19:59:06
1     2017-06-22 19:59:02
2     2017-06-22 19:51:30
3     2017-06-22 19:51:01
4     2017-06-22 19:50:58
...                   ...
1573  2017-06-21 20:21:32
1574  2017-06-21 20:21:03
1575  2017-06-21 20:20:57
1576  2017-06-21 20:15:45
1577  2017-06-21 20:15:42

[1578 rows x 1 columns]