In [1]:
# import libraries

import pandas as pd
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 30)

import sqlite3

In [2]:
# read in file and create dataframe
df = pd.read_csv('Assignment Log.csv')

### Part 1: Analysis 
#### Analyze and extract any interesting insights you can derive from the data set attached (each row represents the assignment of a job in our research queue, including some data about the analyst who received the assignment and the current state of the research queue). What can you infer? What do you think this means for us from a business perspective?

### Exploratory Data Analysis

In [3]:
df.head(10)

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
0,06/22/2017 19:59:06,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Accepted Job,594bec5c95e2ce005840c23a,06/22/2017 12:12:12,review,1,review,0,13,14,4,6,2,0,1,1
1,06/22/2017 19:59:02,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Assigned Job,594bec5c95e2ce005840c23a,06/22/2017 12:12:12,review,1,review,1,13,15,5,6,2,0,1,1
2,06/22/2017 19:51:30,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Declined Job,594bec83fd2cf400280aa965,06/22/2017 12:12:51,writing,9,"sourcing, writing",1,12,12,5,5,1,0,0,1
3,06/22/2017 19:51:01,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,Accepted Job,594c1f5cd7e68f0028c9062c,06/22/2017 15:49:48,sourcing,1,"sourcing, writing",1,11,12,5,5,1,0,0,1
4,06/22/2017 19:50:58,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594bec83fd2cf400280aa965,06/22/2017 12:12:51,writing,8,"sourcing, writing",2,11,14,5,5,2,0,1,1
5,06/22/2017 19:50:58,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,Assigned Job,594c1f5cd7e68f0028c9062c,06/22/2017 15:49:48,sourcing,1,"sourcing, writing",2,11,14,5,5,2,0,1,1
6,06/22/2017 19:50:58,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Declined Job,594bec83fd2cf400280aa965,06/22/2017 12:12:51,writing,8,"sourcing, writing",2,11,14,5,5,2,0,1,1
7,06/22/2017 19:50:23,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594bec83fd2cf400280aa965,06/22/2017 12:12:51,writing,8,"sourcing, writing",1,11,14,5,5,2,0,1,1
8,06/22/2017 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,06/22/2017 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0
9,06/22/2017 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,06/22/2017 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0

In [4]:
df.shape

(791, 19)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 791 entries, 0 to 790
Data columns (total 19 columns):
Event occurred at           791 non-null object
Analyst                     791 non-null object
Quality score (sourcing)    791 non-null float64
Quality score (writing)     791 non-null float64
Action                      791 non-null object
Request                     791 non-null object
Request created at          791 non-null object
Job                         791 non-null object
Wait time (min)             791 non-null int64
Waiting for                 785 non-null object
Analysts available          791 non-null int64
Analysts occupied           791 non-null int64
Total jobs available        791 non-null int64
Review jobs available       791 non-null int64
Vetting jobs available      791 non-null int64
Planning jobs available     791 non-null int64
Editing jobs available      791 non-null int64
Sourcing jobs available     791 non-null int64
Writing jobs available      791 non-null int64
dtypes: float64(2), int64(10), object(7)
memory usage: 117.5+ KB

In [6]:
# convert Event occurred at and Request created at to datetime
df['Event occurred at'] = pd.to_datetime(df['Event occurred at'])
df['Request created at'] = pd.to_datetime(df['Request created at'])

In [7]:
# Min and Max times for creating requests

print('Min Date: ' + str(min(df['Request created at'])))
print('Max Date: ' + str(max(df['Request created at'])))

Min Date: 2017-06-19 13:43:51
Max Date: 2017-06-22 18:16:11

In [8]:
# Min and Max times for events

print('Min Date: ' + str(min(df['Event occurred at'])))
print('Max Date: ' + str(max(df['Event occurred at'])))

Min Date: 2017-06-21 20:15:42
Max Date: 2017-06-22 19:59:06

#### Handling Nulls

In [9]:
# check for any null values
df.isnull().sum()

Event occurred at           0
Analyst                     0
Quality score (sourcing)    0
Quality score (writing)     0
Action                      0
Request                     0
Request created at          0
Job                         0
Wait time (min)             0
Waiting for                 6
Analysts available          0
Analysts occupied           0
Total jobs available        0
Review jobs available       0
Vetting jobs available      0
Planning jobs available     0
Editing jobs available      0
Sourcing jobs available     0
Writing jobs available      0
dtype: int64

In [10]:
# find nulls
def find_nulls(df):
    null_columns=df.columns[df.isnull().any()]
    return df[df['Waiting for'].isnull()][null_columns]

In [11]:
find_nulls(df)

    Waiting for
195         NaN
340         NaN
392         NaN
454         NaN
595         NaN
723         NaN

#### There are just 6 null values in the dataset and all are in the 'Waiting for' column. I am going to replace the null value with the job value.

In [12]:
len(df[df['Job'] == df['Waiting for']])

392

In [13]:
len(df[df['Job'] != df['Waiting for']])

399

In [14]:
df.iloc[194:196]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
194,2017-06-22 14:31:08,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Assigned Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,planning,1,planning,5,16,8,0,3,5,0,0,0
195,2017-06-22 14:30:59,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,26,NaN,5,15,8,0,3,5,0,0,0

In [15]:
df.loc[[195], 'Waiting for'] = 'sourcing'

In [16]:
df.loc[339:341]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
339,2017-06-22 08:03:23,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,4,10,4,0,0,1,0,1,2
340,2017-06-22 08:01:25,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,NaN,3,10,3,0,0,1,0,0,2
341,2017-06-22 08:01:22,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,3,10,3,0,0,1,0,0,2

In [17]:
df.loc[[340], 'Waiting for'] = 'sourcing'

In [18]:
df.loc[391:393]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
391,2017-06-22 06:17:54,7e22ad15724c44543d1d4bcafd10c812,5.0,5.0,Assigned Job,594ae6fb4f06e20035d92345,2017-06-21 17:36:59,review,1,review,1,10,6,3,1,0,0,0,2
392,2017-06-22 06:13:40,766d3435eda76c4de9f034b8f97a0602,3.5,3.5,Accepted Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,NaN,0,9,6,3,1,0,0,0,2
393,2017-06-22 06:13:34,766d3435eda76c4de9f034b8f97a0602,3.5,3.5,Assigned Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,"sourcing, writing",1,9,7,3,1,0,0,0,3

In [19]:
df.loc[[392], 'Waiting for'] = 'sourcing, writing'

In [20]:
df.loc[453:455]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
453,2017-06-22 04:45:27,7e22ad15724c44543d1d4bcafd10c812,5.0,5.0,Assigned Job,594b00e23f82d10028f03be2,2017-06-21 19:27:30,review,1,review,1,14,7,3,1,0,0,0,3
454,2017-06-22 04:40:07,7e22ad15724c44543d1d4bcafd10c812,5.0,5.0,Accepted Job,594af3c6f3b9f600287eabe0,2017-06-21 18:31:34,review,1,NaN,0,15,7,3,1,0,0,0,3
455,2017-06-22 04:40:03,7e22ad15724c44543d1d4bcafd10c812,5.0,5.0,Assigned Job,594af3c6f3b9f600287eabe0,2017-06-21 18:31:34,review,1,review,1,15,8,4,1,0,0,0,3

In [21]:
df.loc[[454], 'Waiting for'] = 'review'

In [22]:
df.loc[594:596]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
594,2017-06-21 23:26:17,9fcbc63ff4c8bea5cea4efad782c87cf,5.0,5.0,Assigned Job,594b20ed3f82d10028f03c6c,2017-06-21 21:44:13,sourcing,1,sourcing,1,24,7,1,3,1,0,1,1
595,2017-06-21 23:23:02,f7f7591403c6c431053920223069550a,5.0,5.0,Accepted Job,594b20ee3f82d10028f03c74,2017-06-21 21:44:14,planning,1,NaN,0,23,7,1,3,1,0,1,1
596,2017-06-21 23:22:37,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Accepted Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,1,22,8,1,3,2,0,1,1

In [23]:
df.loc[[595], 'Waiting for'] = 'planning'

In [24]:
df.loc[722:724]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
722,2017-06-21 21:25:06,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,Assigned Job,5949462dd9ae5200633f9640,2017-06-20 11:58:37,review,1,review,2,21,8,6,1,0,0,0,1
723,2017-06-21 21:24:44,206de922289a1f9f5ee250fc71308628,3.17,3.17,Accepted Job,594ae6fb4f06e20035d92345,2017-06-21 17:36:59,writing,1,NaN,1,20,8,6,1,0,0,0,1
724,2017-06-21 21:24:38,206de922289a1f9f5ee250fc71308628,3.17,3.17,Accepted Job,594ae6fb4f06e20035d92345,2017-06-21 17:36:59,writing,1,writing,1,20,8,6,1,0,0,0,1

In [25]:
df.loc[[723], 'Waiting for'] = 'writing'

In [26]:
# check for any null values
df.isnull().sum()

Event occurred at           0
Analyst                     0
Quality score (sourcing)    0
Quality score (writing)     0
Action                      0
Request                     0
Request created at          0
Job                         0
Wait time (min)             0
Waiting for                 0
Analysts available          0
Analysts occupied           0
Total jobs available        0
Review jobs available       0
Vetting jobs available      0
Planning jobs available     0
Editing jobs available      0
Sourcing jobs available     0
Writing jobs available      0
dtype: int64

#### Handling Duplicates

In [27]:
# find duplicates
# select duplicate rows except first occurrence based on all columns
def duplicates(df):
    duplicate_rows_df = df[df.duplicated()]
    return duplicate_rows_df

In [28]:
duplicates(df)

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available
9,2017-06-22 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0
55,2017-06-22 18:26:42,e2333b2dc03032f12c8526e45243f0c1,0.00,0.00,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,22,sourcing,2,14,9,2,7,0,0,0,0

In [29]:
df.drop_duplicates(inplace = True)

In [30]:
# confirm duplicates removed
duplicates(df)

Empty DataFrame
Columns: [Event occurred at, Analyst, Quality score (sourcing), Quality score (writing), Action, Request, Request created at, Job, Wait time (min), Waiting for, Analysts available, Analysts occupied, Total jobs available, Review jobs available, Vetting jobs available, Planning jobs available, Editing jobs available, Sourcing jobs available, Writing jobs available]
Index: []

In [31]:
# inspecting the unique values found in columns
df.nunique()

Event occurred at           669
Analyst                      71
Quality score (sourcing)     37
Quality score (writing)      37
Action                        3
Request                      74
Request created at           72
Job                           7
Wait time (min)              39
Waiting for                  27
Analysts available            9
Analysts occupied            19
Total jobs available         17
Review jobs available        12
Vetting jobs available        8
Planning jobs available      13
Editing jobs available        3
Sourcing jobs available       5
Writing jobs available        7
dtype: int64

In [32]:
# create function to find value counts for some columns
def values(column):
    print(df[column].value_counts())

In [33]:
# run values function
print(values('Action'))
print(values('Job'))

Assigned Job    393
Accepted Job    301
Declined Job     95
Name: Action, dtype: int64
None
sourcing         209
writing          160
review           143
planning          94
vetting           94
source review     58
editing           31
Name: Job, dtype: int64
None

In [34]:
# create function to find the average wait time for each request based
# on the job type (sourcing, writing, review, planning, vetting, source
# review and editing)

def averages(df, value):    
    return 'Average ' + value.title() + ' Wait Time in Minutes: '+ \
    str(round(df[df['Job'] == value]['Wait time (min)'].mean(), 2))

In [35]:
# run averages function 
print(averages(df, 'sourcing')) 
print(averages(df, 'writing')) 
print(averages(df, 'review')) 
print(averages(df, 'planning')) 
print(averages(df, 'vetting')) 
print(averages(df, 'source review')) 
print(averages(df, 'editing'))

Average Sourcing Wait Time in Minutes: 10.46
Average Writing Wait Time in Minutes: 3.74
Average Review Wait Time in Minutes: 3.36
Average Planning Wait Time in Minutes: 2.18
Average Vetting Wait Time in Minutes: 1.2
Average Source Review Wait Time in Minutes: 2.48
Average Editing Wait Time in Minutes: 9.03

In [36]:
df.groupby(['Analyst', 'Action'])['Action'].count()

Analyst                           Action
00360b3f177375b01b795a4be7b4686c  Assigned Job     4
                                  Declined Job     4
008fa95f5c94985e2d44047aeac31655  Accepted Job     4
                                  Assigned Job     3
052066814364850e1a17a90d576dd904  Accepted Job     2
                                  Assigned Job     1
0c2680433387fb4cf51a3546296f8422  Accepted Job     5
                                  Assigned Job     9
                                  Declined Job     4
0e9802516f8a79dd0d45211dd4ee74af  Accepted Job    11
                                  Assigned Job    12
                                  Declined Job     1
1f8d8b08a994331e419d24293ce9e7b0  Assigned Job     2
                                  Declined Job     2
206de922289a1f9f5ee250fc71308628  Accepted Job     4
                                  Assigned Job     3
2d0f64a208f69a70ec415cfccb59cc24  Accepted Job     2
                                  Assigned Job     2
2df8ce7d317c7d89dfa95be7695d2de0  Accepted Job     4
                                  Assigned Job     4
30ea4ac9222bfa53b3849df49d6f26f0  Accepted Job     1
                                  Assigned Job     1
32553d485988e2ddcf0f701c60754f2d  Accepted Job     2
                                  Assigned Job     2
36ee9fc3bade4a4f71c2a6e5c2bd8862  Accepted Job     3
                                  Assigned Job     1
39012c98c8fb80752d2bbcc3dc285230  Accepted Job     4
                                  Assigned Job     4
39b71201151caf98fd10afce50cfc83e  Accepted Job     6
                                  Assigned Job     6
3a29165b73c047e745934c2cbbfaac1b  Accepted Job     2
                                  Assigned Job     2
3a8a0b0323b02a707535fe7d65821de3  Accepted Job     1
                                  Assigned Job     1
482e9b14d8d59b748320f89074362746  Accepted Job     4
                                  Assigned Job     4
4bb6e496f0c92286dee7eed7038ddd9d  Accepted Job     4
                                  Assigned Job     4
5078cc506436a8668c0b6de594842fcf  Assigned Job     1
5233d783ae5bf0483cf49549cbc594f8  Accepted Job     1
                                  Assigned Job     1
5238b0785b5576f5ffe665136df9244f  Assigned Job     2
                                  Declined Job     2
57ef46a92ecee8e187f4d450e92651ea  Accepted Job     1
                                  Assigned Job     1
608b40f66ef114c6d9f5c95021290f69  Assigned Job     2
                                  Declined Job     2
62060850630c7afe54fd59151413d237  Accepted Job    11
                                  Assigned Job    23
                                  Declined Job    12
632a6492e9ff20cc4a442245836424e5  Accepted Job     2
                                  Assigned Job     3
                                  Declined Job     1
642782c690c8d963c487300a4751e220  Accepted Job    17
                                  Assigned Job    21
                                  Declined Job     4
6b19235b9269df81b6da879771bf40bc  Accepted Job     2
                                  Assigned Job     4
                                  Declined Job     2
6c6bd5e891c4015e534773dfb19f29b0  Accepted Job    10
                                  Assigned Job     9
710dbda77cade1eced9c735c08e6e38d  Accepted Job     7
                                  Assigned Job     7
732e4a29b2e318bce3c1e923276ddf51  Accepted Job    16
                                  Assigned Job    24
                                  Declined Job     2
766d3435eda76c4de9f034b8f97a0602  Accepted Job     1
                                  Assigned Job     2
77b8ab28b9e95edb3a69ca7a6d352ec8  Accepted Job     2
                                  Assigned Job     2
795930bc4ed320777ad76b46da2ed66d  Accepted Job     6
                                  Assigned Job     6
                                  Declined Job     2
7e22ad15724c44543d1d4bcafd10c812  Accepted Job    12
                                  Assigned Job    14
                                  Declined Job     2
8258591d197a3936de0f7ee021ab9e0e  Accepted Job     4
                                  Assigned Job     9
                                  Declined Job     4
83f00c2268afaf459715f4c52e16dd23  Accepted Job     1
                                  Assigned Job     1
85c7b78e76b5232cd38014ea4cdc8f56  Accepted Job     8
                                  Assigned Job    16
                                  Declined Job    10
9286ce84f2401fbd6635f7d768c3cad1  Accepted Job     2
                                  Assigned Job     2
94959cf2d0b592d0fa1e5e9cf760a1c7  Accepted Job    11
                                  Assigned Job    13
                                  Declined Job     2
95130c93e28b36bcb5ecd7e747b4d5c2  Assigned Job     1
                                  Declined Job     1
98de7e62209a07eee6ec8dc984911042  Accepted Job     4
                                  Assigned Job     5
                                  Declined Job     1
9fa24ddce8fd9d1526d9d7451304fc74  Accepted Job     7
                                  Assigned Job     8
                                  Declined Job     2
9fcbc63ff4c8bea5cea4efad782c87cf  Accepted Job    18
                                  Assigned Job    20
                                  Declined Job     2
a09c8906073b4c0b75e3100b857b982a  Accepted Job    28
                                  Assigned Job    36
                                  Declined Job     8
a29fe6d26c1a49ff4a3c876eaee0a1af  Accepted Job     3
                                  Assigned Job     1
b599bfb42906772db81ac90137fc1916  Accepted Job     2
                                  Assigned Job     2
b692db6843c42f5ce686fcdfda4e0b62  Accepted Job     1
                                  Assigned Job     1
b89eb67419465a9e2c9da08dae6023e2  Accepted Job     2
                                  Assigned Job     2
bcd8d747b5af397febc04228293f747f  Accepted Job     1
                                  Assigned Job     1
c033808b89b50e6f550caf266470f090  Accepted Job     4
                                  Assigned Job     4
c2d7982e24aadeea8921108d0eb756d8  Assigned Job     4
                                  Declined Job     4
c2dcc0b178176d7e6b185df9bd1cb4f2  Accepted Job     7
                                  Assigned Job     8
                                  Declined Job     1
c9401f82fdedf3cd080a03bafe3447c7  Accepted Job     1
                                  Assigned Job     9
                                  Declined Job     7
caf77e4ba6154e998b352cc92c685f80  Accepted Job     5
                                  Assigned Job     8
                                  Declined Job     2
d5aa695af013ee5baaeeccfb7ca50c80  Accepted Job     7
                                  Assigned Job     3
d6eaa4eeb52b4d62ec78299454763870  Accepted Job     6
                                  Assigned Job     8
                                  Declined Job     1
d74c4a7423dd3ee0a78de5481c364823  Accepted Job     2
                                  Assigned Job     2
d8e25a290ea51352bf9100a99c475f6d  Accepted Job     8
                                  Assigned Job    10
                                  Declined Job     1
d9837e646a15a4fdd823531178b2d62e  Accepted Job     1
                                  Assigned Job     4
                                  Declined Job     3
dddcdea13df8232803957a5d9c847aae  Accepted Job     2
                                  Assigned Job     7
                                  Declined Job     4
de71db592b02c988670ca3d301a02568  Accepted Job     2
                                  Assigned Job     2
dee1febfdeb9c90a41759cb330c72fd4  Accepted Job     3
                                  Assigned Job     3
e2333b2dc03032f12c8526e45243f0c1  Accepted Job     1
                                  Assigned Job     1
e817dd4305458b293cbeb3015da99565  Accepted Job     1
                                  Assigned Job     1
e8a2b0b2e2234a89dc52dd8a3e0f79e6  Accepted Job     2
                                  Assigned Job     2
e9468b4c33f88d6937c4ad2bea8bbc2f  Accepted Job     1
                                  Assigned Job     1
ea452a7456e38887ca8b98f4e131d224  Accepted Job     1
                                  Assigned Job     1
ea5354c723ba83f2c412c238b133e84a  Accepted Job     1
                                  Assigned Job     1
ef7e6e9fd91d89f2e31b26b9feaec787  Accepted Job     1
                                  Assigned Job     1
f3b93c5ae97215ae15fa63b5f0fc30e1  Accepted Job     1
                                  Assigned Job     1
f7f7591403c6c431053920223069550a  Accepted Job     5
                                  Assigned Job     7
                                  Declined Job     2
Name: Action, dtype: int64

In [37]:
# dummy Action category

action_dummies = pd.get_dummies(df['Action'])
action_dummies.head()

df = pd.concat([df, action_dummies],axis=1)
#df.drop('Action',axis=1, inplace=True)

In [38]:
df[df['Request'] == '594c1e983b593b00281250ba']

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available,Accepted Job,Assigned Job,Declined Job
8,2017-06-22 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0,1,0,0
10,2017-06-22 19:46:56,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",2,12,13,5,5,2,0,1,0,0,1,0
104,2017-06-22 16:02:15,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",0,19,3,2,1,0,0,0,0,1,0,0
105,2017-06-22 16:02:11,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",1,19,4,2,2,0,0,0,0,0,1,0

In [39]:
df[df['Request'] == '594c1e983b593b00281250ba']

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available,Accepted Job,Assigned Job,Declined Job
8,2017-06-22 19:47:03,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",1,11,11,5,5,1,0,0,0,1,0,0
10,2017-06-22 19:46:56,85c7b78e76b5232cd38014ea4cdc8f56,4.35,4.35,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,sourcing,4,"sourcing, writing",2,12,13,5,5,2,0,1,0,0,1,0
104,2017-06-22 16:02:15,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",0,19,3,2,1,0,0,0,0,1,0,0
105,2017-06-22 16:02:11,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",1,19,4,2,2,0,0,0,0,0,1,0

In [40]:
df[df['Request'] == '594bec7ffd2cf400280aa953']

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available,Accepted Job,Assigned Job,Declined Job
188,2017-06-22 14:33:36,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,1,"editing, sourcing, writing",5,14,7,0,3,4,0,0,0,1,0,0
189,2017-06-22 14:33:35,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,1,"editing, sourcing, writing",5,14,7,0,3,4,0,0,0,1,0,0
190,2017-06-22 14:33:29,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,Assigned Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,1,"editing, sourcing, writing",6,14,8,0,3,4,0,1,0,0,1,0
195,2017-06-22 14:30:59,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,26,sourcing,5,15,8,0,3,5,0,0,0,1,0,0
196,2017-06-22 14:30:54,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,26,sourcing,5,15,8,0,3,5,0,0,0,1,0,0
197,2017-06-22 14:30:33,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,Assigned Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,sourcing,26,sourcing,5,15,9,0,3,5,0,1,0,0,1,0
214,2017-06-22 13:32:46,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Accepted Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,planning,1,planning,4,12,9,0,1,8,0,0,0,1,0,0
215,2017-06-22 13:32:40,94959cf2d0b592d0fa1e5e9cf760a1c7,5.00,5.00,Assigned Job,594bec7ffd2cf400280aa953,2017-06-22 12:12:47,planning,1,planning,5,12,10,0,1,9,0,0,0,0,1,0

In [41]:
# Min and Max times for creating requests

print('Min quality score (sourcing) : ' + str(min(df['Quality score (sourcing)'])))
print('Max quality score (sourcing) : ' + str(max(df['Quality score (sourcing)'])))

Min quality score (sourcing) : 0.0
Max quality score (sourcing) : 5.0

In [42]:
df[df['Quality score (sourcing)'] == 0]

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available,Accepted Job,Assigned Job,Declined Job
24,2017-06-22 19:15:06,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,1,sourcing,1,15,9,3,5,1,0,0,0,1,0,0
27,2017-06-22 19:14:53,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,1,sourcing,3,14,12,3,6,2,0,1,0,0,1,0
28,2017-06-22 19:09:03,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,107,sourcing,2,14,11,2,6,2,0,1,0,0,0,1
29,2017-06-22 19:08:28,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,106,sourcing,2,14,11,2,6,2,0,1,0,0,1,0
30,2017-06-22 19:08:28,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,106,sourcing,2,14,11,2,6,2,0,1,0,0,0,1
33,2017-06-22 19:07:53,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,106,sourcing,3,13,12,3,6,2,0,1,0,0,1,0
34,2017-06-22 19:06:14,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,2,13,10,3,6,1,0,0,0,1,0,0
35,2017-06-22 19:06:08,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,3,13,12,3,6,2,0,1,0,0,1,0
40,2017-06-22 18:59:12,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,5,sourcing,2,12,10,3,7,0,0,0,0,1,0,0
41,2017-06-22 18:59:07,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,4,sourcing,4,12,12,3,7,1,0,1,0,0,1,0
54,2017-06-22 18:26:42,e2333b2dc03032f12c8526e45243f0c1,0.0,0.0,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,22,sourcing,2,14,9,2,7,0,0,0,0,1,0,0
56,2017-06-22 18:26:26,e2333b2dc03032f12c8526e45243f0c1,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,21,sourcing,4,14,11,2,7,1,0,1,0,0,1,0
57,2017-06-22 18:26:26,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,18,sourcing,4,14,11,2,7,1,0,1,0,0,0,1
58,2017-06-22 18:25:51,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,17,sourcing,4,15,11,2,7,1,0,1,0,0,1,0
59,2017-06-22 18:25:51,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,17,sourcing,4,15,11,2,7,1,0,1,0,0,0,1
60,2017-06-22 18:25:16,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,sourcing,17,sourcing,4,15,11,2,7,1,0,1,0,0,1,0
81,2017-06-22 17:03:03,b89eb67419465a9e2c9da08dae6023e2,0.0,0.0,Accepted Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,35,sourcing,2,14,8,5,3,0,0,0,0,1,0,0
82,2017-06-22 17:02:54,b89eb67419465a9e2c9da08dae6023e2,0.0,0.0,Assigned Job,594bebaa632eb100405ab4c3,2017-06-22 12:09:14,sourcing,35,sourcing,4,14,9,5,3,0,0,1,0,0,1,0
98,2017-06-22 16:17:23,9286ce84f2401fbd6635f7d768c3cad1,0.0,0.0,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,2,sourcing,2,15,5,5,0,0,0,0,0,1,0,0
99,2017-06-22 16:17:17,9286ce84f2401fbd6635f7d768c3cad1,0.0,0.0,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,2,sourcing,3,15,6,5,0,0,0,1,0,0,1,0
106,2017-06-22 16:01:43,b89eb67419465a9e2c9da08dae6023e2,0.0,0.0,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,sourcing,0,18,4,2,2,0,0,0,0,1,0,0
107,2017-06-22 16:01:36,b89eb67419465a9e2c9da08dae6023e2,0.0,0.0,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,sourcing,1,18,5,2,2,0,0,1,0,0,1,0
108,2017-06-22 15:57:43,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Declined Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,6,sourcing,2,19,5,2,2,0,0,1,0,0,0,1
109,2017-06-22 15:57:08,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,6,sourcing,2,20,5,2,2,0,0,1,0,0,1,0
110,2017-06-22 15:57:08,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Declined Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,6,sourcing,2,20,5,2,2,0,0,1,0,0,0,1
113,2017-06-22 15:56:33,00360b3f177375b01b795a4be7b4686c,0.0,0.0,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,5,sourcing,3,19,6,2,3,0,0,1,0,0,1,0
114,2017-06-22 15:50:34,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Accepted Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,sourcing,2,sourcing,1,19,4,2,2,0,0,0,0,1,0,0
115,2017-06-22 15:50:07,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,sourcing,1,sourcing,2,19,5,2,2,0,0,1,0,0,1,0
116,2017-06-22 15:50:07,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Declined Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,sourcing,1,sourcing,2,19,5,2,2,0,0,1,0,0,0,1
117,2017-06-22 15:49:32,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594bec83fd2cf400280aa965,2017-06-22 12:12:51,sourcing,1,sourcing,2,19,4,2,1,0,0,1,0,0,1,0
132,2017-06-22 15:30:50,95130c93e28b36bcb5ecd7e747b4d5c2,0.0,0.0,Declined Job,594c1abc73dd9c002873cdb8,2017-06-22 15:30:04,sourcing,16,sourcing,5,19,5,2,1,2,0,0,0,0,0,1
133,2017-06-22 15:30:15,95130c93e28b36bcb5ecd7e747b4d5c2,0.0,0.0,Assigned Job,594c1abc73dd9c002873cdb8,2017-06-22 15:30:04,sourcing,16,sourcing,5,18,6,2,1,2,0,1,0,0,1,0
161,2017-06-22 15:12:42,608b40f66ef114c6d9f5c95021290f69,0.0,0.0,Declined Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,sourcing,28,"sourcing, writing",8,13,9,2,4,2,0,1,0,0,0,1
162,2017-06-22 15:12:07,608b40f66ef114c6d9f5c95021290f69,0.0,0.0,Assigned Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,sourcing,28,"sourcing, writing",7,13,9,2,4,2,0,1,0,0,1,0
164,2017-06-22 15:12:07,608b40f66ef114c6d9f5c95021290f69,0.0,0.0,Declined Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,sourcing,28,"sourcing, writing",7,13,9,2,4,2,0,1,0,0,0,1
165,2017-06-22 15:11:32,608b40f66ef114c6d9f5c95021290f69,0.0,0.0,Assigned Job,594bec81fd2cf400280aa95c,2017-06-22 12:12:49,sourcing,27,"sourcing, writing",6,13,9,2,4,2,0,1,0,0,1,0
198,2017-06-22 14:24:23,9286ce84f2401fbd6635f7d768c3cad1,0.0,0.0,Accepted Job,594bec5e95e2ce005840c252,2017-06-22 12:12:14,sourcing,11,sourcing,4,15,7,0,2,5,0,0,0,1,0,0
199,2017-06-22 14:24:07,9286ce84f2401fbd6635f7d768c3cad1,0.0,0.0,Assigned Job,594bec5e95e2ce005840c252,2017-06-22 12:12:14,sourcing,11,sourcing,6,15,8,0,2,5,0,1,0,0,1,0
202,2017-06-22 14:04:23,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Accepted Job,594bcdd680f13f00405cd4e8,2017-06-22 10:01:58,sourcing,4,sourcing,2,12,8,0,2,6,0,0,0,1,0,0
203,2017-06-22 14:04:14,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Assigned Job,594bcdd680f13f00405cd4e8,2017-06-22 10:01:58,sourcing,4,sourcing,3,12,10,0,2,7,0,1,0,0,1,0
230,2017-06-22 13:22:16,30ea4ac9222bfa53b3849df49d6f26f0,0.0,0.0,Accepted Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,sourcing,2,sourcing,5,9,10,0,0,10,0,0,0,1,0,0
232,2017-06-22 13:22:08,30ea4ac9222bfa53b3849df49d6f26f0,0.0,0.0,Assigned Job,594bec5b95e2ce005840c232,2017-06-22 12:12:11,sourcing,2,sourcing,7,9,11,0,0,10,0,1,0,0,1,0
255,2017-06-22 12:54:05,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Declined Job,594aead5ef88150028311172,2017-06-21 17:53:25,writing,1,sourcing,7,7,13,0,0,12,0,0,1,0,0,1
256,2017-06-22 12:53:30,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Assigned Job,594aead5ef88150028311172,2017-06-21 17:53:25,writing,1,"sourcing, writing",4,7,13,0,0,12,0,0,1,0,1,0
301,2017-06-22 09:58:49,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Accepted Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,28,sourcing,1,9,0,0,0,0,0,0,0,1,0,0
302,2017-06-22 09:58:24,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Assigned Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,27,sourcing,3,9,2,0,0,1,0,1,0,0,1,0
303,2017-06-22 09:58:24,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Declined Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,7,sourcing,3,9,2,0,0,1,0,1,0,0,0,1
304,2017-06-22 09:57:49,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Assigned Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,6,sourcing,3,9,2,0,0,1,0,1,0,0,1,0
305,2017-06-22 09:57:49,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Declined Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,6,sourcing,3,9,2,0,0,1,0,1,0,0,0,1
306,2017-06-22 09:57:14,6b19235b9269df81b6da879771bf40bc,0.0,0.0,Assigned Job,594b945bf8b866004036d9c3,2017-06-22 05:56:43,sourcing,5,sourcing,3,10,2,0,0,1,0,1,0,0,1,0
338,2017-06-22 08:03:26,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,4,10,3,0,0,1,0,0,2,1,0,0
339,2017-06-22 08:03:23,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,4,10,4,0,0,1,0,1,2,0,1,0
340,2017-06-22 08:01:25,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,3,10,3,0,0,1,0,0,2,1,0,0
341,2017-06-22 08:01:22,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,3,10,3,0,0,1,0,0,2,1,0,0
342,2017-06-22 08:01:20,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,3,10,3,0,0,1,0,0,2,1,0,0
343,2017-06-22 08:01:03,a29fe6d26c1a49ff4a3c876eaee0a1af,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,5,10,4,0,0,1,0,1,2,0,1,0
344,2017-06-22 08:01:03,1f8d8b08a994331e419d24293ce9e7b0,0.0,0.0,Declined Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,7,sourcing,5,10,4,0,0,1,0,1,2,0,0,1
345,2017-06-22 08:00:28,1f8d8b08a994331e419d24293ce9e7b0,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,7,sourcing,4,10,3,0,0,0,0,1,2,0,1,0
346,2017-06-22 08:00:28,1f8d8b08a994331e419d24293ce9e7b0,0.0,0.0,Declined Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,7,sourcing,4,10,3,0,0,0,0,1,2,0,0,1
347,2017-06-22 07:59:53,1f8d8b08a994331e419d24293ce9e7b0,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,6,sourcing,2,11,2,0,0,0,0,1,1,0,1,0
386,2017-06-22 06:20:10,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,0,10,5,1,1,0,0,0,3,1,0,0
387,2017-06-22 06:20:08,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,1,10,6,1,1,0,0,1,3,0,1,0
415,2017-06-22 05:39:53,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Assigned Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,writing,3,12,5,2,0,0,0,0,3,0,1,0
416,2017-06-22 05:39:53,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Declined Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,writing,3,12,5,2,0,0,0,0,3,0,0,1
417,2017-06-22 05:39:18,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Assigned Job,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,1,writing,1,12,5,2,0,0,0,0,3,0,1,0
460,2017-06-22 04:27:11,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Accepted Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,5,sourcing,0,15,10,6,1,0,0,0,3,1,0,0
461,2017-06-22 04:27:06,2df8ce7d317c7d89dfa95be7695d2de0,0.0,0.0,Assigned Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,5,sourcing,1,15,11,6,1,0,0,1,3,0,1,0
492,2017-06-22 02:57:03,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Accepted Job,594b31f09d87570035cccafd,2017-06-21 22:56:48,sourcing,26,sourcing,1,12,12,5,1,0,1,0,5,1,0,0
493,2017-06-22 02:56:55,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594b31f09d87570035cccafd,2017-06-21 22:56:48,sourcing,26,sourcing,2,12,14,5,1,1,1,1,5,0,1,0
510,2017-06-22 02:05:27,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Accepted Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,1,writing,0,15,12,5,1,1,1,0,4,1,0,0
511,2017-06-22 02:05:22,c9401f82fdedf3cd080a03bafe3447c7,0.0,0.0,Assigned Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,1,writing,1,15,13,5,1,1,1,0,5,0,1,0
512,2017-06-22 02:04:20,77b8ab28b9e95edb3a69ca7a6d352ec8,0.0,0.0,Accepted Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,1,sourcing,1,14,13,5,1,1,1,0,5,1,0,0
513,2017-06-22 02:04:15,77b8ab28b9e95edb3a69ca7a6d352ec8,0.0,0.0,Assigned Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,1,sourcing,1,14,14,5,1,1,1,1,5,0,1,0
514,2017-06-22 02:03:43,5233d783ae5bf0483cf49549cbc594f8,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,0,13,14,5,1,1,1,1,5,1,0,0
515,2017-06-22 02:03:40,5233d783ae5bf0483cf49549cbc594f8,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,1,13,15,5,1,1,1,2,5,0,1,0
516,2017-06-22 01:59:14,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,editing,4,editing,1,14,13,5,1,1,0,1,5,1,0,0
517,2017-06-22 01:59:06,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,editing,3,editing,2,14,14,5,1,1,1,1,5,0,1,0
518,2017-06-22 01:59:05,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Declined Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,editing,3,editing,2,14,14,5,1,1,1,1,5,0,0,1
521,2017-06-22 01:58:30,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b06c06cdeef002881af83,2017-06-21 19:52:32,editing,3,editing,2,13,15,6,1,1,1,1,5,0,1,0
528,2017-06-22 01:40:09,77b8ab28b9e95edb3a69ca7a6d352ec8,0.0,0.0,Accepted Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,0,18,10,5,1,0,0,0,4,1,0,0
529,2017-06-22 01:40:05,77b8ab28b9e95edb3a69ca7a6d352ec8,0.0,0.0,Assigned Job,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,1,sourcing,1,18,11,5,1,0,0,1,4,0,1,0
530,2017-06-22 01:39:46,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b31f09d87570035cccafd,2017-06-21 22:56:48,vetting,1,"vetting, editing, sourcing",1,17,11,5,1,0,0,1,4,1,0,0
533,2017-06-22 01:39:30,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b31f09d87570035cccafd,2017-06-21 22:56:48,vetting,1,"vetting, editing, sourcing",2,16,13,6,2,0,0,1,4,0,1,0
552,2017-06-22 01:17:55,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b1abfa6992500289d6040,2017-06-21 21:17:51,vetting,1,"vetting, editing, sourcing",1,17,12,9,2,0,0,0,1,1,0,0
553,2017-06-22 01:17:52,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b1abfa6992500289d6040,2017-06-21 21:17:51,vetting,1,"vetting, editing, sourcing",1,17,12,9,2,0,0,0,1,1,0,0
554,2017-06-22 01:17:39,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b1abfa6992500289d6040,2017-06-21 21:17:51,vetting,1,"vetting, editing, sourcing",2,17,12,9,2,0,0,0,1,0,1,0
566,2017-06-22 00:20:28,b599bfb42906772db81ac90137fc1916,0.0,0.0,Accepted Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,1,sourcing,1,20,9,5,2,0,0,0,2,1,0,0
567,2017-06-22 00:20:26,b599bfb42906772db81ac90137fc1916,0.0,0.0,Assigned Job,594b20ef3f82d10028f03c7c,2017-06-21 21:44:15,sourcing,1,sourcing,2,20,10,5,2,0,0,1,2,0,1,0
582,2017-06-22 00:00:27,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b20ea3f82d10028f03c54,2017-06-21 21:44:10,sourcing,1,"editing, sourcing",0,19,12,4,2,1,0,3,2,1,0,0
583,2017-06-22 00:00:13,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b20ea3f82d10028f03c54,2017-06-21 21:44:10,sourcing,1,"editing, sourcing",1,19,13,4,2,1,0,4,2,0,1,0
584,2017-06-21 23:38:17,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Accepted Job,594b33d6fee3760035a1a540,2017-06-21 23:04:54,vetting,1,"vetting, editing, sourcing",0,22,10,3,2,1,0,3,1,1,0,0
585,2017-06-21 23:38:16,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594b33d6fee3760035a1a540,2017-06-21 23:04:54,vetting,1,"vetting, editing, sourcing",1,22,11,3,3,1,0,3,1,0,1,0
586,2017-06-21 23:37:09,c2dcc0b178176d7e6b185df9bd1cb4f2,0.0,0.0,Assigned Job,594ae6fb4f06e20035d92345,2017-06-21 17:36:59,writing,1,"editing, sourcing, writing",1,22,11,3,3,1,0,3,1,0,1,0
596,2017-06-21 23:22:37,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Accepted Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,1,22,8,1,3,2,0,1,1,1,0,0
597,2017-06-21 23:22:36,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Accepted Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,1,22,8,1,3,2,0,1,1,1,0,0
598,2017-06-21 23:22:35,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Accepted Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,1,22,8,1,3,2,0,1,1,1,0,0
600,2017-06-21 23:22:30,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.0,0.0,Assigned Job,594b20eb3f82d10028f03c5c,2017-06-21 21:44:11,sourcing,1,sourcing,2,22,9,1,3,2,0,2,1,0,1,0
606,2017-06-21 23:12:02,ea5354c723ba83f2c412c238b133e84a,0.0,0.0,Accepted Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",2,23,8,1,3,2,0,1,1,1,0,0
608,2017-06-21 23:11:54,ea5354c723ba83f2c412c238b133e84a,0.0,0.0,Assigned Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",3,23,9,1,3,2,0,1,2,0,1,0
620,2017-06-21 23:06:55,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Accepted Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",4,24,7,1,3,2,0,0,1,1,0,0
621,2017-06-21 23:06:39,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Assigned Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",3,24,8,1,3,2,0,0,2,0,1,0
622,2017-06-21 23:05:29,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Declined Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2,"sourcing, writing",2,25,7,0,3,2,0,0,2,0,0,1
623,2017-06-21 23:04:54,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Assigned Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",2,25,6,0,2,2,0,0,2,0,1,0
624,2017-06-21 23:04:54,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Declined Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",2,25,6,0,2,2,0,0,2,0,0,1
626,2017-06-21 23:04:19,d9837e646a15a4fdd823531178b2d62e,0.0,0.0,Assigned Job,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,1,"sourcing, writing",3,24,7,0,2,2,0,0,3,0,1,0
628,2017-06-21 23:02:02,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Accepted Job,594b20ea3f82d10028f03c54,2017-06-21 21:44:10,sourcing,1,sourcing,1,22,7,0,2,2,0,0,3,1,0,0
629,2017-06-21 23:02:01,b692db6843c42f5ce686fcdfda4e0b62,0.0,0.0,Accepted Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,1,sourcing,2,22,8,0,2,2,0,1,3,1,0,0
630,2017-06-21 23:01:59,b692db6843c42f5ce686fcdfda4e0b62,0.0,0.0,Assigned Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,1,sourcing,3,22,10,0,2,3,0,2,3,0,1,0
631,2017-06-21 23:01:59,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,594b20ea3f82d10028f03c54,2017-06-21 21:44:10,sourcing,1,sourcing,3,22,10,0,2,3,0,2,3,0,1,0
642,2017-06-21 22:38:56,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Accepted Job,594aead5ef88150028311172,2017-06-21 17:53:25,sourcing,2,sourcing,0,23,6,1,1,3,0,0,1,1,0,0
643,2017-06-21 22:38:50,98de7e62209a07eee6ec8dc984911042,0.0,0.0,Assigned Job,594aead5ef88150028311172,2017-06-21 17:53:25,sourcing,2,sourcing,1,22,9,1,1,4,0,1,2,0,1,0
705,2017-06-21 21:34:05,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Accepted Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,1,sourcing,0,20,8,6,1,0,0,0,1,1,0,0
706,2017-06-21 21:33:52,8258591d197a3936de0f7ee021ab9e0e,0.0,0.0,Assigned Job,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,1,sourcing,2,20,10,6,1,1,0,1,1,0,1,0
716,2017-06-21 21:26:19,b599bfb42906772db81ac90137fc1916,0.0,0.0,Accepted Job,59485c262e71030033104e3c,2017-06-19 19:20:06,sourcing,1,sourcing,2,21,6,5,1,0,0,0,0,1,0,0

In [43]:
df[df['Action'] == 'Declined Job'].describe()

,Quality score (sourcing),Quality score (writing),Wait time (min),Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available,Accepted Job,Assigned Job,Declined Job
count,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.0,95.0,95.0
mean,3.294211,3.294211,12.294737,3.494737,16.431579,7.842105,2.800000,2.031579,1.463158,0.031579,0.536842,0.978947,0.0,0.0,1.0
std,2.205641,2.205641,20.636610,1.934423,5.037419,3.412480,2.611757,1.932106,2.220842,0.175804,0.649231,1.263051,0.0,0.0,0.0
min,0.000000,0.000000,1.000000,1.000000,7.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.0
25%,0.000000,0.000000,2.000000,2.000000,13.000000,5.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.0
50%,4.500000,4.500000,3.000000,3.000000,17.000000,8.000000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.0,1.0
75%,4.930000,4.930000,14.500000,5.000000,20.000000,10.000000,5.000000,3.000000,2.000000,0.000000,1.000000,2.000000,0.0,0.0,1.0
max,5.000000,5.000000,107.000000,8.000000,25.000000,14.000000,9.000000,7.000000,12.000000,1.000000,3.000000,5.000000,0.0,0.0,1.0

In [44]:
df.groupby('Analyst')['Request'].count()

Analyst
00360b3f177375b01b795a4be7b4686c     8
008fa95f5c94985e2d44047aeac31655     7
052066814364850e1a17a90d576dd904     3
0c2680433387fb4cf51a3546296f8422    18
0e9802516f8a79dd0d45211dd4ee74af    24
1f8d8b08a994331e419d24293ce9e7b0     4
206de922289a1f9f5ee250fc71308628     7
2d0f64a208f69a70ec415cfccb59cc24     4
2df8ce7d317c7d89dfa95be7695d2de0     8
30ea4ac9222bfa53b3849df49d6f26f0     2
32553d485988e2ddcf0f701c60754f2d     4
36ee9fc3bade4a4f71c2a6e5c2bd8862     4
39012c98c8fb80752d2bbcc3dc285230     8
39b71201151caf98fd10afce50cfc83e    12
3a29165b73c047e745934c2cbbfaac1b     4
3a8a0b0323b02a707535fe7d65821de3     2
482e9b14d8d59b748320f89074362746     8
4bb6e496f0c92286dee7eed7038ddd9d     8
5078cc506436a8668c0b6de594842fcf     1
5233d783ae5bf0483cf49549cbc594f8     2
5238b0785b5576f5ffe665136df9244f     4
57ef46a92ecee8e187f4d450e92651ea     2
608b40f66ef114c6d9f5c95021290f69     4
62060850630c7afe54fd59151413d237    46
632a6492e9ff20cc4a442245836424e5     6
642782c690c8d963c487300a4751e220    42
6b19235b9269df81b6da879771bf40bc     8
6c6bd5e891c4015e534773dfb19f29b0    19
710dbda77cade1eced9c735c08e6e38d    14
732e4a29b2e318bce3c1e923276ddf51    42
766d3435eda76c4de9f034b8f97a0602     3
77b8ab28b9e95edb3a69ca7a6d352ec8     4
795930bc4ed320777ad76b46da2ed66d    14
7e22ad15724c44543d1d4bcafd10c812    28
8258591d197a3936de0f7ee021ab9e0e    17
83f00c2268afaf459715f4c52e16dd23     2
85c7b78e76b5232cd38014ea4cdc8f56    34
9286ce84f2401fbd6635f7d768c3cad1     4
94959cf2d0b592d0fa1e5e9cf760a1c7    26
95130c93e28b36bcb5ecd7e747b4d5c2     2
98de7e62209a07eee6ec8dc984911042    10
9fa24ddce8fd9d1526d9d7451304fc74    17
9fcbc63ff4c8bea5cea4efad782c87cf    40
a09c8906073b4c0b75e3100b857b982a    72
a29fe6d26c1a49ff4a3c876eaee0a1af     4
b599bfb42906772db81ac90137fc1916     4
b692db6843c42f5ce686fcdfda4e0b62     2
b89eb67419465a9e2c9da08dae6023e2     4
bcd8d747b5af397febc04228293f747f     2
c033808b89b50e6f550caf266470f090     8
c2d7982e24aadeea8921108d0eb756d8     8
c2dcc0b178176d7e6b185df9bd1cb4f2    16
c9401f82fdedf3cd080a03bafe3447c7    17
caf77e4ba6154e998b352cc92c685f80    15
d5aa695af013ee5baaeeccfb7ca50c80    10
d6eaa4eeb52b4d62ec78299454763870    15
d74c4a7423dd3ee0a78de5481c364823     4
d8e25a290ea51352bf9100a99c475f6d    19
d9837e646a15a4fdd823531178b2d62e     8
dddcdea13df8232803957a5d9c847aae    13
de71db592b02c988670ca3d301a02568     4
dee1febfdeb9c90a41759cb330c72fd4     6
e2333b2dc03032f12c8526e45243f0c1     2
e817dd4305458b293cbeb3015da99565     2
e8a2b0b2e2234a89dc52dd8a3e0f79e6     4
e9468b4c33f88d6937c4ad2bea8bbc2f     2
ea452a7456e38887ca8b98f4e131d224     2
ea5354c723ba83f2c412c238b133e84a     2
ef7e6e9fd91d89f2e31b26b9feaec787     2
f3b93c5ae97215ae15fa63b5f0fc30e1     2
f7f7591403c6c431053920223069550a    14
Name: Request, dtype: int64

In [45]:
df.groupby(['Request', 'Analyst'])['Wait time (min)'].sum()

Request                   Analyst
59480d57e759070028da6467  a09c8906073b4c0b75e3100b857b982a      2
                          d8e25a290ea51352bf9100a99c475f6d      7
59485c262e71030033104e3c  642782c690c8d963c487300a4751e220      2
                          7e22ad15724c44543d1d4bcafd10c812      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          b599bfb42906772db81ac90137fc1916      2
                          e817dd4305458b293cbeb3015da99565      2
59486e7af5874900429ce273  9fcbc63ff4c8bea5cea4efad782c87cf      2
5949462dd9ae5200633f9640  39012c98c8fb80752d2bbcc3dc285230      2
                          9fa24ddce8fd9d1526d9d7451304fc74     10
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
59494c13d9ae5200633f9695  a09c8906073b4c0b75e3100b857b982a      2
5949a81c4d1319005556396c  39012c98c8fb80752d2bbcc3dc285230      4
                          632a6492e9ff20cc4a442245836424e5      2
                          642782c690c8d963c487300a4751e220      4
                          710dbda77cade1eced9c735c08e6e38d      2
                          732e4a29b2e318bce3c1e923276ddf51      2
                          795930bc4ed320777ad76b46da2ed66d      2
                          7e22ad15724c44543d1d4bcafd10c812      2
                          8258591d197a3936de0f7ee021ab9e0e      2
                          9fa24ddce8fd9d1526d9d7451304fc74    107
                          a09c8906073b4c0b75e3100b857b982a      2
                          b692db6843c42f5ce686fcdfda4e0b62      2
                          c9401f82fdedf3cd080a03bafe3447c7      2
                          d74c4a7423dd3ee0a78de5481c364823      2
                          de71db592b02c988670ca3d301a02568      2
5949bdb4fe2f5d005b4f4910  39012c98c8fb80752d2bbcc3dc285230      2
5949bdbcfe2f5d005b4f4928  c033808b89b50e6f550caf266470f090      2
5949e376f03c130028baa724  482e9b14d8d59b748320f89074362746      2
                          dddcdea13df8232803957a5d9c847aae      6
594a4325499a400071d4cca4  9fcbc63ff4c8bea5cea4efad782c87cf      2
594a536d220b450040dc0182  9fcbc63ff4c8bea5cea4efad782c87cf      2
594a5e5566cb69006fdcf09d  008fa95f5c94985e2d44047aeac31655      9
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          c2dcc0b178176d7e6b185df9bd1cb4f2      2
594a8f5664251c002831f4c5  2d0f64a208f69a70ec415cfccb59cc24      8
                          a09c8906073b4c0b75e3100b857b982a      4
                          d5aa695af013ee5baaeeccfb7ca50c80      4
594a8fd422b3c50028e71976  0c2680433387fb4cf51a3546296f8422      2
                          2d0f64a208f69a70ec415cfccb59cc24      2
                          482e9b14d8d59b748320f89074362746      2
                          642782c690c8d963c487300a4751e220      4
                          732e4a29b2e318bce3c1e923276ddf51      2
                          766d3435eda76c4de9f034b8f97a0602      2
                          795930bc4ed320777ad76b46da2ed66d      3
                          7e22ad15724c44543d1d4bcafd10c812      2
                          c9401f82fdedf3cd080a03bafe3447c7      3
                          caf77e4ba6154e998b352cc92c685f80      1
594a9ce6c864e200288e766b  1f8d8b08a994331e419d24293ce9e7b0     27
                          2df8ce7d317c7d89dfa95be7695d2de0      2
                          5233d783ae5bf0483cf49549cbc594f8      2
                          57ef46a92ecee8e187f4d450e92651ea      2
                          642782c690c8d963c487300a4751e220      2
                          77b8ab28b9e95edb3a69ca7a6d352ec8      2
                          795930bc4ed320777ad76b46da2ed66d     47
                          7e22ad15724c44543d1d4bcafd10c812      2
                          98de7e62209a07eee6ec8dc984911042      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          a29fe6d26c1a49ff4a3c876eaee0a1af      4
                          caf77e4ba6154e998b352cc92c685f80      2
594aa36664251c002831f51e  9fcbc63ff4c8bea5cea4efad782c87cf      2
594ab554c864e200288e76ef  0c2680433387fb4cf51a3546296f8422      2
                          0e9802516f8a79dd0d45211dd4ee74af      2
                          482e9b14d8d59b748320f89074362746      2
                          795930bc4ed320777ad76b46da2ed66d     54
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          c033808b89b50e6f550caf266470f090      2
                          c9401f82fdedf3cd080a03bafe3447c7    197
                          caf77e4ba6154e998b352cc92c685f80      2
                          d6eaa4eeb52b4d62ec78299454763870      2
                          d9837e646a15a4fdd823531178b2d62e      7
                          dddcdea13df8232803957a5d9c847aae      4
                          e8a2b0b2e2234a89dc52dd8a3e0f79e6      2
                          ea5354c723ba83f2c412c238b133e84a      2
594ada897a05b40035f08be4  32553d485988e2ddcf0f701c60754f2d      2
                          a09c8906073b4c0b75e3100b857b982a      2
594ae6944f06e20035d92325  0e9802516f8a79dd0d45211dd4ee74af      4
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
594ae6994f06e20035d92335  732e4a29b2e318bce3c1e923276ddf51      7
                          9fcbc63ff4c8bea5cea4efad782c87cf      7
                          a09c8906073b4c0b75e3100b857b982a      2
594ae6fa4f06e20035d9233d  a09c8906073b4c0b75e3100b857b982a      2
594ae6fb4f06e20035d92345  206de922289a1f9f5ee250fc71308628      3
                          5078cc506436a8668c0b6de594842fcf      1
                          632a6492e9ff20cc4a442245836424e5      5
                          7e22ad15724c44543d1d4bcafd10c812      2
                          9fcbc63ff4c8bea5cea4efad782c87cf      4
                          c2dcc0b178176d7e6b185df9bd1cb4f2      1
                          caf77e4ba6154e998b352cc92c685f80      2
                          d6eaa4eeb52b4d62ec78299454763870      5
594aead5ef88150028311172  0c2680433387fb4cf51a3546296f8422     32
                          0e9802516f8a79dd0d45211dd4ee74af      2
                          206de922289a1f9f5ee250fc71308628      2
                          39b71201151caf98fd10afce50cfc83e     50
                          4bb6e496f0c92286dee7eed7038ddd9d      2
                          98de7e62209a07eee6ec8dc984911042      4
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          bcd8d747b5af397febc04228293f747f      3
                          d9837e646a15a4fdd823531178b2d62e      2
594aec513f82d10028f03b9a  a09c8906073b4c0b75e3100b857b982a      2
594af29d3f82d10028f03bb2  0e9802516f8a79dd0d45211dd4ee74af      4
                          32553d485988e2ddcf0f701c60754f2d      2
                          39b71201151caf98fd10afce50cfc83e      2
                          642782c690c8d963c487300a4751e220      6
                          766d3435eda76c4de9f034b8f97a0602      1
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          ef7e6e9fd91d89f2e31b26b9feaec787     10
                          f3b93c5ae97215ae15fa63b5f0fc30e1      2
594af3c6f3b9f600287eabe0  482e9b14d8d59b748320f89074362746      2
                          7e22ad15724c44543d1d4bcafd10c812      2
                          a09c8906073b4c0b75e3100b857b982a      2
594b00e23f82d10028f03be2  6c6bd5e891c4015e534773dfb19f29b0      2
                          7e22ad15724c44543d1d4bcafd10c812      2
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          d8e25a290ea51352bf9100a99c475f6d      2
594b0303f3b9f600287eac2b  0e9802516f8a79dd0d45211dd4ee74af      2
                          4bb6e496f0c92286dee7eed7038ddd9d      2
                          642782c690c8d963c487300a4751e220      2
                          7e22ad15724c44543d1d4bcafd10c812      4
                          85c7b78e76b5232cd38014ea4cdc8f56      4
                          9fa24ddce8fd9d1526d9d7451304fc74      2
                          caf77e4ba6154e998b352cc92c685f80      2
                          d6eaa4eeb52b4d62ec78299454763870      2
                          d8e25a290ea51352bf9100a99c475f6d      2
594b06bf6cdeef002881af7b  0e9802516f8a79dd0d45211dd4ee74af      2
                          8258591d197a3936de0f7ee021ab9e0e      8
594b06c06cdeef002881af83  206de922289a1f9f5ee250fc71308628      2
                          5238b0785b5576f5ffe665136df9244f     23
                          8258591d197a3936de0f7ee021ab9e0e      3
                          98de7e62209a07eee6ec8dc984911042      5
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          c2dcc0b178176d7e6b185df9bd1cb4f2     13
                          d5aa695af013ee5baaeeccfb7ca50c80      3
594b1abfa6992500289d6040  0c2680433387fb4cf51a3546296f8422      2
                          39b71201151caf98fd10afce50cfc83e      2
                          3a29165b73c047e745934c2cbbfaac1b      2
                          642782c690c8d963c487300a4751e220     14
                          6c6bd5e891c4015e534773dfb19f29b0      3
                          85c7b78e76b5232cd38014ea4cdc8f56    289
                          c2dcc0b178176d7e6b185df9bd1cb4f2      3
594b20ea3f82d10028f03c54  642782c690c8d963c487300a4751e220      2
                          732e4a29b2e318bce3c1e923276ddf51      3
                          8258591d197a3936de0f7ee021ab9e0e      2
                          85c7b78e76b5232cd38014ea4cdc8f56      7
                          a09c8906073b4c0b75e3100b857b982a      2
                          c2dcc0b178176d7e6b185df9bd1cb4f2      2
                          d8e25a290ea51352bf9100a99c475f6d      2
                          f7f7591403c6c431053920223069550a     27
594b20eb3f82d10028f03c5c  0e9802516f8a79dd0d45211dd4ee74af      4
                          36ee9fc3bade4a4f71c2a6e5c2bd8862      4
                          39b71201151caf98fd10afce50cfc83e      2
                          642782c690c8d963c487300a4751e220      2
                          732e4a29b2e318bce3c1e923276ddf51      3
                          85c7b78e76b5232cd38014ea4cdc8f56     85
                          a09c8906073b4c0b75e3100b857b982a      7
                          caf77e4ba6154e998b352cc92c685f80      5
                          f7f7591403c6c431053920223069550a      2
594b20ec3f82d10028f03c64  0c2680433387fb4cf51a3546296f8422      2
                          732e4a29b2e318bce3c1e923276ddf51      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          e8a2b0b2e2234a89dc52dd8a3e0f79e6      2
594b20ed3f82d10028f03c6c  7e22ad15724c44543d1d4bcafd10c812      2
                          9fcbc63ff4c8bea5cea4efad782c87cf      4
                          a09c8906073b4c0b75e3100b857b982a      7
                          f7f7591403c6c431053920223069550a      2
594b20ee3f82d10028f03c74  7e22ad15724c44543d1d4bcafd10c812      2
                          85c7b78e76b5232cd38014ea4cdc8f56      2
                          a09c8906073b4c0b75e3100b857b982a      5
                          d6eaa4eeb52b4d62ec78299454763870      2
                          f7f7591403c6c431053920223069550a      2
594b20ef3f82d10028f03c7c  2df8ce7d317c7d89dfa95be7695d2de0     10
                          642782c690c8d963c487300a4751e220    131
                          710dbda77cade1eced9c735c08e6e38d      2
                          77b8ab28b9e95edb3a69ca7a6d352ec8      2
                          85c7b78e76b5232cd38014ea4cdc8f56      8
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
                          b599bfb42906772db81ac90137fc1916      2
                          d6eaa4eeb52b4d62ec78299454763870      2
                          e9468b4c33f88d6937c4ad2bea8bbc2f      2
                          f7f7591403c6c431053920223069550a      2
594b31f09d87570035cccafd  052066814364850e1a17a90d576dd904      3
                          39b71201151caf98fd10afce50cfc83e      2
                          4bb6e496f0c92286dee7eed7038ddd9d      2
                          795930bc4ed320777ad76b46da2ed66d     51
                          7e22ad15724c44543d1d4bcafd10c812    219
                          8258591d197a3936de0f7ee021ab9e0e     52
                          c2dcc0b178176d7e6b185df9bd1cb4f2      2
                          caf77e4ba6154e998b352cc92c685f80      2
                          dee1febfdeb9c90a41759cb330c72fd4      2
                          ea452a7456e38887ca8b98f4e131d224      2
594b33d6fee3760035a1a540  7e22ad15724c44543d1d4bcafd10c812      2
                          c2dcc0b178176d7e6b185df9bd1cb4f2      2
594b52f717d10a00289676dd  6c6bd5e891c4015e534773dfb19f29b0      8
594b6c6a96165a002896b124  6c6bd5e891c4015e534773dfb19f29b0      6
594b945bf8b866004036d9c3  0e9802516f8a79dd0d45211dd4ee74af      8
                          2df8ce7d317c7d89dfa95be7695d2de0     55
                          39b71201151caf98fd10afce50cfc83e     60
                          642782c690c8d963c487300a4751e220     47
                          6b19235b9269df81b6da879771bf40bc     24
                          732e4a29b2e318bce3c1e923276ddf51      2
                          de71db592b02c988670ca3d301a02568      2
594b9dd57c3b31004d97a6dc  4bb6e496f0c92286dee7eed7038ddd9d      2
                          732e4a29b2e318bce3c1e923276ddf51      2
                          d6eaa4eeb52b4d62ec78299454763870      2
594babd780f13f00405cd449  642782c690c8d963c487300a4751e220      2
594baca737b4b7004b683616  642782c690c8d963c487300a4751e220      2
                          732e4a29b2e318bce3c1e923276ddf51      2
594bcdd580f13f00405cd4e0  dee1febfdeb9c90a41759cb330c72fd4      2
594bcdd680f13f00405cd4e8  2df8ce7d317c7d89dfa95be7695d2de0      8
                          3a8a0b0323b02a707535fe7d65821de3      2
                          710dbda77cade1eced9c735c08e6e38d      2
                          83f00c2268afaf459715f4c52e16dd23     14
                          9fa24ddce8fd9d1526d9d7451304fc74     40
                          d8e25a290ea51352bf9100a99c475f6d      2
                          dee1febfdeb9c90a41759cb330c72fd4      2
594bcdd780f13f00405cd4f0  710dbda77cade1eced9c735c08e6e38d      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          d74c4a7423dd3ee0a78de5481c364823     52
594bde9ffd2cf400280aa920  732e4a29b2e318bce3c1e923276ddf51      2
594bebaa632eb100405ab4c3  0c2680433387fb4cf51a3546296f8422     93
                          642782c690c8d963c487300a4751e220      4
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          b89eb67419465a9e2c9da08dae6023e2     70
                          dddcdea13df8232803957a5d9c847aae      9
594bec5a95e2ce005840c22a  0e9802516f8a79dd0d45211dd4ee74af      2
                          732e4a29b2e318bce3c1e923276ddf51      5
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          9fa24ddce8fd9d1526d9d7451304fc74    107
594bec5b95e2ce005840c232  30ea4ac9222bfa53b3849df49d6f26f0      4
                          3a29165b73c047e745934c2cbbfaac1b     16
                          732e4a29b2e318bce3c1e923276ddf51      3
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          a09c8906073b4c0b75e3100b857b982a      4
594bec5c95e2ce005840c23a  732e4a29b2e318bce3c1e923276ddf51      1
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          9fcbc63ff4c8bea5cea4efad782c87cf      2
594bec5c95e2ce005840c242  732e4a29b2e318bce3c1e923276ddf51      2
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          9fa24ddce8fd9d1526d9d7451304fc74     30
                          a09c8906073b4c0b75e3100b857b982a      2
                          d6eaa4eeb52b4d62ec78299454763870     32
594bec5d95e2ce005840c24a  732e4a29b2e318bce3c1e923276ddf51      2
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
594bec5e95e2ce005840c252  732e4a29b2e318bce3c1e923276ddf51      2
                          9286ce84f2401fbd6635f7d768c3cad1     22
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          a09c8906073b4c0b75e3100b857b982a      2
                          c033808b89b50e6f550caf266470f090      8
594bec5e95e2ce005840c25a  710dbda77cade1eced9c735c08e6e38d      2
                          732e4a29b2e318bce3c1e923276ddf51      3
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
594bec7ffd2cf400280aa953  94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          9fa24ddce8fd9d1526d9d7451304fc74     78
                          d5aa695af013ee5baaeeccfb7ca50c80      3
594bec81fd2cf400280aa95c  608b40f66ef114c6d9f5c95021290f69    111
                          85c7b78e76b5232cd38014ea4cdc8f56     15
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          c2d7982e24aadeea8921108d0eb756d8     13
594bec83fd2cf400280aa965  0c2680433387fb4cf51a3546296f8422     56
                          0e9802516f8a79dd0d45211dd4ee74af      2
                          85c7b78e76b5232cd38014ea4cdc8f56     33
                          94959cf2d0b592d0fa1e5e9cf760a1c7      2
                          98de7e62209a07eee6ec8dc984911042      5
                          a09c8906073b4c0b75e3100b857b982a      2
                          c2d7982e24aadeea8921108d0eb756d8    129
                          dddcdea13df8232803957a5d9c847aae     28
594bfcde70709600281a12b8  62060850630c7afe54fd59151413d237      7
                          642782c690c8d963c487300a4751e220      2
594c0645b99a200028ff12fe  62060850630c7afe54fd59151413d237     11
594c0b883b593b002812506e  00360b3f177375b01b795a4be7b4686c    425
                          62060850630c7afe54fd59151413d237      4
                          6b19235b9269df81b6da879771bf40bc      9
                          8258591d197a3936de0f7ee021ab9e0e     71
                          94959cf2d0b592d0fa1e5e9cf760a1c7     24
                          a09c8906073b4c0b75e3100b857b982a     71
                          e2333b2dc03032f12c8526e45243f0c1     43
594c151273dd9c002873cd98  62060850630c7afe54fd59151413d237     19
                          6b19235b9269df81b6da879771bf40bc     12
                          c033808b89b50e6f550caf266470f090      2
594c15a573dd9c002873cda1  00360b3f177375b01b795a4be7b4686c     23
                          62060850630c7afe54fd59151413d237      9
                          9286ce84f2401fbd6635f7d768c3cad1      4
                          a09c8906073b4c0b75e3100b857b982a      2
                          b89eb67419465a9e2c9da08dae6023e2      2
594c1abc73dd9c002873cdb8  95130c93e28b36bcb5ecd7e747b4d5c2     32
594c1e983b593b00281250ba  62060850630c7afe54fd59151413d237      2
                          85c7b78e76b5232cd38014ea4cdc8f56      8
594c1f5cd7e68f0028c9062c  0e9802516f8a79dd0d45211dd4ee74af      2
                          62060850630c7afe54fd59151413d237      2
594c20b773dd9c002873cdda  62060850630c7afe54fd59151413d237      2
594c28953b593b00281250e1  62060850630c7afe54fd59151413d237      7
594c2e992c137900353e0faa  d8e25a290ea51352bf9100a99c475f6d      2
594c3f0c73dd9c002873ce44  d8e25a290ea51352bf9100a99c475f6d      2
594c41482c137900353e0fea  d8e25a290ea51352bf9100a99c475f6d      3
594c41ab1e24bf00350a1f11  710dbda77cade1eced9c735c08e6e38d      4
Name: Wait time (min), dtype: int64

In [46]:
df[df['Request'] == '594c151273dd9c002873cd98']

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available,Accepted Job,Assigned Job,Declined Job
17,2017-06-22 19:31:18,c033808b89b50e6f550caf266470f090,4.90,4.90,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,1,"editing, sourcing, writing",2,10,11,5,5,1,0,0,0,1,0,0
18,2017-06-22 19:31:15,c033808b89b50e6f550caf266470f090,4.90,4.90,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,1,"editing, sourcing, writing",2,10,13,5,5,2,0,1,0,0,1,0
34,2017-06-22 19:06:14,6b19235b9269df81b6da879771bf40bc,0.00,0.00,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,2,13,10,3,6,1,0,0,0,1,0,0
35,2017-06-22 19:06:08,6b19235b9269df81b6da879771bf40bc,0.00,0.00,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,sourcing,6,sourcing,3,13,12,3,6,2,0,1,0,0,1,0
126,2017-06-22 15:34:23,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,19,4,2,0,2,0,0,0,1,0,0
127,2017-06-22 15:34:21,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",6,19,5,2,1,2,0,0,0,0,1,0
128,2017-06-22 15:33:11,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",6,19,5,2,1,2,0,0,0,0,0,1
129,2017-06-22 15:32:36,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0,0,1,0
130,2017-06-22 15:32:36,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0,0,0,1
131,2017-06-22 15:32:01,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0,0,1,0
134,2017-06-22 15:27:20,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0,0,0,1
135,2017-06-22 15:26:45,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0,0,1,0
136,2017-06-22 15:26:45,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0,0,0,1
137,2017-06-22 15:26:10,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",6,17,4,2,1,1,0,0,0,0,1,0
138,2017-06-22 15:23:50,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",8,17,4,2,1,1,0,0,0,0,0,1
139,2017-06-22 15:23:15,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0,0,1,0
140,2017-06-22 15:23:15,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0,0,0,1
141,2017-06-22 15:22:39,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,4,2,1,1,0,0,0,0,1,0

In [47]:
df[df['Analyst'] == '62060850630c7afe54fd59151413d237']

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available,Accepted Job,Assigned Job,Declined Job
96,2017-06-22 16:29:48,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c28953b593b00281250e1,2017-06-22 16:29:09,vetting,4,"vetting, planning, editing, sourcing, writing",4,15,6,6,0,0,0,0,0,1,0,0
97,2017-06-22 16:29:33,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c28953b593b00281250e1,2017-06-22 16:29:09,vetting,3,"vetting, planning, editing, sourcing, writing",5,15,7,6,1,0,0,0,0,0,1,0
100,2017-06-22 16:09:53,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,"vetting, planning, editing, sourcing, writing",0,17,4,4,0,0,0,0,0,1,0,0
101,2017-06-22 16:09:47,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,sourcing,1,"vetting, planning, editing, sourcing, writing",1,17,5,4,0,0,0,1,0,0,1,0
102,2017-06-22 16:05:31,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c20b773dd9c002873cdda,2017-06-22 15:55:35,vetting,1,"vetting, planning, editing, sourcing, writing",0,18,3,2,0,0,0,1,0,1,0,0
103,2017-06-22 16:05:27,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c20b773dd9c002873cdda,2017-06-22 15:55:35,vetting,1,"vetting, planning, editing, sourcing, writing",1,18,4,2,1,0,0,1,0,0,1,0
104,2017-06-22 16:02:15,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",0,19,3,2,1,0,0,0,0,1,0,0
105,2017-06-22 16:02:11,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c1e983b593b00281250ba,2017-06-22 15:46:32,vetting,1,"vetting, planning, editing, sourcing, writing",1,19,4,2,2,0,0,0,0,0,1,0
111,2017-06-22 15:57:02,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c1f5cd7e68f0028c9062c,2017-06-22 15:49:48,vetting,1,"vetting, planning, editing, sourcing, writing",2,19,5,2,2,0,0,1,0,1,0,0
112,2017-06-22 15:56:33,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c1f5cd7e68f0028c9062c,2017-06-22 15:49:48,vetting,1,"vetting, planning, editing, sourcing, writing",3,19,6,2,3,0,0,1,0,0,1,0
124,2017-06-22 15:37:20,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,planning,1,"vetting, planning, editing, sourcing, writing",4,18,3,2,0,1,0,0,0,1,0,0
125,2017-06-22 15:37:16,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,planning,1,"vetting, planning, editing, sourcing, writing",5,18,4,2,0,2,0,0,0,0,1,0
126,2017-06-22 15:34:23,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,19,4,2,0,2,0,0,0,1,0,0
127,2017-06-22 15:34:21,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",6,19,5,2,1,2,0,0,0,0,1,0
128,2017-06-22 15:33:11,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",6,19,5,2,1,2,0,0,0,0,0,1
129,2017-06-22 15:32:36,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0,0,1,0
130,2017-06-22 15:32:36,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0,0,0,1
131,2017-06-22 15:32:01,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,19,5,2,1,2,0,0,0,0,1,0
134,2017-06-22 15:27:20,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0,0,0,1
135,2017-06-22 15:26:45,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0,0,1,0
136,2017-06-22 15:26:45,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",5,17,4,2,1,1,0,0,0,0,0,1
137,2017-06-22 15:26:10,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",6,17,4,2,1,1,0,0,0,0,1,0
138,2017-06-22 15:23:50,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,2,"vetting, planning, editing, sourcing, writing",8,17,4,2,1,1,0,0,0,0,0,1
139,2017-06-22 15:23:15,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0,0,1,0
140,2017-06-22 15:23:15,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0,0,0,1
141,2017-06-22 15:22:39,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c151273dd9c002873cd98,2017-06-22 15:05:54,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,4,2,1,1,0,0,0,0,1,0
142,2017-06-22 15:19:23,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c0b883b593b002812506e,2017-06-22 14:25:12,vetting,1,"vetting, planning, editing, sourcing, writing",7,17,4,2,1,1,0,0,0,1,0,0
143,2017-06-22 15:19:09,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,5,2,2,1,0,0,0,0,1,0
144,2017-06-22 15:19:09,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c0b883b593b002812506e,2017-06-22 14:25:12,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,5,2,2,1,0,0,0,0,0,1
145,2017-06-22 15:18:34,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0b883b593b002812506e,2017-06-22 14:25:12,vetting,1,"vetting, planning, editing, sourcing, writing",8,17,5,2,2,1,0,0,0,0,1,0
146,2017-06-22 15:16:09,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,vetting,2,"vetting, planning, editing, sourcing, writing",5,17,5,2,2,1,0,0,0,1,0,0
147,2017-06-22 15:15:38,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,vetting,1,"vetting, planning, editing, sourcing, writing",6,17,6,2,3,1,0,0,0,0,1,0
148,2017-06-22 15:15:38,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,vetting,1,"vetting, planning, editing, sourcing, writing",6,17,6,2,3,1,0,0,0,0,0,1
149,2017-06-22 15:15:03,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c15a573dd9c002873cda1,2017-06-22 15:08:21,vetting,1,"vetting, planning, editing, sourcing, writing",6,16,6,2,3,1,0,0,0,0,1,0
157,2017-06-22 15:12:45,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594bfcde70709600281a12b8,2017-06-22 13:22:38,vetting,2,"vetting, planning, editing, sourcing, writing",6,13,8,2,3,2,0,1,0,1,0,0
158,2017-06-22 15:12:42,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594bfcde70709600281a12b8,2017-06-22 13:22:38,vetting,2,"vetting, planning, editing, sourcing, writing",8,13,9,2,4,2,0,1,0,0,1,0
160,2017-06-22 15:12:42,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594bfcde70709600281a12b8,2017-06-22 13:22:38,vetting,2,"vetting, planning, editing, sourcing, writing",8,13,9,2,4,2,0,1,0,0,0,1
163,2017-06-22 15:12:07,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594bfcde70709600281a12b8,2017-06-22 13:22:38,vetting,1,"vetting, planning, editing, sourcing, writing",7,13,9,2,4,2,0,1,0,0,1,0
166,2017-06-22 15:06:54,62060850630c7afe54fd59151413d237,4.82,4.82,Accepted Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",6,15,7,1,3,3,0,0,0,1,0,0
167,2017-06-22 15:06:50,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",7,16,7,0,4,3,0,0,0,0,1,0
168,2017-06-22 15:06:50,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",7,16,7,0,4,3,0,0,0,0,0,1
169,2017-06-22 15:06:15,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",6,16,7,0,4,3,0,0,0,0,1,0
170,2017-06-22 15:05:05,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,2,"vetting, planning, editing, sourcing, writing",6,16,6,0,3,3,0,0,0,0,0,1
171,2017-06-22 15:04:30,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,2,"vetting, planning, editing, sourcing, writing",6,16,6,0,3,3,0,0,0,0,1,0
172,2017-06-22 15:04:30,62060850630c7afe54fd59151413d237,4.82,4.82,Declined Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,2,"vetting, planning, editing, sourcing, writing",6,16,6,0,3,3,0,0,0,0,0,1
173,2017-06-22 15:03:55,62060850630c7afe54fd59151413d237,4.82,4.82,Assigned Job,594c0645b99a200028ff12fe,2017-06-22 14:02:45,vetting,1,"vetting, planning, editing, sourcing, writing",5,16,6,0,3,3,0,0,0,0,1,0

In [48]:
# sort values in table by time the request created
df.sort_values('Request created at', inplace = True)

In [49]:
# create a primary key per record
df['record'] = range(1, len(df) + 1)

In [50]:
df.head()

,Event occurred at,Analyst,Quality score (sourcing),Quality score (writing),Action,Request,Request created at,Job,Wait time (min),Waiting for,Analysts available,Analysts occupied,Total jobs available,Review jobs available,Vetting jobs available,Planning jobs available,Editing jobs available,Sourcing jobs available,Writing jobs available,Accepted Job,Assigned Job,Declined Job,record
697,2017-06-21 21:50:31,a09c8906073b4c0b75e3100b857b982a,5.0,5.0,Accepted Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,1,"review, planning, editing, sourcing, writing",1,21,13,6,1,6,0,0,0,1,0,0,1
718,2017-06-21 21:26:17,d8e25a290ea51352bf9100a99c475f6d,5.0,5.0,Assigned Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,1,review,4,21,8,5,1,0,0,1,1,0,1,0,2
713,2017-06-21 21:27:19,d8e25a290ea51352bf9100a99c475f6d,5.0,5.0,Accepted Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,2,review,1,22,6,5,1,0,0,0,0,1,0,0,3
714,2017-06-21 21:26:52,d8e25a290ea51352bf9100a99c475f6d,5.0,5.0,Assigned Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,2,review,2,22,7,6,1,0,0,0,0,0,1,0,4
715,2017-06-21 21:26:52,d8e25a290ea51352bf9100a99c475f6d,5.0,5.0,Declined Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,2,review,2,22,7,6,1,0,0,0,0,0,0,1,5

In [51]:
# save cleaned csv to a file
df.to_csv (r'clean_assignment_log.csv', index = False, header=True)

### Part 2: Data modeling 
#### Assuming we are starting with the data set from Part 1 as our raw data table, how would you model this data in a data warehouse for analytical purposes? What tables would you create? What kinds of questions do you imagine business users would want to ask of this data, and how would they express them in your data model? Please use whatever tools you are comfortable with to answer this question and whatever flavor of SQL you are most familiar with. A github repo or gist is preferred.

In [120]:
# import csv
clean_df = pd.read_csv('clean_assignment_log.csv')

In [121]:
# connect to database
conn = sqlite3.connect(':memory:')

# create cursor object
cur = conn.cursor()

In [122]:
# write records stored in the dataframe to SQL database
df = pd.read_csv('clean_assignment_log.csv')
df.to_sql('assignment_log', con = conn, if_exists='append', index=False)

In [123]:
cur.execute('''SELECT  record,
                       Analyst AS analyst, 
                      "Quality score (sourcing)" AS quality_score_sourcing,
                      "Quality score (writing)" AS quality_score_writing, 
                      "Assigned Job" AS assigned_job,
                      "Accepted Job" AS accepted_job ,
                      "Declined Job" AS declined_job,
                       Action AS action,
                       Request AS request,
                      "Request created at" AS request_created_at,
                       Job AS job,
                      "Event occurred at" AS event_occured_at,
                      "Wait time (min)" AS wait_time_min, 
                      "Waiting for" AS waiting_for, 
                      "Analysts available" AS analysts_available,
                      "Analysts occupied" AS analysts_occupied, 
                      "Total jobs available" AS total_jobs_available, 
                      "Review jobs available" AS review_jobs_available,
                      "Vetting jobs available" AS vetting_jobs_avaiable, 
                      "Planning jobs available" AS planning_jobs_available,
                      "Editing jobs available" AS editing_jobs_available, 
                      "Sourcing jobs available" AS sourcing_jobs_available,
                      "Writing jobs available" AS writing_jobs_available
                       
                FROM assignment_log;''')               # sql query
assign_df = pd.DataFrame(cur.fetchall())               # create dataframe from sql query
assign_df.columns = [x[0] for x in cur.description]    # labels dataframe columns
assign_df.head()                                              # view dataframe

,record,analyst,quality_score_sourcing,quality_score_writing,assigned_job,accepted_job,declined_job,action,request,request_created_at,job,event_occured_at,wait_time_min,waiting_for,analysts_available,analysts_occupied,total_jobs_available,review_jobs_available,vetting_jobs_avaiable,planning_jobs_available,editing_jobs_available,sourcing_jobs_available,writing_jobs_available
0,1,a09c8906073b4c0b75e3100b857b982a,5.0,5.0,0,1,0,Accepted Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:50:31,1,"review, planning, editing, sourcing, writing",1,21,13,6,1,6,0,0,0
1,2,d8e25a290ea51352bf9100a99c475f6d,5.0,5.0,1,0,0,Assigned Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:26:17,1,review,4,21,8,5,1,0,0,1,1
2,3,d8e25a290ea51352bf9100a99c475f6d,5.0,5.0,0,1,0,Accepted Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:27:19,2,review,1,22,6,5,1,0,0,0,0
3,4,d8e25a290ea51352bf9100a99c475f6d,5.0,5.0,1,0,0,Assigned Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:26:52,2,review,2,22,7,6,1,0,0,0,0
4,5,d8e25a290ea51352bf9100a99c475f6d,5.0,5.0,0,0,1,Declined Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:26:52,2,review,2,22,7,6,1,0,0,0,0

In [124]:
# save analyst csv to a file
assign_df.to_csv(r'master_table.csv', index = None, header=True)

In [125]:
assign_df.head(1)

,record,analyst,quality_score_sourcing,quality_score_writing,assigned_job,accepted_job,declined_job,action,request,request_created_at,job,event_occured_at,wait_time_min,waiting_for,analysts_available,analysts_occupied,total_jobs_available,review_jobs_available,vetting_jobs_avaiable,planning_jobs_available,editing_jobs_available,sourcing_jobs_available,writing_jobs_available
0,1,a09c8906073b4c0b75e3100b857b982a,5.0,5.0,0,1,0,Accepted Job,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:50:31,1,"review, planning, editing, sourcing, writing",1,21,13,6,1,6,0,0,0

In [126]:
# write records stored in the dataframe to SQL database
df = pd.read_csv('master_table.csv')
df.to_sql('master_table', con = conn, if_exists='append', index=None)

#### Create Analyst Metric Table

In [127]:
# create SQL database for analysts

cur.execute('''SELECT record,
                      analyst, 
                      quality_score_sourcing, 
                      quality_score_writing	,
                      assigned_job,
                      accepted_job,
                      declined_job
               FROM master_table
               ORDER BY record''')                        # sql query
analyst_rank = pd.DataFrame(cur.fetchall())               # create dataframe from sql query
analyst_rank.columns = [x[0] for x in cur.description]    # labels dataframe columns
analyst_rank                                              # view dataframe

,record,analyst,quality_score_sourcing,quality_score_writing,assigned_job,accepted_job,declined_job
0,1,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
1,2,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,1,0,0
2,3,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,0,1,0
3,4,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,1,0,0
4,5,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,0,0,1
5,6,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
6,7,642782c690c8d963c487300a4751e220,4.97,4.97,0,1,0
7,8,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
8,9,b599bfb42906772db81ac90137fc1916,0.00,0.00,0,1,0
9,10,e817dd4305458b293cbeb3015da99565,4.55,4.55,0,1,0
10,11,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,0,1,0
11,12,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,1,0,0
12,13,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
13,14,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
14,15,e817dd4305458b293cbeb3015da99565,4.55,4.55,1,0,0
15,16,b599bfb42906772db81ac90137fc1916,0.00,0.00,1,0,0
16,17,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
17,18,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
18,19,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,0,1,0
19,20,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,1,0,0
20,21,39012c98c8fb80752d2bbcc3dc285230,4.75,4.75,0,1,0
21,22,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
22,23,39012c98c8fb80752d2bbcc3dc285230,4.75,4.75,1,0,0
23,24,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
24,25,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
25,26,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
26,27,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
27,28,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,0,1,0
28,29,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,1,0,0
29,30,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,0,1,0
30,31,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,1,0,0
31,32,de71db592b02c988670ca3d301a02568,5.00,5.00,1,0,0
32,33,642782c690c8d963c487300a4751e220,4.97,4.97,0,1,0
33,34,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
34,35,b692db6843c42f5ce686fcdfda4e0b62,0.00,0.00,1,0,0
35,36,b692db6843c42f5ce686fcdfda4e0b62,0.00,0.00,0,1,0
36,37,de71db592b02c988670ca3d301a02568,5.00,5.00,0,1,0
37,38,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
38,39,632a6492e9ff20cc4a442245836424e5,4.17,4.17,1,0,0
39,40,39012c98c8fb80752d2bbcc3dc285230,4.75,4.75,1,0,0
40,41,39012c98c8fb80752d2bbcc3dc285230,4.75,4.75,0,1,0
41,42,710dbda77cade1eced9c735c08e6e38d,5.00,5.00,0,1,0
42,43,710dbda77cade1eced9c735c08e6e38d,5.00,5.00,1,0,0
43,44,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,0,1,0
44,45,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,1,0,0
45,46,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,0,1,0
46,47,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,1,0,0
47,48,642782c690c8d963c487300a4751e220,4.97,4.97,0,1,0
48,49,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,0,1,0
49,50,39012c98c8fb80752d2bbcc3dc285230,4.75,4.75,1,0,0
50,51,39012c98c8fb80752d2bbcc3dc285230,4.75,4.75,0,1,0
51,52,d74c4a7423dd3ee0a78de5481c364823,4.65,4.65,1,0,0
52,53,d74c4a7423dd3ee0a78de5481c364823,4.65,4.65,0,1,0
53,54,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
54,55,632a6492e9ff20cc4a442245836424e5,4.17,4.17,0,1,0
55,56,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,1,0,0
56,57,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,0,1,0
57,58,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,1,0,0
58,59,39012c98c8fb80752d2bbcc3dc285230,4.75,4.75,0,1,0
59,60,39012c98c8fb80752d2bbcc3dc285230,4.75,4.75,1,0,0
60,61,c033808b89b50e6f550caf266470f090,4.90,4.90,1,0,0
61,62,c033808b89b50e6f550caf266470f090,4.90,4.90,0,1,0
62,63,dddcdea13df8232803957a5d9c847aae,4.31,4.31,1,0,0
63,64,dddcdea13df8232803957a5d9c847aae,4.31,4.31,0,1,0
64,65,dddcdea13df8232803957a5d9c847aae,4.31,4.31,1,0,0
65,66,dddcdea13df8232803957a5d9c847aae,4.31,4.31,0,0,1
66,67,482e9b14d8d59b748320f89074362746,4.55,4.55,0,1,0
67,68,482e9b14d8d59b748320f89074362746,4.55,4.55,1,0,0
68,69,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
69,70,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
70,71,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
71,72,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
72,73,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,1,0,0
73,74,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
74,75,008fa95f5c94985e2d44047aeac31655,4.69,4.69,0,1,0
75,76,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
76,77,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,0,1,0
77,78,008fa95f5c94985e2d44047aeac31655,4.69,4.69,1,0,0
78,79,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
79,80,008fa95f5c94985e2d44047aeac31655,4.69,4.69,1,0,0
80,81,008fa95f5c94985e2d44047aeac31655,4.69,4.69,0,1,0
81,82,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
82,83,008fa95f5c94985e2d44047aeac31655,4.69,4.69,0,1,0
83,84,008fa95f5c94985e2d44047aeac31655,4.69,4.69,1,0,0
84,85,008fa95f5c94985e2d44047aeac31655,4.69,4.69,0,1,0
85,86,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
86,87,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
87,88,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
88,89,2d0f64a208f69a70ec415cfccb59cc24,3.92,3.92,0,1,0
89,90,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,0,1,0
90,91,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,0,1,0
91,92,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,0,1,0
92,93,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
93,94,2d0f64a208f69a70ec415cfccb59cc24,3.92,3.92,1,0,0
94,95,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,1,0,0
95,96,766d3435eda76c4de9f034b8f97a0602,3.50,3.50,0,1,0
96,97,482e9b14d8d59b748320f89074362746,4.55,4.55,0,1,0
97,98,2d0f64a208f69a70ec415cfccb59cc24,3.85,3.85,0,1,0
98,99,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,0,1,0
99,100,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,1,0,0
100,101,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,0,1,0
101,102,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,0,1,0
102,103,766d3435eda76c4de9f034b8f97a0602,3.50,3.50,1,0,0
103,104,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,1,0,0
104,105,caf77e4ba6154e998b352cc92c685f80,4.83,4.83,1,0,0
105,106,2d0f64a208f69a70ec415cfccb59cc24,3.85,3.85,1,0,0
106,107,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
107,108,642782c690c8d963c487300a4751e220,4.97,4.97,0,0,1
108,109,0c2680433387fb4cf51a3546296f8422,4.48,4.48,1,0,0
109,110,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
110,111,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,1,0,0
111,112,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,0,0,1
112,113,642782c690c8d963c487300a4751e220,4.97,4.97,0,0,1
113,114,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,1,0,0
114,115,0c2680433387fb4cf51a3546296f8422,4.48,4.48,0,1,0
115,116,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,0,1,0
116,117,482e9b14d8d59b748320f89074362746,4.55,4.55,1,0,0
117,118,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,1,0,0
118,119,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
119,120,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
120,121,57ef46a92ecee8e187f4d450e92651ea,4.81,4.81,1,0,0
121,122,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,0,1,0
122,123,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,1,0,0
123,124,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,0,0,1
124,125,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,1,0,0
125,126,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,0,0,1
126,127,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,1,0,0
127,128,57ef46a92ecee8e187f4d450e92651ea,4.81,4.81,0,1,0
128,129,77b8ab28b9e95edb3a69ca7a6d352ec8,0.00,0.00,0,1,0
129,130,98de7e62209a07eee6ec8dc984911042,0.00,0.00,0,1,0
130,131,caf77e4ba6154e998b352cc92c685f80,4.83,4.83,1,0,0
131,132,77b8ab28b9e95edb3a69ca7a6d352ec8,0.00,0.00,1,0,0
132,133,2df8ce7d317c7d89dfa95be7695d2de0,0.00,0.00,1,0,0
133,134,2df8ce7d317c7d89dfa95be7695d2de0,0.00,0.00,0,1,0
134,135,5233d783ae5bf0483cf49549cbc594f8,0.00,0.00,1,0,0
135,136,5233d783ae5bf0483cf49549cbc594f8,0.00,0.00,0,1,0
136,137,1f8d8b08a994331e419d24293ce9e7b0,0.00,0.00,1,0,0
137,138,1f8d8b08a994331e419d24293ce9e7b0,0.00,0.00,0,0,1
138,139,1f8d8b08a994331e419d24293ce9e7b0,0.00,0.00,1,0,0
139,140,1f8d8b08a994331e419d24293ce9e7b0,0.00,0.00,0,0,1
140,141,a29fe6d26c1a49ff4a3c876eaee0a1af,0.00,0.00,1,0,0
141,142,a29fe6d26c1a49ff4a3c876eaee0a1af,0.00,0.00,0,1,0
142,143,a29fe6d26c1a49ff4a3c876eaee0a1af,0.00,0.00,0,1,0
143,144,a29fe6d26c1a49ff4a3c876eaee0a1af,0.00,0.00,0,1,0
144,145,98de7e62209a07eee6ec8dc984911042,0.00,0.00,1,0,0
145,146,642782c690c8d963c487300a4751e220,4.97,4.97,0,1,0
146,147,caf77e4ba6154e998b352cc92c685f80,4.83,4.83,0,1,0
147,148,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
148,149,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
149,150,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
150,151,ea5354c723ba83f2c412c238b133e84a,0.00,0.00,1,0,0
151,152,d9837e646a15a4fdd823531178b2d62e,0.00,0.00,0,0,1
152,153,d9837e646a15a4fdd823531178b2d62e,0.00,0.00,1,0,0
153,154,d9837e646a15a4fdd823531178b2d62e,0.00,0.00,0,1,0
154,155,0e9802516f8a79dd0d45211dd4ee74af,4.40,4.40,0,1,0
155,156,caf77e4ba6154e998b352cc92c685f80,4.83,4.83,0,1,0
156,157,caf77e4ba6154e998b352cc92c685f80,4.83,4.83,1,0,0
157,158,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,1,0,0
158,159,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,0,0,1
159,160,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,1,0,0
160,161,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,0,0,1
161,162,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,1,0,0
162,163,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
163,164,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,0,0,1
164,165,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
165,166,482e9b14d8d59b748320f89074362746,4.55,4.55,0,1,0
166,167,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,1,0,0
167,168,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,0,0,1
168,169,482e9b14d8d59b748320f89074362746,4.55,4.55,1,0,0
169,170,dddcdea13df8232803957a5d9c847aae,4.31,4.31,0,0,1
170,171,dddcdea13df8232803957a5d9c847aae,4.31,4.31,1,0,0
171,172,d9837e646a15a4fdd823531178b2d62e,0.00,0.00,1,0,0
172,173,d9837e646a15a4fdd823531178b2d62e,0.00,0.00,0,0,1
173,174,dddcdea13df8232803957a5d9c847aae,4.31,4.31,1,0,0
174,175,0e9802516f8a79dd0d45211dd4ee74af,4.40,4.40,1,0,0
175,176,d9837e646a15a4fdd823531178b2d62e,0.00,0.00,1,0,0
176,177,ea5354c723ba83f2c412c238b133e84a,0.00,0.00,0,1,0
177,178,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,0,1,0
178,179,795930bc4ed320777ad76b46da2ed66d,4.80,4.80,1,0,0
179,180,d6eaa4eeb52b4d62ec78299454763870,5.00,5.00,0,1,0
180,181,d6eaa4eeb52b4d62ec78299454763870,5.00,5.00,1,0,0
181,182,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
182,183,0c2680433387fb4cf51a3546296f8422,4.48,4.48,0,1,0
183,184,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
184,185,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,1,0,0
185,186,e8a2b0b2e2234a89dc52dd8a3e0f79e6,4.80,4.80,1,0,0
186,187,c033808b89b50e6f550caf266470f090,4.90,4.90,0,1,0
187,188,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,0,0,1
188,189,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,1,0,0
189,190,c9401f82fdedf3cd080a03bafe3447c7,0.00,0.00,0,0,1
190,191,c033808b89b50e6f550caf266470f090,4.90,4.90,1,0,0
191,192,e8a2b0b2e2234a89dc52dd8a3e0f79e6,4.80,4.80,0,1,0
192,193,0c2680433387fb4cf51a3546296f8422,4.48,4.48,1,0,0
193,194,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
194,195,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
195,196,32553d485988e2ddcf0f701c60754f2d,4.87,4.87,1,0,0
196,197,32553d485988e2ddcf0f701c60754f2d,4.87,4.87,0,1,0
197,198,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
198,199,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
199,200,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
200,201,0e9802516f8a79dd0d45211dd4ee74af,4.40,4.40,1,0,0
201,202,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
202,203,0e9802516f8a79dd0d45211dd4ee74af,4.40,4.40,0,1,0
203,204,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
204,205,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,1,0,0
205,206,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,0,0,1
206,207,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,0,1
207,208,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
208,209,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,0,0,1
209,210,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
210,211,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,0,1
211,212,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
212,213,732e4a29b2e318bce3c1e923276ddf51,5.00,5.00,1,0,0
213,214,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
214,215,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
215,216,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,0,1,0
216,217,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,1,0,0
217,218,632a6492e9ff20cc4a442245836424e5,4.17,4.17,0,0,1
218,219,632a6492e9ff20cc4a442245836424e5,4.17,4.17,0,1,0
219,220,632a6492e9ff20cc4a442245836424e5,4.17,4.17,1,0,0
220,221,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,1,0,0
221,222,632a6492e9ff20cc4a442245836424e5,4.17,4.17,1,0,0
222,223,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
223,224,d6eaa4eeb52b4d62ec78299454763870,5.00,5.00,1,0,0
224,225,d6eaa4eeb52b4d62ec78299454763870,5.00,5.00,0,0,1
225,226,d6eaa4eeb52b4d62ec78299454763870,5.00,5.00,1,0,0
226,227,caf77e4ba6154e998b352cc92c685f80,4.83,4.83,1,0,0
227,228,caf77e4ba6154e998b352cc92c685f80,4.83,4.83,0,1,0
228,229,5078cc506436a8668c0b6de594842fcf,4.20,4.20,1,0,0
229,230,206de922289a1f9f5ee250fc71308628,3.17,3.17,1,0,0
230,231,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
231,232,206de922289a1f9f5ee250fc71308628,3.17,3.17,0,1,0
232,233,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
233,234,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
234,235,206de922289a1f9f5ee250fc71308628,3.17,3.17,0,1,0
235,236,d9837e646a15a4fdd823531178b2d62e,0.00,0.00,0,0,1
236,237,0c2680433387fb4cf51a3546296f8422,4.48,4.48,0,1,0
237,238,206de922289a1f9f5ee250fc71308628,3.14,3.14,0,1,0
238,239,206de922289a1f9f5ee250fc71308628,3.14,3.14,1,0,0
239,240,0c2680433387fb4cf51a3546296f8422,4.48,4.48,1,0,0
240,241,d9837e646a15a4fdd823531178b2d62e,0.00,0.00,1,0,0
241,242,39b71201151caf98fd10afce50cfc83e,4.85,4.85,0,1,0
242,243,bcd8d747b5af397febc04228293f747f,4.67,4.67,1,0,0
243,244,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
244,245,4bb6e496f0c92286dee7eed7038ddd9d,4.89,4.89,1,0,0
245,246,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
246,247,4bb6e496f0c92286dee7eed7038ddd9d,4.89,4.89,0,1,0
247,248,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
248,249,bcd8d747b5af397febc04228293f747f,4.67,4.67,0,1,0
249,250,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,0,1,0
250,251,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
251,252,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,1,0,0
252,253,98de7e62209a07eee6ec8dc984911042,0.00,0.00,1,0,0
253,254,98de7e62209a07eee6ec8dc984911042,0.00,0.00,0,1,0
254,255,39b71201151caf98fd10afce50cfc83e,4.85,4.85,1,0,0
255,256,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
256,257,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
257,258,0e9802516f8a79dd0d45211dd4ee74af,4.40,4.40,1,0,0
258,259,766d3435eda76c4de9f034b8f97a0602,3.50,3.50,1,0,0
259,260,32553d485988e2ddcf0f701c60754f2d,4.88,4.88,1,0,0
260,261,39b71201151caf98fd10afce50cfc83e,4.85,4.85,0,1,0
261,262,ef7e6e9fd91d89f2e31b26b9feaec787,0.00,0.00,1,0,0
262,263,39b71201151caf98fd10afce50cfc83e,4.85,4.85,1,0,0
263,264,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
264,265,642782c690c8d963c487300a4751e220,4.97,4.97,0,1,0
265,266,0e9802516f8a79dd0d45211dd4ee74af,4.40,4.40,0,1,0
266,267,32553d485988e2ddcf0f701c60754f2d,4.88,4.88,0,1,0
267,268,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
268,269,f3b93c5ae97215ae15fa63b5f0fc30e1,4.83,4.83,0,1,0
269,270,ef7e6e9fd91d89f2e31b26b9feaec787,0.00,0.00,0,1,0
270,271,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
271,272,642782c690c8d963c487300a4751e220,4.97,4.97,0,1,0
272,273,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
273,274,f3b93c5ae97215ae15fa63b5f0fc30e1,4.83,4.83,1,0,0
274,275,642782c690c8d963c487300a4751e220,4.97,4.97,0,0,1
275,276,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
276,277,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
277,278,482e9b14d8d59b748320f89074362746,4.55,4.55,0,1,0
278,279,482e9b14d8d59b748320f89074362746,4.55,4.55,1,0,0
279,280,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
280,281,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,1,0,0
281,282,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,0,1,0
282,283,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,1,0,0
283,284,6c6bd5e891c4015e534773dfb19f29b0,5.00,5.00,0,1,0
284,285,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
285,286,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
286,287,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,0,1,0
287,288,6c6bd5e891c4015e534773dfb19f29b0,5.00,5.00,1,0,0
288,289,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,0,1,0
289,290,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,1,0,0
290,291,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,1,0,0
291,292,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,1,0,0
292,293,d6eaa4eeb52b4d62ec78299454763870,5.00,5.00,1,0,0
293,294,d6eaa4eeb52b4d62ec78299454763870,5.00,5.00,0,1,0
294,295,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,1,0,0
295,296,0e9802516f8a79dd0d45211dd4ee74af,4.50,4.50,0,1,0
296,297,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,1,0,0
297,298,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
298,299,642782c690c8d963c487300a4751e220,4.97,4.97,0,1,0
299,300,caf77e4ba6154e998b352cc92c685f80,4.83,4.83,0,1,0
300,301,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,1,0,0
301,302,caf77e4ba6154e998b352cc92c685f80,4.83,4.83,1,0,0
302,303,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,0,1,0
303,304,7e22ad15724c44543d1d4bcafd10c812,5.00,5.00,0,1,0
304,305,9fa24ddce8fd9d1526d9d7451304fc74,4.89,4.89,0,1,0
305,306,4bb6e496f0c92286dee7eed7038ddd9d,4.89,4.89,0,1,0
306,307,d8e25a290ea51352bf9100a99c475f6d,5.00,5.00,0,1,0
307,308,4bb6e496f0c92286dee7eed7038ddd9d,4.89,4.89,1,0,0
308,309,85c7b78e76b5232cd38014ea4cdc8f56,4.50,4.50,0,1,0
309,310,85c7b78e76b5232cd38014ea4cdc8f56,4.50,4.50,1,0,0
310,311,0e9802516f8a79dd0d45211dd4ee74af,4.40,4.40,0,1,0
311,312,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,1,0,0
312,313,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,0,0,1
313,314,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,1,0,0
314,315,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,0,0,1
315,316,0e9802516f8a79dd0d45211dd4ee74af,4.40,4.40,1,0,0
316,317,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,1,0,0
317,318,206de922289a1f9f5ee250fc71308628,3.17,3.17,1,0,0
318,319,206de922289a1f9f5ee250fc71308628,3.17,3.17,0,1,0
319,320,5238b0785b5576f5ffe665136df9244f,0.00,0.00,1,0,0
320,321,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,1,0,0
321,322,98de7e62209a07eee6ec8dc984911042,0.00,0.00,0,1,0
322,323,98de7e62209a07eee6ec8dc984911042,0.00,0.00,1,0,0
323,324,8258591d197a3936de0f7ee021ab9e0e,0.00,0.00,1,0,0
324,325,5238b0785b5576f5ffe665136df9244f,0.00,0.00,0,0,1
325,326,9fcbc63ff4c8bea5cea4efad782c87cf,5.00,5.00,0,1,0
326,327,a09c8906073b4c0b75e3100b857b982a,5.00,5.00,0,1,0
327,328,5238b0785b5576f5ffe665136df9244f,0.00,0.00,1,0,0
328,329,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,0,0,1
329,330,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,1,0,0
330,331,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,1,0,0
331,332,5238b0785b5576f5ffe665136df9244f,0.00,0.00,0,0,1
332,333,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,0,1,0
333,334,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,0,1,0
334,335,d5aa695af013ee5baaeeccfb7ca50c80,4.70,4.70,0,1,0
335,336,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,1,0,0
336,337,85c7b78e76b5232cd38014ea4cdc8f56,4.50,4.50,0,0,1
337,338,85c7b78e76b5232cd38014ea4cdc8f56,4.50,4.50,1,0,0
338,339,85c7b78e76b5232cd38014ea4cdc8f56,4.50,4.50,0,0,1
339,340,85c7b78e76b5232cd38014ea4cdc8f56,4.50,4.50,1,0,0
340,341,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,1,0,0
341,342,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,0,1,0
342,343,6c6bd5e891c4015e534773dfb19f29b0,5.00,5.00,0,1,0
343,344,6c6bd5e891c4015e534773dfb19f29b0,5.00,5.00,0,1,0
344,345,6c6bd5e891c4015e534773dfb19f29b0,5.00,5.00,1,0,0
345,346,c2dcc0b178176d7e6b185df9bd1cb4f2,0.00,0.00,0,1,0
346,347,0c2680433387fb4cf51a3546296f8422,4.48,4.48,1,0,0
347,348,0c2680433387fb4cf51a3546296f8422,4.48,4.48,0,1,0
348,349,39b71201151caf98fd10afce50cfc83e,4.85,4.85,0,1,0
349,350,642782c690c8d963c487300a4751e220,4.97,4.97,1,0,0
350,351,642782c690c8d963c487300a4751e220,4.97,4.97,0,1,0
351,352,3a29165b73c047e745934c2cbbfaac1b,4.63,4.63,1,0,0

In [128]:
# save analyst csv to a file
analyst_rank.to_csv (r'analyst_table.csv', index = None, header=True)

In [129]:
# write records stored in the dataframe to SQL database
df = pd.read_csv('analyst_table.csv')
df.to_sql('analyst_table', con = conn, if_exists='append', index=False)

In [131]:
# SQL query to evaluate analyst metrics (sourcing and writing scores,
# and jobs assigned/accepted/declined) 

cur.execute('''SELECT analyst, 
                      AVG(quality_score_sourcing) AS average_sourcing_score, 
                      AVG(quality_score_writing) AS average_writing_score,
                      SUM(assigned_job) AS assigned_job,
                      SUM(accepted_job) AS accepted_job,
                      SUM(declined_job) AS declined_job
               FROM analyst_table
               GROUP BY analyst
               ORDER BY 6 DESC''')                             # sql query
analyst_rank = pd.DataFrame(cur.fetchall())               # create dataframe from sql query
analyst_rank.columns = [x[0] for x in cur.description]    # labels dataframe columns
analyst_rank                                              # view dataframe

,analyst,average_sourcing_score,average_writing_score,assigned_job,accepted_job,declined_job
0,62060850630c7afe54fd59151413d237,4.820000,4.820000,23,11,12
1,85c7b78e76b5232cd38014ea4cdc8f56,4.455882,4.455882,16,8,10
2,a09c8906073b4c0b75e3100b857b982a,5.000000,5.000000,36,28,8
3,c9401f82fdedf3cd080a03bafe3447c7,0.000000,0.000000,9,1,7
4,dddcdea13df8232803957a5d9c847aae,4.310000,4.310000,7,2,4
5,c2d7982e24aadeea8921108d0eb756d8,4.450000,4.450000,4,0,4
6,8258591d197a3936de0f7ee021ab9e0e,0.000000,0.000000,9,4,4
7,642782c690c8d963c487300a4751e220,4.970000,4.970000,21,17,4
8,0c2680433387fb4cf51a3546296f8422,4.497778,4.497778,9,5,4
9,00360b3f177375b01b795a4be7b4686c,0.000000,0.000000,4,0,4
10,d9837e646a15a4fdd823531178b2d62e,0.000000,0.000000,4,1,3
11,f7f7591403c6c431053920223069550a,5.000000,5.000000,7,5,2
12,caf77e4ba6154e998b352cc92c685f80,4.830000,4.830000,8,5,2
13,9fcbc63ff4c8bea5cea4efad782c87cf,5.000000,5.000000,20,18,2
14,9fa24ddce8fd9d1526d9d7451304fc74,4.890000,4.890000,8,7,2
15,94959cf2d0b592d0fa1e5e9cf760a1c7,5.000000,5.000000,13,11,2
16,7e22ad15724c44543d1d4bcafd10c812,5.000000,5.000000,14,12,2
17,795930bc4ed320777ad76b46da2ed66d,4.800000,4.800000,6,6,2
18,732e4a29b2e318bce3c1e923276ddf51,5.000000,5.000000,24,16,2
19,6b19235b9269df81b6da879771bf40bc,0.000000,0.000000,4,2,2
20,608b40f66ef114c6d9f5c95021290f69,0.000000,0.000000,2,0,2
21,5238b0785b5576f5ffe665136df9244f,0.000000,0.000000,2,0,2
22,1f8d8b08a994331e419d24293ce9e7b0,0.000000,0.000000,2,0,2
23,d8e25a290ea51352bf9100a99c475f6d,5.000000,5.000000,10,8,1
24,d6eaa4eeb52b4d62ec78299454763870,4.946667,4.946667,8,6,1
25,c2dcc0b178176d7e6b185df9bd1cb4f2,0.000000,0.000000,8,7,1
26,98de7e62209a07eee6ec8dc984911042,0.000000,0.000000,5,4,1
27,95130c93e28b36bcb5ecd7e747b4d5c2,0.000000,0.000000,1,0,1
28,632a6492e9ff20cc4a442245836424e5,4.170000,4.170000,3,2,1
29,0e9802516f8a79dd0d45211dd4ee74af,4.466667,4.466667,12,11,1
30,f3b93c5ae97215ae15fa63b5f0fc30e1,4.830000,4.830000,1,1,0
31,ef7e6e9fd91d89f2e31b26b9feaec787,0.000000,0.000000,1,1,0
32,ea5354c723ba83f2c412c238b133e84a,0.000000,0.000000,1,1,0
33,ea452a7456e38887ca8b98f4e131d224,5.000000,5.000000,1,1,0
34,e9468b4c33f88d6937c4ad2bea8bbc2f,5.000000,5.000000,1,1,0
35,e8a2b0b2e2234a89dc52dd8a3e0f79e6,4.800000,4.800000,2,2,0
36,e817dd4305458b293cbeb3015da99565,4.550000,4.550000,1,1,0
37,e2333b2dc03032f12c8526e45243f0c1,0.000000,0.000000,1,1,0
38,dee1febfdeb9c90a41759cb330c72fd4,4.540000,4.540000,3,3,0
39,de71db592b02c988670ca3d301a02568,5.000000,5.000000,2,2,0
40,d74c4a7423dd3ee0a78de5481c364823,4.650000,4.650000,2,2,0
41,d5aa695af013ee5baaeeccfb7ca50c80,4.700000,4.700000,3,7,0
42,c033808b89b50e6f550caf266470f090,4.900000,4.900000,4,4,0
43,bcd8d747b5af397febc04228293f747f,4.670000,4.670000,1,1,0
44,b89eb67419465a9e2c9da08dae6023e2,0.000000,0.000000,2,2,0
45,b692db6843c42f5ce686fcdfda4e0b62,0.000000,0.000000,1,1,0
46,b599bfb42906772db81ac90137fc1916,0.000000,0.000000,2,2,0
47,a29fe6d26c1a49ff4a3c876eaee0a1af,0.000000,0.000000,1,3,0
48,9286ce84f2401fbd6635f7d768c3cad1,0.000000,0.000000,2,2,0
49,83f00c2268afaf459715f4c52e16dd23,4.430000,4.430000,1,1,0
50,77b8ab28b9e95edb3a69ca7a6d352ec8,0.000000,0.000000,2,2,0
51,766d3435eda76c4de9f034b8f97a0602,3.500000,3.500000,2,1,0
52,710dbda77cade1eced9c735c08e6e38d,5.000000,5.000000,7,7,0
53,6c6bd5e891c4015e534773dfb19f29b0,5.000000,5.000000,9,10,0
54,57ef46a92ecee8e187f4d450e92651ea,4.810000,4.810000,1,1,0
55,5233d783ae5bf0483cf49549cbc594f8,0.000000,0.000000,1,1,0
56,5078cc506436a8668c0b6de594842fcf,4.200000,4.200000,1,0,0
57,4bb6e496f0c92286dee7eed7038ddd9d,4.890000,4.890000,4,4,0
58,482e9b14d8d59b748320f89074362746,4.550000,4.550000,4,4,0
59,3a8a0b0323b02a707535fe7d65821de3,4.640000,4.640000,1,1,0
60,3a29165b73c047e745934c2cbbfaac1b,4.650000,4.650000,2,2,0
61,39b71201151caf98fd10afce50cfc83e,4.850000,4.850000,6,6,0
62,39012c98c8fb80752d2bbcc3dc285230,4.750000,4.750000,4,4,0
63,36ee9fc3bade4a4f71c2a6e5c2bd8862,0.000000,0.000000,1,3,0
64,32553d485988e2ddcf0f701c60754f2d,4.875000,4.875000,2,2,0
65,30ea4ac9222bfa53b3849df49d6f26f0,0.000000,0.000000,1,1,0
66,2df8ce7d317c7d89dfa95be7695d2de0,0.000000,0.000000,4,4,0
67,2d0f64a208f69a70ec415cfccb59cc24,3.885000,3.885000,2,2,0
68,206de922289a1f9f5ee250fc71308628,3.161429,3.161429,3,4,0
69,052066814364850e1a17a90d576dd904,4.200000,4.200000,1,2,0
70,008fa95f5c94985e2d44047aeac31655,4.690000,4.690000,3,4,0

#### Create Request Table

In [134]:
assign_df.columns

Index(['record', 'analyst', 'quality_score_sourcing', 'quality_score_writing',
       'assigned_job', 'accepted_job', 'declined_job', 'action', 'request',
       'request_created_at', 'job', 'event_occured_at', 'wait_time_min',
       'waiting_for', 'analysts_available', 'analysts_occupied',
       'total_jobs_available', 'review_jobs_available',
       'vetting_jobs_avaiable', 'planning_jobs_available',
       'editing_jobs_available', 'sourcing_jobs_available',
       'writing_jobs_available'],
      dtype='object')

In [136]:
# create SQL database for requests

cur.execute('''SELECT record,
                      request,
                      request_created_at, 
                      job, 
                      event_occured_at, 
                      wait_time_min,
                      waiting_for
               FROM master_table
               ORDER BY record''')                        # sql query
requests = pd.DataFrame(cur.fetchall())               # create dataframe from sql query
requests.columns = [x[0] for x in cur.description]    # labels dataframe columns
requests                                              # view dataframe

,record,request,request_created_at,job,event_occured_at,wait_time_min,waiting_for
0,1,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:50:31,1,"review, planning, editing, sourcing, writing"
1,2,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:26:17,1,review
2,3,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:27:19,2,review
3,4,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:26:52,2,review
4,5,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:26:52,2,review
5,6,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:50:30,1,"review, planning, editing, sourcing, writing"
6,7,59485c262e71030033104e3c,2017-06-19 19:20:06,review,2017-06-22 06:19:35,1,"review, vetting, editing, sourcing, writing"
7,8,59485c262e71030033104e3c,2017-06-19 19:20:06,review,2017-06-22 06:19:33,1,"review, vetting, editing, sourcing, writing"
8,9,59485c262e71030033104e3c,2017-06-19 19:20:06,sourcing,2017-06-21 21:26:19,1,sourcing
9,10,59485c262e71030033104e3c,2017-06-19 19:20:06,writing,2017-06-22 05:04:04,1,"sourcing, writing"
10,11,59485c262e71030033104e3c,2017-06-19 19:20:06,writing,2017-06-22 04:51:04,1,"sourcing, writing"
11,12,59485c262e71030033104e3c,2017-06-19 19:20:06,writing,2017-06-22 04:50:59,1,"sourcing, writing"
12,13,59485c262e71030033104e3c,2017-06-19 19:20:06,source review,2017-06-22 01:39:39,1,"review, planning, editing, sourcing, writing"
13,14,59485c262e71030033104e3c,2017-06-19 19:20:06,source review,2017-06-22 01:39:30,1,"review, planning, editing, sourcing, writing"
14,15,59485c262e71030033104e3c,2017-06-19 19:20:06,writing,2017-06-22 05:04:00,1,"sourcing, writing"
15,16,59485c262e71030033104e3c,2017-06-19 19:20:06,sourcing,2017-06-21 21:26:17,1,sourcing
16,17,59486e7af5874900429ce273,2017-06-19 20:38:18,review,2017-06-21 21:18:06,1,review
17,18,59486e7af5874900429ce273,2017-06-19 20:38:18,review,2017-06-21 21:18:10,1,review
18,19,5949462dd9ae5200633f9640,2017-06-20 11:58:37,editing,2017-06-21 22:03:13,5,editing
19,20,5949462dd9ae5200633f9640,2017-06-20 11:58:37,editing,2017-06-21 22:03:02,5,editing
20,21,5949462dd9ae5200633f9640,2017-06-20 11:58:37,review,2017-06-21 21:21:06,1,"review, editing, sourcing, writing"
21,22,5949462dd9ae5200633f9640,2017-06-20 11:58:37,review,2017-06-21 21:25:06,1,review
22,23,5949462dd9ae5200633f9640,2017-06-20 11:58:37,review,2017-06-21 21:21:01,1,"review, editing, sourcing, writing"
23,24,5949462dd9ae5200633f9640,2017-06-20 11:58:37,review,2017-06-21 21:25:09,1,review
24,25,59494c13d9ae5200633f9695,2017-06-20 12:23:47,review,2017-06-21 22:00:10,1,"review, planning, editing, sourcing, writing"
25,26,59494c13d9ae5200633f9695,2017-06-20 12:23:47,review,2017-06-21 22:00:07,1,"review, planning, editing, sourcing, writing"
26,27,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-22 05:46:09,1,"review, vetting, editing, sourcing, writing"
27,28,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-22 05:37:10,1,review
28,29,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-22 05:37:07,1,review
29,30,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,2017-06-22 02:05:27,1,writing
30,31,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,2017-06-22 02:05:22,1,writing
31,32,5949a81c4d1319005556396c,2017-06-20 18:56:28,editing,2017-06-22 13:16:17,1,"editing, writing"
32,33,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-22 05:46:13,1,"review, vetting, editing, sourcing, writing"
33,34,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,2017-06-22 05:53:43,1,"review, vetting, editing, sourcing, writing"
34,35,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,2017-06-21 23:01:59,1,sourcing
35,36,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,2017-06-21 23:02:01,1,sourcing
36,37,5949a81c4d1319005556396c,2017-06-20 18:56:28,editing,2017-06-22 13:16:28,1,"editing, writing"
37,38,5949a81c4d1319005556396c,2017-06-20 18:56:28,source review,2017-06-22 00:58:58,1,"review, planning, editing, sourcing, writing"
38,39,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,2017-06-22 06:01:39,1,writing
39,40,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-21 20:21:32,1,"review, editing, sourcing, writing"
40,41,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-21 20:21:39,1,"review, editing, sourcing, writing"
41,42,5949a81c4d1319005556396c,2017-06-20 18:56:28,editing,2017-06-22 12:46:09,1,editing
42,43,5949a81c4d1319005556396c,2017-06-20 18:56:28,editing,2017-06-22 12:46:02,1,editing
43,44,5949a81c4d1319005556396c,2017-06-20 18:56:28,editing,2017-06-22 12:38:43,54,editing
44,45,5949a81c4d1319005556396c,2017-06-20 18:56:28,editing,2017-06-22 12:38:26,53,editing
45,46,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-22 12:18:33,1,review
46,47,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-22 12:18:31,1,review
47,48,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,2017-06-22 05:53:46,1,"review, vetting, editing, sourcing, writing"
48,49,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-22 11:10:45,1,review
49,50,5949a81c4d1319005556396c,2017-06-20 18:56:28,source review,2017-06-21 21:11:41,1,"review, editing, sourcing, writing"
50,51,5949a81c4d1319005556396c,2017-06-20 18:56:28,source review,2017-06-21 21:11:47,1,"review, editing, sourcing, writing"
51,52,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,2017-06-21 21:21:01,1,"editing, sourcing"
52,53,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,2017-06-21 21:21:04,1,"editing, sourcing"
53,54,5949a81c4d1319005556396c,2017-06-20 18:56:28,source review,2017-06-22 00:59:00,1,"review, planning, editing, sourcing, writing"
54,55,5949a81c4d1319005556396c,2017-06-20 18:56:28,writing,2017-06-22 06:01:43,1,writing
55,56,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,2017-06-21 21:33:52,1,sourcing
56,57,5949a81c4d1319005556396c,2017-06-20 18:56:28,sourcing,2017-06-21 21:34:05,1,sourcing
57,58,5949a81c4d1319005556396c,2017-06-20 18:56:28,review,2017-06-22 11:10:42,1,review
58,59,5949bdb4fe2f5d005b4f4910,2017-06-20 20:28:36,review,2017-06-21 20:15:45,1,"review, editing, sourcing, writing"
59,60,5949bdb4fe2f5d005b4f4910,2017-06-20 20:28:36,review,2017-06-21 20:15:42,1,"review, editing, sourcing, writing"
60,61,5949bdbcfe2f5d005b4f4928,2017-06-20 20:28:44,editing,2017-06-21 20:25:04,1,editing
61,62,5949bdbcfe2f5d005b4f4928,2017-06-20 20:28:44,editing,2017-06-21 20:25:07,1,editing
62,63,5949e376f03c130028baa724,2017-06-20 23:09:42,writing,2017-06-21 21:33:17,2,"sourcing, writing"
63,64,5949e376f03c130028baa724,2017-06-20 23:09:42,writing,2017-06-21 21:35:02,1,"sourcing, writing"
64,65,5949e376f03c130028baa724,2017-06-20 23:09:42,writing,2017-06-21 21:34:59,1,"sourcing, writing"
65,66,5949e376f03c130028baa724,2017-06-20 23:09:42,writing,2017-06-21 21:33:52,2,"sourcing, writing"
66,67,5949e376f03c130028baa724,2017-06-20 23:09:42,writing,2017-06-21 21:26:19,1,"sourcing, writing"
67,68,5949e376f03c130028baa724,2017-06-20 23:09:42,writing,2017-06-21 21:26:17,1,"sourcing, writing"
68,69,594a4325499a400071d4cca4,2017-06-21 05:57:57,review,2017-06-21 22:04:15,1,review
69,70,594a4325499a400071d4cca4,2017-06-21 05:57:57,review,2017-06-21 22:04:10,1,review
70,71,594a536d220b450040dc0182,2017-06-21 07:07:25,review,2017-06-21 20:22:47,1,review
71,72,594a536d220b450040dc0182,2017-06-21 07:07:25,review,2017-06-21 20:22:44,1,review
72,73,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,writing,2017-06-21 21:07:01,1,"editing, sourcing, writing"
73,74,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-21 20:32:08,1,review
74,75,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 00:31:41,1,"review, editing, sourcing, writing"
75,76,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-21 20:32:04,1,review
76,77,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,writing,2017-06-21 21:07:13,1,"editing, sourcing, writing"
77,78,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 00:33:17,2,"review, editing, sourcing, writing"
78,79,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 01:18:51,1,"review, planning, editing, sourcing, writing"
79,80,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 00:23:56,1,"review, editing, sourcing, writing"
80,81,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 00:23:59,1,"review, editing, sourcing, writing"
81,82,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 01:18:49,1,"review, planning, editing, sourcing, writing"
82,83,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 00:33:22,2,"review, editing, sourcing, writing"
83,84,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 00:31:32,1,"review, editing, sourcing, writing"
84,85,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 00:31:38,1,"review, editing, sourcing, writing"
85,86,594a8f5664251c002831f4c5,2017-06-21 11:23:02,source review,2017-06-21 22:05:17,1,"review, planning, editing, sourcing, writing"
86,87,594a8f5664251c002831f4c5,2017-06-21 11:23:02,source review,2017-06-21 22:05:21,1,"review, planning, editing, sourcing, writing"
87,88,594a8f5664251c002831f4c5,2017-06-21 11:23:02,review,2017-06-22 03:01:35,1,"review, planning, editing, sourcing, writing"
88,89,594a8f5664251c002831f4c5,2017-06-21 11:23:02,writing,2017-06-21 22:10:33,4,writing
89,90,594a8f5664251c002831f4c5,2017-06-21 11:23:02,editing,2017-06-22 04:26:02,1,editing
90,91,594a8f5664251c002831f4c5,2017-06-21 11:23:02,editing,2017-06-22 04:26:01,1,editing
91,92,594a8f5664251c002831f4c5,2017-06-21 11:23:02,editing,2017-06-22 04:26:00,1,editing
92,93,594a8f5664251c002831f4c5,2017-06-21 11:23:02,review,2017-06-22 03:01:40,1,"review, planning, editing, sourcing, writing"
93,94,594a8f5664251c002831f4c5,2017-06-21 11:23:02,writing,2017-06-21 22:10:29,4,writing
94,95,594a8f5664251c002831f4c5,2017-06-21 11:23:02,editing,2017-06-22 04:25:56,1,editing
95,96,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 06:13:40,1,"sourcing, writing"
96,97,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-21 22:35:25,1,"sourcing, writing"
97,98,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 07:23:45,1,writing
98,99,594a8fd422b3c50028e71976,2017-06-21 11:25:08,review,2017-06-22 09:01:12,1,review
99,100,594a8fd422b3c50028e71976,2017-06-21 11:25:08,review,2017-06-22 09:05:15,1,review
100,101,594a8fd422b3c50028e71976,2017-06-21 11:25:08,review,2017-06-22 09:05:23,1,review
101,102,594a8fd422b3c50028e71976,2017-06-21 11:25:08,review,2017-06-22 09:05:24,1,review
102,103,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 06:13:34,1,"sourcing, writing"
103,104,594a8fd422b3c50028e71976,2017-06-21 11:25:08,review,2017-06-22 09:01:10,1,review
104,105,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 06:05:44,1,"planning, editing, sourcing, writing"
105,106,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 07:23:41,1,writing
106,107,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 05:42:42,1,"vetting, editing, sourcing, writing"
107,108,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 05:43:14,1,"vetting, editing"
108,109,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-21 22:36:33,1,"sourcing, writing"
109,110,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 05:42:07,1,"vetting, editing, sourcing, writing"
110,111,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 05:39:53,1,writing
111,112,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 05:39:53,1,writing
112,113,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 05:42:42,1,"vetting, editing, sourcing, writing"
113,114,594a8fd422b3c50028e71976,2017-06-21 11:25:08,source review,2017-06-21 22:06:59,1,"review, planning"
114,115,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-21 22:36:43,1,"sourcing, writing"
115,116,594a8fd422b3c50028e71976,2017-06-21 11:25:08,source review,2017-06-21 22:07:01,1,"review, planning"
116,117,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-21 22:35:23,1,"sourcing, writing"
117,118,594a8fd422b3c50028e71976,2017-06-21 11:25:08,writing,2017-06-22 05:39:18,1,writing
118,119,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 01:22:10,1,"review, planning, editing, sourcing, writing"
119,120,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 01:22:14,1,"review, planning, editing, sourcing, writing"
120,121,594a9ce6c864e200288e766b,2017-06-21 12:20:54,writing,2017-06-22 09:50:13,1,writing
121,122,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 09:25:49,1,"review, editing"
122,123,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 09:25:42,1,"review, editing"
123,124,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 09:24:32,12,review
124,125,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 09:23:56,12,review
125,126,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 09:23:56,12,review
126,127,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 09:23:21,11,review
127,128,594a9ce6c864e200288e766b,2017-06-21 12:20:54,writing,2017-06-22 09:50:15,1,writing
128,129,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 01:40:09,1,sourcing
129,130,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 08:03:26,1,sourcing
130,131,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 01:50:20,1,sourcing
131,132,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 01:40:05,1,sourcing
132,133,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 06:20:08,1,sourcing
133,134,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 06:20:10,1,sourcing
134,135,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 02:03:40,1,sourcing
135,136,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 02:03:43,1,sourcing
136,137,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 07:59:53,6,sourcing
137,138,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 08:00:28,7,sourcing
138,139,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 08:00:28,7,sourcing
139,140,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 08:01:03,7,sourcing
140,141,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 08:01:03,1,sourcing
141,142,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 08:01:20,1,sourcing
142,143,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 08:01:22,1,sourcing
143,144,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 08:01:25,1,sourcing
144,145,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 08:03:23,1,sourcing
145,146,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 06:03:29,1,"review, vetting, editing, sourcing, writing"
146,147,594a9ce6c864e200288e766b,2017-06-21 12:20:54,sourcing,2017-06-22 01:50:22,1,sourcing
147,148,594a9ce6c864e200288e766b,2017-06-21 12:20:54,source review,2017-06-22 06:03:24,1,"review, vetting, editing, sourcing, writing"
148,149,594aa36664251c002831f51e,2017-06-21 12:48:38,review,2017-06-22 05:39:55,1,review
149,150,594aa36664251c002831f51e,2017-06-21 12:48:38,review,2017-06-22 05:39:53,1,review
150,151,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 23:11:54,1,"sourcing, writing"
151,152,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 23:05:29,2,"sourcing, writing"
152,153,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 23:06:39,1,"sourcing, writing"
153,154,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 23:06:55,1,"sourcing, writing"
154,155,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:07:02,1,"editing, sourcing, writing"
155,156,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-22 01:43:24,1,writing
156,157,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-22 01:43:21,1,writing
157,158,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:08:11,1,writing
158,159,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:08:46,1,writing
159,160,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:08:46,1,writing
160,161,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:09:21,2,writing
161,162,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:11:41,1,writing
162,163,594ab554c864e200288e76ef,2017-06-21 14:05:08,review,2017-06-22 01:29:55,1,"review, planning, editing, sourcing, writing"
163,164,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:12:16,2,writing
164,165,594ab554c864e200288e76ef,2017-06-21 14:05:08,review,2017-06-22 01:29:45,1,"review, planning, editing, sourcing, writing"
165,166,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:33:20,1,"sourcing, writing"
166,167,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:12:16,2,writing
167,168,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:12:51,2,writing
168,169,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:33:17,1,"sourcing, writing"
169,170,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:33:17,2,"sourcing, writing"
170,171,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:32:42,1,"sourcing, writing"
171,172,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 23:04:54,1,"sourcing, writing"
172,173,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 23:04:54,1,"sourcing, writing"
173,174,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-22 02:10:14,1,"sourcing, writing"
174,175,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:07:01,1,"editing, sourcing, writing"
175,176,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 23:04:19,1,"sourcing, writing"
176,177,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 23:12:02,1,"sourcing, writing"
177,178,594ab554c864e200288e76ef,2017-06-21 14:05:08,review,2017-06-22 05:33:55,27,review
178,179,594ab554c864e200288e76ef,2017-06-21 14:05:08,review,2017-06-22 05:33:48,27,review
179,180,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-22 03:37:11,1,"sourcing, writing"
180,181,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-22 03:37:07,1,"sourcing, writing"
181,182,594ab554c864e200288e76ef,2017-06-21 14:05:08,source review,2017-06-21 20:52:31,1,review
182,183,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:21:39,1,"sourcing, writing"
183,184,594ab554c864e200288e76ef,2017-06-21 14:05:08,source review,2017-06-21 20:52:37,1,review
184,185,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:00:41,46,writing
185,186,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-22 02:44:04,1,writing
186,187,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-22 02:27:28,1,writing
187,188,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:01:16,46,writing
188,189,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:01:16,46,writing
189,190,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:01:48,47,writing
190,191,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-22 02:27:27,1,writing
191,192,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-22 02:44:14,1,writing
192,193,594ab554c864e200288e76ef,2017-06-21 14:05:08,writing,2017-06-21 21:21:36,1,"sourcing, writing"
193,194,594ada897a05b40035f08be4,2017-06-21 16:43:53,review,2017-06-22 02:49:55,1,"review, planning, editing, sourcing, writing"
194,195,594ada897a05b40035f08be4,2017-06-21 16:43:53,review,2017-06-22 02:49:58,1,"review, planning, editing, sourcing, writing"

In [137]:
# save request csv to a file
requests.to_csv (r'request_table.csv', index = None, header=True)

In [139]:
# write records stored in the dataframe to SQL database
df = pd.read_csv('request_table.csv')
df.to_sql('request_table', con = conn, if_exists='append', index=False)

In [144]:
# SQL query to find which requests are still in review, planning, editing, sourcing, writing

cur.execute('''SELECT *
               FROM request_table
               WHERE waiting_for = 'review, planning, editing, sourcing, writing'
               GROUP BY request''')                             # sql query
waiting_for = pd.DataFrame(cur.fetchall())                      # create dataframe from sql query
waiting_for.columns = [x[0] for x in cur.description]           # labels dataframe columns
waiting_for.head()                                                     # view dataframe

,record,request,request_created_at,job,event_occured_at,wait_time_min,waiting_for
0,1,59480d57e759070028da6467,2017-06-19 13:43:51,review,2017-06-21 21:50:31,1,"review, planning, editing, sourcing, writing"
1,13,59485c262e71030033104e3c,2017-06-19 19:20:06,source review,2017-06-22 01:39:39,1,"review, planning, editing, sourcing, writing"
2,25,59494c13d9ae5200633f9695,2017-06-20 12:23:47,review,2017-06-21 22:00:10,1,"review, planning, editing, sourcing, writing"
3,38,5949a81c4d1319005556396c,2017-06-20 18:56:28,source review,2017-06-22 00:58:58,1,"review, planning, editing, sourcing, writing"
4,79,594a5e5566cb69006fdcf09d,2017-06-21 07:53:57,review,2017-06-22 01:18:51,1,"review, planning, editing, sourcing, writing"

#### Create Assigments Status

In [156]:
# create SQL database for analyst availability

cur.execute('''SELECT record,
                      event_occured_at,
                      analysts_available, 
                      analysts_occupied,
                      total_jobs_available, 
                      review_jobs_available,
                      vetting_jobs_avaiable, 
                      planning_jobs_available,
                      editing_jobs_available, 
                      sourcing_jobs_available,
                      writing_jobs_available
               FROM master_table
               ORDER BY event_occured_at DESC''')                        # sql query
availability = pd.DataFrame(cur.fetchall())                              # create dataframe from sql query
availability.columns = [x[0] for x in cur.description]                   # labels dataframe columns
availability                                                             # view dataframe

,record,event_occured_at,analysts_available,analysts_occupied,total_jobs_available,review_jobs_available,vetting_jobs_avaiable,planning_jobs_available,editing_jobs_available,sourcing_jobs_available,writing_jobs_available
0,608,2017-06-22 19:59:06,0,13,14,4,6,2,0,1,1
1,606,2017-06-22 19:59:02,1,13,15,5,6,2,0,1,1
2,663,2017-06-22 19:51:30,1,12,12,5,5,1,0,0,1
3,774,2017-06-22 19:51:01,1,11,12,5,5,1,0,0,1
4,673,2017-06-22 19:50:58,2,11,14,5,5,2,0,1,1
5,681,2017-06-22 19:50:58,2,11,14,5,5,2,0,1,1
6,773,2017-06-22 19:50:58,2,11,14,5,5,2,0,1,1
7,685,2017-06-22 19:50:23,1,11,14,5,5,2,0,1,1
8,767,2017-06-22 19:47:03,1,11,11,5,5,1,0,0,0
9,770,2017-06-22 19:46:56,2,12,13,5,5,2,0,1,0
10,599,2017-06-22 19:44:03,1,10,11,5,5,1,0,0,0
11,604,2017-06-22 19:44:01,2,10,12,6,5,1,0,0,0
12,682,2017-06-22 19:40:41,2,9,12,6,5,1,0,0,0
13,684,2017-06-22 19:40:37,3,9,13,6,5,1,0,0,1
14,788,2017-06-22 19:35:59,2,11,10,5,4,1,0,0,0
15,789,2017-06-22 19:35:56,3,11,11,5,5,1,0,0,0
16,745,2017-06-22 19:31:18,2,10,11,5,5,1,0,0,0
17,746,2017-06-22 19:31:15,2,10,13,5,5,2,0,1,0
18,786,2017-06-22 19:25:28,1,12,10,5,4,1,0,0,0
19,787,2017-06-22 19:25:25,2,12,11,5,5,1,0,0,0
20,785,2017-06-22 19:20:23,1,14,8,3,4,1,0,0,0
21,784,2017-06-22 19:20:09,2,14,9,3,5,1,0,0,0
22,783,2017-06-22 19:18:59,2,14,9,3,5,1,0,0,0
23,703,2017-06-22 19:15:06,1,15,9,3,5,1,0,0,0
24,781,2017-06-22 19:14:59,2,14,11,3,5,2,0,1,0
25,701,2017-06-22 19:14:53,3,14,12,3,6,2,0,1,0
26,782,2017-06-22 19:14:53,3,14,12,3,6,2,0,1,0
27,707,2017-06-22 19:09:03,2,14,11,2,6,2,0,1,0
28,711,2017-06-22 19:08:28,2,14,11,2,6,2,0,1,0
29,724,2017-06-22 19:08:28,2,14,11,2,6,2,0,1,0
30,558,2017-06-22 19:07:55,2,13,11,2,6,2,0,1,0
31,557,2017-06-22 19:07:53,3,13,12,3,6,2,0,1,0
32,722,2017-06-22 19:07:53,3,13,12,3,6,2,0,1,0
33,729,2017-06-22 19:06:14,2,13,10,3,6,1,0,0,0
34,741,2017-06-22 19:06:08,3,13,12,3,6,2,0,1,0
35,780,2017-06-22 19:00:59,3,13,9,3,6,0,0,0,0
36,779,2017-06-22 19:00:52,4,13,10,3,7,0,0,0,0
37,714,2017-06-22 19:00:19,2,12,10,3,7,0,0,0,0
38,715,2017-06-22 19:00:17,3,12,12,3,7,1,0,1,0
39,718,2017-06-22 18:59:12,2,12,10,3,7,0,0,0,0
40,727,2017-06-22 18:59:07,4,12,12,3,7,1,0,1,0
41,728,2017-06-22 18:59:07,4,12,12,3,7,1,0,1,0
42,725,2017-06-22 18:58:32,4,12,12,3,7,1,0,1,0
43,726,2017-06-22 18:58:32,4,12,12,3,7,1,0,1,0
44,706,2017-06-22 18:57:57,5,12,12,3,7,1,0,1,0
45,713,2017-06-22 18:57:57,5,12,12,3,7,1,0,1,0
46,708,2017-06-22 18:57:21,5,12,12,3,7,1,0,1,0
47,723,2017-06-22 18:57:21,5,12,12,3,7,1,0,1,0
48,709,2017-06-22 18:56:46,4,12,12,3,7,1,0,1,0
49,762,2017-06-22 18:37:07,2,14,8,1,7,0,0,0,0
50,760,2017-06-22 18:36:56,3,14,9,2,7,0,0,0,0
51,607,2017-06-22 18:29:23,3,14,9,2,7,0,0,0,0
52,605,2017-06-22 18:29:21,4,14,10,3,7,0,0,0,0
53,704,2017-06-22 18:26:42,2,14,9,2,7,0,0,0,0
54,702,2017-06-22 18:26:26,4,14,11,2,7,1,0,1,0
55,719,2017-06-22 18:26:26,4,14,11,2,7,1,0,1,0
56,712,2017-06-22 18:25:51,4,15,11,2,7,1,0,1,0
57,716,2017-06-22 18:25:51,4,15,11,2,7,1,0,1,0
58,717,2017-06-22 18:25:16,4,15,11,2,7,1,0,1,0
59,564,2017-06-22 17:47:20,6,17,4,1,3,0,0,0,0
60,563,2017-06-22 17:47:18,6,17,5,2,3,0,0,0,0
61,523,2017-06-22 17:26:53,2,18,4,1,3,0,0,0,0
62,522,2017-06-22 17:26:52,3,18,5,2,3,0,0,0,0
63,244,2017-06-22 17:19:35,2,17,5,2,3,0,0,0,0
64,671,2017-06-22 17:19:26,3,16,6,3,3,0,0,0,0
65,251,2017-06-22 17:19:16,4,16,7,3,3,0,0,0,1
66,669,2017-06-22 17:19:16,4,16,7,3,3,0,0,0,1
67,670,2017-06-22 17:19:16,4,16,7,3,3,0,0,0,1
68,667,2017-06-22 17:18:41,4,16,7,3,3,0,0,0,1
69,668,2017-06-22 17:18:41,4,16,7,3,3,0,0,0,1
70,666,2017-06-22 17:18:06,3,16,7,3,3,0,0,0,1
71,634,2017-06-22 17:12:54,3,16,6,3,3,0,0,0,0
72,672,2017-06-22 17:12:52,4,16,7,3,3,0,0,0,1
73,636,2017-06-22 17:12:50,5,16,8,4,3,0,0,0,1
74,664,2017-06-22 17:12:50,5,16,8,4,3,0,0,0,1
75,637,2017-06-22 17:04:42,2,15,7,4,3,0,0,0,0
76,629,2017-06-22 17:04:40,3,15,8,5,3,0,0,0,0
77,593,2017-06-22 17:04:12,2,14,8,5,3,0,0,0,0
78,596,2017-06-22 17:04:05,3,14,9,5,3,0,0,0,1
79,568,2017-06-22 17:03:03,2,14,8,5,3,0,0,0,0
80,574,2017-06-22 17:02:54,4,14,9,5,3,0,0,1,0
81,576,2017-06-22 17:02:54,4,14,9,5,3,0,0,1,0
82,573,2017-06-22 17:02:19,4,14,9,5,3,0,0,1,0
83,575,2017-06-22 17:02:19,4,14,9,5,3,0,0,1,0
84,569,2017-06-22 17:01:44,5,14,9,5,3,0,0,1,0
85,571,2017-06-22 17:01:44,5,14,9,5,3,0,0,1,0
86,570,2017-06-22 17:01:09,5,14,9,5,3,0,0,1,0
87,572,2017-06-22 17:01:09,5,14,9,5,3,0,0,1,0
88,567,2017-06-22 17:00:34,4,14,9,5,3,0,0,1,0
89,597,2017-06-22 16:53:00,3,14,5,5,0,0,0,0,0
90,594,2017-06-22 16:52:58,4,14,6,6,0,0,0,0,0
91,595,2017-06-22 16:46:32,4,14,6,6,0,0,0,0,0
92,539,2017-06-22 16:37:46,4,14,6,6,0,0,0,0,0
93,537,2017-06-22 16:37:43,5,14,7,7,0,0,0,0,0
94,777,2017-06-22 16:29:48,4,15,6,6,0,0,0,0,0
95,778,2017-06-22 16:29:33,5,15,7,6,1,0,0,0,0
96,747,2017-06-22 16:17:23,2,15,5,5,0,0,0,0,0
97,752,2017-06-22 16:17:17,3,15,6,5,0,0,0,1,0
98,751,2017-06-22 16:09:53,0,17,4,4,0,0,0,0,0
99,748,2017-06-22 16:09:47,1,17,5,4,0,0,0,1,0
100,775,2017-06-22 16:05:31,0,18,3,2,0,0,0,1,0
101,776,2017-06-22 16:05:27,1,18,4,2,1,0,0,1,0
102,768,2017-06-22 16:02:15,0,19,3,2,1,0,0,0,0
103,769,2017-06-22 16:02:11,1,19,4,2,2,0,0,0,0
104,749,2017-06-22 16:01:43,0,18,4,2,2,0,0,0,0
105,750,2017-06-22 16:01:36,1,18,5,2,2,0,0,1,0
106,754,2017-06-22 15:57:43,2,19,5,2,2,0,0,1,0
107,753,2017-06-22 15:57:08,2,20,5,2,2,0,0,1,0
108,764,2017-06-22 15:57:08,2,20,5,2,2,0,0,1,0
109,772,2017-06-22 15:57:02,2,19,5,2,2,0,0,1,0
110,758,2017-06-22 15:56:33,3,19,6,2,3,0,0,1,0
111,771,2017-06-22 15:56:33,3,19,6,2,3,0,0,1,0
112,683,2017-06-22 15:50:34,1,19,4,2,2,0,0,0,0
113,680,2017-06-22 15:50:07,2,19,5,2,2,0,0,1,0
114,686,2017-06-22 15:50:07,2,19,5,2,2,0,0,1,0
115,679,2017-06-22 15:49:32,2,19,4,2,1,0,0,1,0
116,676,2017-06-22 15:47:47,2,19,4,2,1,0,0,1,0
117,565,2017-06-22 15:47:15,2,18,4,2,1,0,0,1,0
118,566,2017-06-22 15:47:12,3,18,5,2,1,1,0,1,0
119,674,2017-06-22 15:47:12,3,18,5,2,1,1,0,1,0
120,675,2017-06-22 15:47:12,3,18,5,2,1,1,0,1,0
121,665,2017-06-22 15:46:37,2,18,5,2,1,1,0,1,0
122,759,2017-06-22 15:37:20,4,18,3,2,0,1,0,0,0
123,761,2017-06-22 15:37:16,5,18,4,2,0,2,0,0,0
124,730,2017-06-22 15:34:23,5,19,4,2,0,2,0,0,0
125,731,2017-06-22 15:34:21,6,19,5,2,1,2,0,0,0
126,732,2017-06-22 15:33:11,6,19,5,2,1,2,0,0,0
127,733,2017-06-22 15:32:36,5,19,5,2,1,2,0,0,0
128,734,2017-06-22 15:32:36,5,19,5,2,1,2,0,0,0
129,735,2017-06-22 15:32:01,5,19,5,2,1,2,0,0,0
130,766,2017-06-22 15:30:50,5,19,5,2,1,2,0,0,0
131,765,2017-06-22 15:30:15,5,18,6,2,1,2,0,1,0
132,736,2017-06-22 15:27:20,5,17,4,2,1,1,0,0,0
133,737,2017-06-22 15:26:45,5,17,4,2,1,1,0,0,0
134,738,2017-06-22 15:26:45,5,17,4,2,1,1,0,0,0
135,739,2017-06-22 15:26:10,6,17,4,2,1,1,0,0,0
136,740,2017-06-22 15:23:50,8,17,4,2,1,1,0,0,0
137,742,2017-06-22 15:23:15,7,17,4,2,1,1,0,0,0
138,743,2017-06-22 15:23:15,7,17,4,2,1,1,0,0,0
139,744,2017-06-22 15:22:39,8,17,4,2,1,1,0,0,0
140,705,2017-06-22 15:19:23,7,17,4,2,1,1,0,0,0
141,710,2017-06-22 15:19:09,8,17,5,2,2,1,0,0,0
142,720,2017-06-22 15:19:09,8,17,5,2,2,1,0,0,0
143,721,2017-06-22 15:18:34,8,17,5,2,2,1,0,0,0
144,757,2017-06-22 15:16:09,5,17,5,2,2,1,0,0,0
145,756,2017-06-22 15:15:38,6,17,6,2,3,1,0,0,0
146,763,2017-06-22 15:15:38,6,17,6,2,3,1,0,0,0
147,651,2017-06-22 15:15:03,6,16,6,2,3,1,0,0,0
148,755,2017-06-22 15:15:03,6,16,6,2,3,1,0,0,0
149,653,2017-06-22 15:14:28,4,15,7,2,3,1,0,1,0
150,654,2017-06-22 15:14:28,4,15,7,2,3,1,0,1,0
151,656,2017-06-22 15:13:53,6,14,8,2,3,2,0,1,0
152,658,2017-06-22 15:13:53,6,14,8,2,3,2,0,1,0
153,655,2017-06-22 15:13:18,6,14,8,2,3,2,0,1,0
154,660,2017-06-22 15:13:18,6,14,8,2,3,2,0,1,0
155,691,2017-06-22 15:12:45,6,13,8,2,3,2,0,1,0
156,657,2017-06-22 15:12:42,8,13,9,2,4,2,0,1,0
157,661,2017-06-22 15:12:42,8,13,9,2,4,2,0,1,0
158,688,2017-06-22 15:12:42,8,13,9,2,4,2,0,1,0
159,690,2017-06-22 15:12:42,8,13,9,2,4,2,0,1,0
160,652,2017-06-22 15:12:07,7,13,9,2,4,2,0,1,0
161,662,2017-06-22 15:12:07,7,13,9,2,4,2,0,1,0
162,687,2017-06-22 15:12:07,7,13,9,2,4,2,0,1,0
163,659,2017-06-22 15:11:32,6,13,9,2,4,2,0,1,0
164,699,2017-06-22 15:06:54,6,15,7,1,3,3,0,0,0
165,697,2017-06-22 15:06:50,7,16,7,0,4,3,0,0,0
166,698,2017-06-22 15:06:50,7,16,7,0,4,3,0,0,0
167,696,2017-06-22 15:06:15,6,16,7,0,4,3,0,0,0
168,695,2017-06-22 15:05:05,6,16,6,0,3,3,0,0,0
169,694,2017-06-22 15:04:30,6,16,6,0,3,3,0,0,0
170,700,2017-06-22 15:04:30,6,16,6,0,3,3,0,0,0
171,693,2017-06-22 15:03:55,5,16,6,0,3,3,0,0,0
172,579,2017-06-22 14:59:17,5,15,6,0,3,3,0,0,0
173,586,2017-06-22 14:59:14,6,15,7,1,3,3,0,0,0
174,525,2017-06-22 14:57:01,5,16,7,1,3,3,0,0,0
175,511,2017-06-22 14:56:54,5,16,8,1,3,3,0,0,1
176,518,2017-06-22 14:54:37,4,14,7,1,3,3,0,0,0
177,515,2017-06-22 14:54:34,4,14,8,1,3,3,0,0,1
178,589,2017-06-22 14:49:53,5,15,7,1,3,3,0,0,0
179,628,2017-06-22 14:47:00,5,14,7,1,3,3,0,0,0
180,627,2017-06-22 14:46:57,6,14,8,1,3,3,0,1,0
181,626,2017-06-22 14:39:23,3,15,6,0,3,3,0,0,0
182,625,2017-06-22 14:39:21,4,15,7,0,3,4,0,0,0
183,640,2017-06-22 14:36:25,6,15,7,0,3,4,0,0,0
184,677,2017-06-22 14:35:52,6,14,7,0,3,4,0,0,0
185,678,2017-06-22 14:35:50,7,14,8,0,3,5,0,0,0
186,647,2017-06-22 14:33:36,5,14,7,0,3,4,0,0,0
187,646,2017-06-22 14:33:35,5,14,7,0,3,4,0,0,0
188,645,2017-06-22 14:33:29,6,14,8,0,3,4,0,1,0
189,547,2017-06-22 14:31:47,4,18,7,0,3,4,0,0,0
190,545,2017-06-22 14:31:43,5,18,9,0,3,5,0,1,0
191,650,2017-06-22 14:31:12,4,16,7,0,3,4,0,0,0
192,649,2017-06-22 14:31:08,5,16,8,0,3,5,0,0,0
193,642,2017-06-22 14:30:59,5,15,8,0,3,5,0,0,0
194,641,2017-06-22 14:30:54,5,15,8,0,3,5,0,0,0
195,648,2017-06-22 14:30:33,5,15,9,0,3,5,0,1,0
196,630,2017-06-22 14:24:23,4,15,7,0,2,5,0,0,0
197,631,2017-06-22 14:24:07,6,15,8,0,2,5,0,1,0
198,632,2017-06-22 14:10:41,4,13,7,0,2,5,0,0,0
199,633,2017-06-22 14:10:40,5,13,8,0,2,6,0,0,0
200,544,2017-06-22 14:04:23,2,12,8,0,2,6,0,0,0
201,543,2017-06-22 14:04:14,3,12,10,0,2,7,0,1,0
202,550,2017-06-22 14:02:36,4,11,7,0,1,6,0,0,0
203,560,2017-06-22 14:02:34,5,11,9,0,1,7,0,1,0
204,548,2017-06-22 14:02:28,6,11,11,0,1,8,0,2,0
205,559,2017-06-22 14:02:28,6,11,11,0,1,8,0,2,0
206,610,2017-06-22 13:43:27,6,11,8,0,1,7,0,0,0
207,611,2017-06-22 13:43:11,5,11,9,0,1,7,0,1,0
208,621,2017-06-22 13:42:38,6,12,8,0,1,7,0,0,0
209,623,2017-06-22 13:42:36,7,12,9,0,1,8,0,0,0
210,612,2017-06-22 13:38:35,6,11,9,0,1,8,0,0,0
211,613,2017-06-22 13:38:30,6,11,10,0,1,8,0,1,0
212,643,2017-06-22 13:32:46,4,12,9,0,1,8,0,0,0
213,644,2017-06-22 13:32:40,5,12,10,0,1,9,0,0,0
214,624,2017-06-22 13:29:19,3,11,9,0,1,8,0,0,0
215,638,2017-06-22 13:29:09,4,11,10,0,1,9,0,0,0
216,614,2017-06-22 13:28:01,4,10,10,0,1,9,0,0,0
217,639,2017-06-22 13:28:01,2,10,9,0,1,8,0,0,0
218,615,2017-06-22 13:27:59,5,10,11,0,1,10,0,0,0
219,635,2017-06-22 13:27:59,5,10,11,0,1,10,0,0,0
220,620,2017-06-22 13:26:19,3,11,10,0,1,9,0,0,0
221,622,2017-06-22 13:26:14,4,10,11,0,1,10,0,0,0
222,520,2017-06-22 13:25:08,4,10,9,0,0,9,0,0,0
223,689,2017-06-22 13:25:06,5,10,10,0,0,9,0,0,1
224,527,2017-06-22 13:25:03,6,10,11,0,1,9,0,0,1
225,692,2017-06-22 13:25:03,6,10,11,0,1,9,0,0,1
226,619,2017-06-22 13:24:35,5,9,11,0,1,10,0,0,0
227,618,2017-06-22 13:24:28,6,10,12,0,1,11,0,0,0
228,601,2017-06-22 13:22:16,5,9,10,0,0,10,0,0,0
229,592,2017-06-22 13:22:08,7,9,11,0,0,10,0,1,0
230,617,2017-06-22 13:22:08,7,9,11,0,0,10,0,1,0
231,517,2017-06-22 13:21:01,5,9,10,0,0,10,0,0,0
232,516,2017-06-22 13:20:58,6,9,11,1,0,10,0,0,0
233,603,2017-06-22 13:20:25,4,8,10,0,0,10,0,0,0
234,602,2017-06-22 13:20:23,5,8,11,0,0,11,0,0,0
235,582,2017-06-22 13:19:50,3,7,11,0,0,11,0,0,0
236,580,2017-06-22 13:19:48,5,7,12,0,0,11,0,1,0
237,581,2017-06-22 13:19:48,5,7,12,0,0,11,0,1,0
238,587,2017-06-22 13:19:13,5,8,12,0,0,11,0,1,0
239,588,2017-06-22 13:19:13,5,8,12,0,0,11,0,1,0
240,583,2017-06-22 13:18:37,5,8,12,0,0,11,0,1,0
241,37,2017-06-22 13:16:28,6,10,10,0,0,10,0,0,0
242,32,2017-06-22 13:16:17,6,10,11,0,0,10,1,0,0
243,609,2017-06-22 13:12:52,4,8,11,0,0,10,1,0,0
244,616,2017-06-22 13:12:47,5,8,12,0,0,11,1,0,0
245,600,2017-06-22 13:09:23,5,8,10,0,0,10,0,0,0
246,584,2017-06-22 13:09:19,6,8,11,0,0,11,0,0,0
247,585,2017-06-22 13:09:17,7,8,12,0,0,12,0,0,0
248,598,2017-06-22 13:09:17,7,8,12,0,0,12,0,0,0
249,238,2017-06-22 13:05:52,4,9,11,0,0,11,0,0,0
250,239,2017-06-22 13:05:46,5,9,12,0,0,11,0,0,1
251,591,2017-06-22 12:58:51,4,7,12,0,0,11,0,0,1
252,590,2017-06-22 12:58:46,5,7,13,0,0,12,0,0,1
253,236,2017-06-22 12:54:05,7,7,13,0,0,12,0,0,1
254,241,2017-06-22 12:53:30,4,7,13,0,0,12,0,0,1
255,42,2017-06-22 12:46:09,2,7,12,0,0,12,0,0,0
256,43,2017-06-22 12:46:02,3,7,13,0,0,12,1,0,0
257,44,2017-06-22 12:38:43,3,7,12,0,0,12,0,0,0
258,45,2017-06-22 12:38:26,4,7,13,0,0,12,1,0,0
259,46,2017-06-22 12:18:33,3,7,12,0,0,12,0,0,0
260,47,2017-06-22 12:18:31,4,7,13,1,0,12,0,0,0
261,577,2017-06-22 12:09:49,1,7,1,1,0,0,0,0,0
262,578,2017-06-22 12:09:45,2,7,2,1,1,0,0,0,0
263,351,2017-06-22 12:00:28,2,7,1,1,0,0,0,0,0
264,350,2017-06-22 12:00:23,3,7,2,2,0,0,0,0,0
265,49,2017-06-22 11:10:45,5,9,0,0,0,0,0,0,0
266,58,2017-06-22 11:10:42,5,9,1,1,0,0,0,0,0
267,242,2017-06-22 10:59:40,6,9,0,0,0,0,0,0,0
268,255,2017-06-22 10:59:35,7,9,1,0,0,0,0,0,1
269,549,2017-06-22 10:57:18,6,9,0,0,0,0,0,0,0
270,553,2017-06-22 10:57:15,7,9,1,0,1,0,0,0,0
271,529,2017-06-22 10:55:33,6,9,1,0,1,0,0,0,0
272,531,2017-06-22 10:55:30,6,9,2,1,1,0,0,0,0
273,479,2017-06-22 10:47:23,2,8,1,0,1,0,0,0,0
274,478,2017-06-22 10:47:21,2,8,1,0,1,0,0,0,0
275,477,2017-06-22 10:47:19,3,8,2,1,1,0,0,0,0
276,476,2017-06-22 10:39:49,3,8,1,0,1,0,0,0,0
277,484,2017-06-22 10:39:48,3,8,1,0,1,0,0,0,0
278,473,2017-06-22 10:39:44,5,8,2,1,1,0,0,0,0
279,474,2017-06-22 10:39:44,5,8,2,1,1,0,0,0,0
280,469,2017-06-22 10:39:09,5,8,2,1,1,0,0,0,0
281,470,2017-06-22 10:39:09,5,8,2,1,1,0,0,0,0
282,487,2017-06-22 10:38:34,5,8,2,1,1,0,0,0,0
283,561,2017-06-22 10:33:32,4,9,1,0,1,0,0,0,0
284,562,2017-06-22 10:33:19,5,9,1,0,1,0,0,0,0
285,554,2017-06-22 10:31:41,4,9,1,0,1,0,0,0,0
286,556,2017-06-22 10:31:34,5,9,2,0,2,0,0,0,0
287,555,2017-06-22 10:30:27,5,9,1,0,1,0,0,0,0
288,552,2017-06-22 10:30:23,6,9,2,0,2,0,0,0,0
289,249,2017-06-22 10:27:41,6,9,2,0,2,0,0,0,0
290,243,2017-06-22 10:27:28,6,9,3,0,2,0,0,0,1
291,492,2017-06-22 10:25:53,4,9,2,0,2,0,0,0,0
292,490,2017-06-22 10:25:51,5,9,3,0,2,0,0,0,1
293,551,2017-06-22 10:24:43,4,10,1,0,1,0,0,0,0
294,546,2017-06-22 10:24:41,5,10,2,0,2,0,0,0,0
295,250,2017-06-22 10:23:33,4,9,2,0,2,0,0,0,0
296,252,2017-06-22 10:23:31,5,9,3,0,2,0,0,0,1
297,541,2017-06-22 10:11:24,2,9,3,0,2,0,0,0,1
298,542,2017-06-22 10:11:15,3,9,4,0,3,0,0,0,1
299,528,2017-06-22 09:58:49,1,9,0,0,0,0,0,0,0
300,524,2017-06-22 09:58:24,3,9,2,0,0,1,0,1,0
301,526,2017-06-22 09:58:24,3,9,2,0,0,1,0,1,0
302,512,2017-06-22 09:57:49,3,9,2,0,0,1,0,1,0
303,513,2017-06-22 09:57:49,3,9,2,0,0,1,0,1,0
304,514,2017-06-22 09:57:14,3,10,2,0,0,1,0,1,0
305,128,2017-06-22 09:50:15,3,9,0,0,0,0,0,0,0
306,121,2017-06-22 09:50:13,4,9,1,0,0,0,0,0,1
307,122,2017-06-22 09:25:49,2,9,0,0,0,0,0,0,0
308,123,2017-06-22 09:25:42,3,9,1,1,0,0,0,0,0
309,124,2017-06-22 09:24:32,3,9,1,1,0,0,0,0,0
310,125,2017-06-22 09:23:56,3,9,1,1,0,0,0,0,0
311,126,2017-06-22 09:23:56,3,9,1,1,0,0,0,0,0
312,127,2017-06-22 09:23:21,3,9,1,1,0,0,0,0,0
313,102,2017-06-22 09:05:24,1,10,0,0,0,0,0,0,0
314,101,2017-06-22 09:05:23,1,10,0,0,0,0,0,0,0
315,100,2017-06-22 09:05:15,2,10,1,1,0,0,0,0,0
316,99,2017-06-22 09:01:12,2,10,0,0,0,0,0,0,0
317,104,2017-06-22 09:01:10,3,10,1,1,0,0,0,0,0
318,493,2017-06-22 08:58:53,3,10,1,1,0,0,0,0,0
319,496,2017-06-22 08:58:50,4,10,2,2,0,0,0,0,0
320,468,2017-06-22 08:57:07,2,9,2,2,0,0,0,0,0
321,460,2017-06-22 08:57:04,3,9,3,2,0,0,1,0,0
322,455,2017-06-22 08:32:44,3,10,0,0,0,0,0,0,0
323,456,2017-06-22 08:32:39,3,10,1,0,0,0,1,0,0
324,457,2017-06-22 08:32:39,3,10,1,0,0,0,1,0,0
325,458,2017-06-22 08:32:04,2,10,1,0,0,0,1,0,0
326,530,2017-06-22 08:21:36,2,13,0,0,0,0,0,0,0
327,533,2017-06-22 08:21:33,3,13,1,0,0,0,0,1,0
328,462,2017-06-22 08:18:37,3,12,1,0,0,1,0,0,0
329,463,2017-06-22 08:18:35,4,12,2,1,0,1,0,0,0
330,489,2017-06-22 08:12:12,3,12,1,0,0,1,0,0,0
331,491,2017-06-22 08:12:09,4,11,2,0,0,1,0,0,1
332,353,2017-06-22 08:11:39,4,10,2,0,0,1,0,0,1
333,352,2017-06-22 08:11:34,4,10,3,0,0,1,0,0,2
334,305,2017-06-22 08:06:22,5,10,2,0,0,1,0,0,1
335,301,2017-06-22 08:06:19,6,10,3,0,0,1,0,0,2
336,130,2017-06-22 08:03:26,4,10,3,0,0,1,0,0,2
337,145,2017-06-22 08:03:23,4,10,4,0,0,1,0,1,2
338,144,2017-06-22 08:01:25,3,10,3,0,0,1,0,0,2
339,143,2017-06-22 08:01:22,3,10,3,0,0,1,0,0,2
340,142,2017-06-22 08:01:20,3,10,3,0,0,1,0,0,2
341,140,2017-06-22 08:01:03,5,10,4,0,0,1,0,1,2
342,141,2017-06-22 08:01:03,5,10,4,0,0,1,0,1,2
343,138,2017-06-22 08:00:28,4,10,3,0,0,0,0,1,2
344,139,2017-06-22 08:00:28,4,10,3,0,0,0,0,1,2
345,137,2017-06-22 07:59:53,2,11,2,0,0,0,0,1,1
346,349,2017-06-22 07:58:48,3,10,1,0,0,0,0,0,1
347,354,2017-06-22 07:58:43,4,10,2,0,0,0,0,0,2
348,299,2017-06-22 07:58:17,4,9,2,0,0,0,0,0,2
349,298,2017-06-22 07:58:08,4,9,3,0,0,0,0,0,3
350,391,2017-06-22 07:43:36,1,10,2,0,0,0,0,0,2
351,407,2017-06-22 07:43:32,2,10,3,0,0,0,0,0,3
352,296,2017-06-22 07:41:50,2,9,4,0,1,0,0,0,3
353,538,2017-06-22 07:41:50,1,9,3,0,0,0,0,0,3
354,295,2017-06-22 07:41:47,3,9,5,0,1,0,0,0,4
355,540,2017-06-22 07:41:47,3,9,5,0,1,0,0,0,4
356,536,2017-06-22 07:38:58,1,10,3,0,0,0,0,0,3
357,535,2017-06-22 07:38:52,2,10,4,0,1,0,0,0,3
358,519,2017-06-22 07:36:37,2,9,3,0,0,0,0,0,3
359,247,2017-06-22 07:36:35,3,9,4,0,1,0,0,0,3
360,245,2017-06-22 07:36:32,4,9,5,0,1,0,0,0,4
361,521,2017-06-22 07:36:32,4,9,5,0,1,0,0,0,4
362,532,2017-06-22 07:34:49,1,9,5,0,1,0,0,0,4
363,534,2017-06-22 07:34:47,2,9,6,0,2,0,0,0,4
364,488,2017-06-22 07:33:21,1,9,5,0,2,0,0,0,3
365,486,2017-06-22 07:33:02,2,9,6,1,2,0,0,0,3
366,306,2017-06-22 07:27:48,1,9,5,1,2,0,0,0,2
367,308,2017-06-22 07:27:46,2,9,6,2,2,0,0,0,2
368,98,2017-06-22 07:23:45,2,7,7,2,2,0,0,0,3
369,448,2017-06-22 07:23:45,1,7,6,2,2,0,0,0,2
370,106,2017-06-22 07:23:41,3,7,8,2,2,0,0,0,4
371,445,2017-06-22 07:23:41,3,7,8,2,2,0,0,0,4
372,397,2017-06-22 07:03:53,1,8,6,1,2,0,0,0,3
373,398,2017-06-22 07:03:50,2,8,7,1,2,0,0,0,4
374,401,2017-06-22 07:03:50,2,8,7,1,2,0,0,0,4
375,400,2017-06-22 07:03:15,2,8,7,1,2,0,0,0,4
376,444,2017-06-22 06:59:51,1,7,7,1,2,0,0,0,4
377,450,2017-06-22 06:59:45,2,7,8,2,2,0,0,0,4
378,234,2017-06-22 06:47:37,2,7,8,2,2,0,0,0,4
379,223,2017-06-22 06:47:33,3,7,9,3,2,0,0,0,4
380,403,2017-06-22 06:36:27,3,8,6,1,1,0,0,0,4
381,404,2017-06-22 06:35:52,2,9,6,1,1,0,0,0,4
382,405,2017-06-22 06:35:52,2,9,6,1,1,0,0,0,4
383,406,2017-06-22 06:35:17,2,9,6,1,1,0,0,0,4
384,134,2017-06-22 06:20:10,0,10,5,1,1,0,0,0,3
385,133,2017-06-22 06:20:08,1,10,6,1,1,0,0,1,3
386,7,2017-06-22 06:19:35,0,9,6,1,1,0,0,1,3
387,8,2017-06-22 06:19:33,1,9,7,2,1,0,0,1,3
388,216,2017-06-22 06:18:00,0,10,5,2,1,0,0,0,2
389,217,2017-06-22 06:17:54,1,10,6,3,1,0,0,0,2
390,96,2017-06-22 06:13:40,0,9,6,3,1,0,0,0,2
391,103,2017-06-22 06:13:34,1,9,7,3,1,0,0,0,3
392,105,2017-06-22 06:05:44,2,11,5,1,1,0,0,0,3
393,146,2017-06-22 06:03:29,1,10,5,1,1,0,0,0,3
394,148,2017-06-22 06:03:24,2,10,6,2,1,0,0,0,3
395,55,2017-06-22 06:01:43,1,10,6,2,1,0,0,0,3
396,39,2017-06-22 06:01:39,2,10,7,2,1,0,0,0,4
397,48,2017-06-22 05:53:46,0,11,3,0,0,0,0,0,3
398,34,2017-06-22 05:53:43,1,11,4,0,0,0,0,0,4
399,276,2017-06-22 05:52:15,0,12,3,0,0,0,0,0,3
400,271,2017-06-22 05:52:04,1,12,4,1,0,0,0,0,3
401,33,2017-06-22 05:46:13,0,13,4,1,0,0,0,0,3
402,27,2017-06-22 05:46:09,1,13,5,2,0,0,0,0,3
403,108,2017-06-22 05:43:14,1,13,4,1,0,0,0,0,3
404,107,2017-06-22 05:42:42,1,13,4,1,0,0,0,0,3
405,113,2017-06-22 05:42:42,1,13,4,1,0,0,0,0,3
406,110,2017-06-22 05:42:07,1,13,4,1,0,0,0,0,3
407,272,2017-06-22 05:40:37,0,13,3,0,0,0,0,0,3
408,273,2017-06-22 05:40:28,1,13,4,1,0,0,0,0,3
409,275,2017-06-22 05:40:28,1,13,4,1,0,0,0,0,3
410,149,2017-06-22 05:39:55,2,12,4,1,0,0,0,0,3
411,111,2017-06-22 05:39:53,3,12,5,2,0,0,0,0,3
412,112,2017-06-22 05:39:53,3,12,5,2,0,0,0,0,3
413,150,2017-06-22 05:39:53,3,12,5,2,0,0,0,0,3
414,268,2017-06-22 05:39:53,3,12,5,2,0,0,0,0,3
415,118,2017-06-22 05:39:18,1,12,5,2,0,0,0,0,3
416,28,2017-06-22 05:37:10,0,12,4,1,0,0,0,0,3
417,29,2017-06-22 05:37:07,1,12,5,2,0,0,0,0,3
418,294,2017-06-22 05:34:41,0,14,3,0,0,0,0,0,3
419,293,2017-06-22 05:34:23,1,14,4,0,0,0,0,1,3
420,178,2017-06-22 05:33:55,1,13,4,0,0,0,0,1,3
421,179,2017-06-22 05:33:48,1,13,5,1,0,0,0,1,3
422,510,2017-06-22 05:31:32,1,14,3,0,0,0,0,0,3

Notes: All the sourcing scores and writing scores are the same for each analyst
    Is there a link between number of analysts available and the wait time?
    There needs to be a 'closed/submitted to client' action item